# Generated by Django 5.0.6 on 2026-03-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0009_efrishscode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesapalIPNLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_tracking_id', models.CharField(db_index=True, max_length=101)),
                ('order_merchant_reference', models.CharField(max_length=100)),
                ('order_notification_type', models.CharField(choices=[('IPNCHANGE', 'IPN Change'), ('RECURRING', 'Recurring'), ('CALLBACKURL', 'Callback')], max_length=20)),
                ('source', models.CharField(choices=[('platform', 'Platform (SaaS billing)'), ('tenant', 'Tenant (customer payment)')], default='tenant', max_length=20)),
                ('tenant_schema', models.CharField(blank=True, max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_params', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'IPN Log',
                'verbose_name_plural': 'IPN Logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=60, unique=True)),
                ('merchant_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('pesapal_tracking_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('pesapal_confirmation', models.CharField(blank=True, max_length=200)),
                ('redirect_url', models.URLField(blank=True, max_length=1000)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_account', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_invoices', to='company.company')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Platform Invoice',
                'verbose_name_plural': 'Platform Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('merchant_reference', models.CharField(db_index=True, max_length=100)),
                ('order_tracking_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('confirmation_code', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_account', models.CharField(blank=True, max_length=100)),
                ('payment_type', models.CharField(choices=[('INVOICE', 'Invoice Payment'), ('SUBSCRIPTION', 'Subscription'), ('ONE_TIME', 'One-time')], default='ONE_TIME', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('INVALID', 'Invalid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('redirect_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesapal_transactions', to='company.company')),
            ],
            options={
                'verbose_name': 'Tenant Payment Transaction',
                'verbose_name_plural': 'Tenant Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPesapalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_own_keys', models.BooleanField(default=False, help_text='If True, use the keys below. Otherwise use platform keys.')),
                ('consumer_key', models.CharField(blank=True, max_length=300)),
                ('consumer_secret', models.CharField(blank=True, max_length=300)),
                ('ipn_id', models.CharField(blank=True, help_text='Pesapal IPN ID registered for this tenant.', max_length=100)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pesapal_config', to='company.company')),
            ],
            options={
                'verbose_name': 'Tenant Pesapal Config',
                'verbose_name_plural': 'Tenant Pesapal Configs',
            },
        ),
    ]
