# Generated by Django 5.0.6 on 2026-03-24 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_availablemodule_companymodule'),
        ('pesapal_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminvoice',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Set when this invoice is for a module add-on purchase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_invoices', to='company.availablemodule'),
        ),
    ]
