# Generated by Django 5.0.6 on 2026-03-17 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usernavigationpreference',
            name='workspace_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TenantWorkspaceDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_mode', models.CharField(default='sidebar', max_length=20)),
                ('header_order', models.JSONField(blank=True, default=list)),
                ('sidebar_order', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Workspace Default',
            },
        ),
    ]
