# Generated by Django 5.0.6 on 2026-03-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usernavigationpreference_workspace_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantworkspacedefault',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict, help_text='Tenant-wide theme/accessibility defaults (accentColor, fontSize, density, highContrast, etc.)'),
        ),
    ]
