# Generated by Django 5.0.6 on 2025-11-17 04:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import invoices.efris
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, verbose_name='Invoice Number')),
                ('fiscalization_error', models.TextField(blank=True, help_text='Error message if fiscalization failed', null=True, verbose_name='Fiscalization Error')),
                ('efris_status', models.CharField(blank=True, help_text='Current status from EFRIS system', max_length=50, null=True, verbose_name='EFRIS Status')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_PAID', 'Partially Paid')], default='DRAFT', max_length=20)),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('PROFORMA', 'Proforma Invoice')], default='INVOICE', max_length=20)),
                ('efris_document_type', models.CharField(choices=[('1', 'Normal Invoice'), ('2', 'Credit Note'), ('3', 'Debit Note'), ('4', 'Proforma Invoice')], default='1', max_length=2, verbose_name='EFRIS Document Type')),
                ('business_type', models.CharField(blank=True, choices=[('B2C', 'Business to Consumer'), ('B2B', 'Business to Business'), ('B2G', 'Business to Government')], max_length=3, verbose_name='Business Type')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fiscal_document_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Fiscal Document Number')),
                ('fiscal_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=255, verbose_name='Verification Code')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR Code Data')),
                ('currency_code', models.CharField(default='UGX', max_length=3, verbose_name='Currency')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=10, verbose_name='Exchange Rate to UGX')),
                ('ugx_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='UGX Subtotal')),
                ('ugx_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='UGX Tax Amount')),
                ('ugx_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='UGX Total Amount')),
                ('device_number', models.CharField(blank=True, max_length=50, verbose_name='Device Number')),
                ('operator_name', models.CharField(blank=True, max_length=100, verbose_name='Operator Name')),
                ('fiscalization_status', models.CharField(choices=[('pending', 'Pending Fiscalization'), ('fiscalized', 'Fiscalized'), ('failed', 'Fiscalization Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15, verbose_name='Fiscalization Status')),
                ('is_fiscalized', models.BooleanField(db_index=True, default=False)),
                ('fiscalization_time', models.DateTimeField(blank=True, null=True)),
                ('original_fdn', models.CharField(blank=True, help_text='For credit/debit notes', max_length=50, verbose_name='Original FDN')),
                ('requires_ura_approval', models.BooleanField(default=False, verbose_name='Requires URA Approval')),
                ('ura_approved', models.BooleanField(default=False, verbose_name='URA Approved')),
                ('ura_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='URA Approval Date')),
                ('auto_fiscalize', models.BooleanField(default=True, help_text='Automatically fiscalize when invoice is sent', verbose_name='Auto-Fiscalize')),
                ('notes', models.TextField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('fiscalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscalized_invoices', to=settings.AUTH_USER_MODEL)),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.sale', verbose_name='Sale')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='stores.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date'],
                'permissions': [('fiscalize_invoice', 'Can fiscalize invoices with EFRIS'), ('manage_credit_notes', 'Can create and manage credit notes')],
            },
            bases=(models.Model, invoices.efris.EFRISInvoiceMixin),
        ),
        migrations.CreateModel(
            name='FiscalizationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('FISCALIZE', 'Fiscalized'), ('RETRY', 'Retry Fiscalization'), ('ERROR', 'Fiscalization Error'), ('URA_APPROVAL', 'URA Approval'), ('EFRIS_SUBMIT', 'EFRIS Submission')], max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('efris_response', models.JSONField(blank=True, default=dict)),
                ('fiscal_document_number', models.CharField(blank=True, max_length=50, verbose_name='Fiscal Document Number')),
                ('verification_code', models.CharField(blank=True, max_length=255, verbose_name='Verification Code')),
                ('device_number', models.CharField(blank=True, max_length=50, verbose_name='Device Number')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscalization_audits', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Fiscalization Audit',
                'verbose_name_plural': 'Fiscalization Audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('OTHER', 'Other')], max_length=20, verbose_name='Payment Method')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Reference')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice', verbose_name='Invoice')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Invoice Payment',
                'verbose_name_plural': 'Invoice Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('template_file', models.FileField(upload_to='invoice_templates/', verbose_name='Template File')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Template')),
                ('is_efris_compliant', models.BooleanField(default=False, help_text='Whether this template meets URA requirements', verbose_name='EFRIS Compliant')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Invoice Template',
                'verbose_name_plural': 'Invoice Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_in_invoice_e6b546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['fiscal_document_number'], name='invoices_in_fiscal__10d142_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['fiscal_number'], name='invoices_in_fiscal__48e033_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_fiscalized'], name='invoices_in_is_fisc_eab6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['fiscalization_status'], name='invoices_in_fiscali_892395_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['business_type'], name='invoices_in_busines_3eee58_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['efris_document_type'], name='invoices_in_efris_d_a9114f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['store', 'issue_date'], name='invoices_in_store_i_7535e6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='invoices_in_status_041490_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('invoice_number',), name='unique_invoice_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('fiscal_document_number__isnull', False), models.Q(('fiscal_document_number', ''), _negated=True)), fields=('fiscal_document_number',), name='unique_fiscal_document_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('fiscal_number__isnull', False), models.Q(('fiscal_number', ''), _negated=True)), fields=('fiscal_number',), name='unique_fiscal_number_per_tenant'),
        ),
    ]
