# Generated by Django 5.0.6 on 2025-12-04 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('sales', '0003_alter_saleitem_product'),
        ('stores', '0002_store_store_auto_fiscalize_sales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'permissions': [('fiscalize_invoice', 'Can fiscalize invoices with EFRIS'), ('manage_credit_notes', 'Can create and manage credit notes')], 'verbose_name': 'Invoice Detail', 'verbose_name_plural': 'Invoice Details'},
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_number_per_tenant',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_in_invoice_e6b546_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_in_store_i_7535e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_in_status_041490_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ugx_subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ugx_tax_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ugx_total_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Order Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoice_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_detail', to='sales.sale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_details', to='stores.store', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.TextField(blank=True, null=True, verbose_name='Terms and Conditions'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sale'], name='invoices_in_sale_id_77e694_idx'),
        ),
    ]
