# Generated by Django 5.0.6 on 2025-12-12 11:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Installment Number')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Payment Schedule',
                'verbose_name_plural': 'Payment Schedules',
                'ordering': ['installment_number'],
                'unique_together': {('invoice', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='invoices.invoicepayment')),
                ('payment_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='invoices.paymentschedule')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('UPCOMING', 'Upcoming Payment'), ('DUE', 'Payment Due'), ('OVERDUE', 'Payment Overdue'), ('FINAL_NOTICE', 'Final Notice')], max_length=20)),
                ('reminder_method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('LETTER', 'Physical Letter')], default='EMAIL', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('next_reminder_date', models.DateField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='invoices.invoice')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_schedule', models.ForeignKey(blank=True, help_text='Specific installment being reminded about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='invoices.paymentschedule')),
            ],
            options={
                'verbose_name': 'Payment Reminder',
                'verbose_name_plural': 'Payment Reminders',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['invoice', 'sent_at'], name='invoices_pa_invoice_558df0_idx'), models.Index(fields=['reminder_type'], name='invoices_pa_reminde_5d1719_idx'), models.Index(fields=['next_reminder_date'], name='invoices_pa_next_re_9351ed_idx')],
            },
        ),
    ]
