# Generated by Django 5.0.6 on 2025-12-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_paymentschedule_paymentallocation_paymentreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='allocated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='allocation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
