# Generated by Django 5.0.6 on 2026-01-31 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoicepayment_allocated_date_and_more'),
        ('sales', '0012_sale_discount_sale_fiscalization_error_and_more'),
        ('stores', '0006_stockstore_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='export_cleared_at',
            field=models.DateTimeField(blank=True, help_text='When customs clearance was completed', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='export_delivery_terms',
            field=models.CharField(blank=True, help_text='Incoterms: FOB, CIF, CFR, etc.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='export_sad_number',
            field=models.CharField(blank=True, help_text='Customs SAD declaration number (20 digits)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='export_sad_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the SAD was submitted', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='export_status',
            field=models.CharField(blank=True, db_index=True, help_text='EFRIS export status: 101=Processing, 102=Cleared', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='export_total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total gross weight in KGM', max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['export_status'], name='invoices_in_export__17fb37_idx'),
        ),
    ]
