# Generated by Django 5.0.6 on 2026-04-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_fiscalizationaudit_sync_id_invoice_sync_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='efris_exempt',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this invoice was created during a pause window and will never be sent for fiscalization.', verbose_name='EFRIS Exempt'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='efris_exemption_reason',
            field=models.CharField(blank=True, default='', help_text='Describes why this invoice is exempt from fiscalization.', max_length=255, verbose_name='EFRIS Exemption Reason'),
        ),
    ]
