# Generated by Django 5.0.6 on 2026-03-15 09:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('maintenance', 'Maintenance'), ('billing', 'Billing'), ('promo', 'Promotion'), ('critical', 'Critical')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_dismissible', models.BooleanField(default=True)),
                ('action_text', models.CharField(blank=True, max_length=60)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangelogRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_tag', models.CharField(help_text='Semantic version, e.g. v2.4.0.', max_length=20, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, default="Here's what we've been building for you", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Changelog Release',
                'verbose_name_plural': 'Changelog Releases',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangelogSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('tag', models.CharField(choices=[('new', 'New Feature'), ('improved', 'Improved'), ('tip', 'Pro Tip'), ('fixed', 'Bug Fix'), ('removed', 'Removed')], default='new', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(help_text='Supports <strong>, <em>, <br> HTML tags.')),
                ('chips', models.JSONField(blank=True, default=list, help_text='List of {"icon": "bi-...", "label": "..."} objects.')),
                ('media_type', models.CharField(choices=[('none', 'No Media (text only)'), ('image', 'Image / Screenshot / GIF'), ('video', 'Self-hosted Video'), ('embed', 'Embed (YouTube / Loom iframe src)'), ('comparison', 'Before/After Comparison')], default='none', max_length=20)),
                ('media_url', models.CharField(blank=True, max_length=500)),
                ('media_alt', models.CharField(blank=True, max_length=200)),
                ('media_poster', models.CharField(blank=True, max_length=500)),
                ('before_image', models.CharField(blank=True, max_length=500)),
                ('after_image', models.CharField(blank=True, max_length=500)),
                ('highlight_selector', models.CharField(blank=True, max_length=200)),
                ('highlight_label', models.CharField(blank=True, max_length=100)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='changelog.changelogrelease')),
            ],
            options={
                'verbose_name': 'Changelog Slide',
                'verbose_name_plural': 'Changelog Slides',
                'ordering': ['release', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(db_index=True, help_text='PK of the tenant user. No FK — cross-schema reference.')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='changelog.announcement')),
            ],
            options={
                'verbose_name': 'Announcement Dismissal',
                'unique_together': {('user_id', 'announcement')},
            },
        ),
        migrations.CreateModel(
            name='ChangelogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(db_index=True, help_text='PK of the tenant user. No FK — cross-schema reference.')),
                ('last_slide', models.PositiveSmallIntegerField(default=0)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('opted_out', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='changelog.changelogrelease')),
            ],
            options={
                'verbose_name': 'Changelog View',
                'verbose_name_plural': 'Changelog Views',
                'unique_together': {('user_id', 'release')},
            },
        ),
    ]
