# Generated by Django 5.0.6 on 2026-03-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogrelease',
            name='is_minor_push',
            field=models.BooleanField(default=False, help_text='Set to True when you push a patch/minor update via admin. Causes the modal to re-show to users who already dismissed this release.'),
        ),
        migrations.AddField(
            model_name='changelogrelease',
            name='last_pushed_at',
            field=models.DateTimeField(blank=True, help_text='When this release was last pushed to all users.', null=True),
        ),
        migrations.AddField(
            model_name='changelogrelease',
            name='push_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times this release has been pushed to users.'),
        ),
        migrations.AddField(
            model_name='changelogrelease',
            name='pushed_by',
            field=models.CharField(blank=True, help_text='Username of admin who last triggered the push.', max_length=150),
        ),
        migrations.AddField(
            model_name='changelogrelease',
            name='release_type',
            field=models.CharField(choices=[('major', 'Major — new version'), ('minor', 'Minor — notable features'), ('patch', 'Patch — small improvements / fixes')], default='minor', help_text='Major/Minor: shows automatically to all users. Patch: only shows after you click "Push to all users" in admin.', max_length=10),
        ),
        migrations.AlterField(
            model_name='changelogrelease',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive releases are never shown.'),
        ),
        migrations.AlterField(
            model_name='changelogrelease',
            name='version_tag',
            field=models.CharField(help_text='Version tag, e.g. v2.4.0. For minor feature pushes that do not increment the version, use a descriptive tag like "v2.4.0-nav-update" or "v2.4.1".', max_length=20, unique=True),
        ),
    ]
