# Generated by Django 5.0.6 on 2026-03-17 22:15

import changelog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0002_changelogrelease_is_minor_push_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogslide',
            name='after_image_upload',
            field=models.ImageField(blank=True, help_text='Upload the "after" comparison image. Overrides the URL field.', null=True, upload_to=changelog.models.SlideUploadPath('after')),
        ),
        migrations.AddField(
            model_name='changelogslide',
            name='before_image_upload',
            field=models.ImageField(blank=True, help_text='Upload the "before" comparison image. Overrides the URL field.', null=True, upload_to=changelog.models.SlideUploadPath('before')),
        ),
        migrations.AddField(
            model_name='changelogslide',
            name='media_poster_upload',
            field=models.ImageField(blank=True, help_text='Upload a poster/thumbnail image. Overrides the URL field above.', null=True, upload_to=changelog.models.SlideUploadPath('poster')),
        ),
        migrations.AddField(
            model_name='changelogslide',
            name='media_upload',
            field=models.FileField(blank=True, help_text='Upload an image, GIF, or MP4. Overrides the URL field above.', null=True, upload_to=changelog.models.SlideUploadPath('media')),
        ),
        migrations.AlterField(
            model_name='changelogslide',
            name='after_image',
            field=models.CharField(blank=True, help_text='After image URL for comparison slider. Or upload below.', max_length=500),
        ),
        migrations.AlterField(
            model_name='changelogslide',
            name='before_image',
            field=models.CharField(blank=True, help_text='Before image URL for comparison slider. Or upload below.', max_length=500),
        ),
        migrations.AlterField(
            model_name='changelogslide',
            name='media_poster',
            field=models.CharField(blank=True, help_text='Poster image URL shown before a video plays. Or upload below.', max_length=500),
        ),
        migrations.AlterField(
            model_name='changelogslide',
            name='media_url',
            field=models.CharField(blank=True, help_text='Paste a URL, or use the Upload button below.', max_length=500),
        ),
    ]
