# Generated by Django 5.0.6 on 2026-03-15 09:31

import django.db.models.deletion
import suggestions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('type', models.CharField(choices=[('bug', 'Bug / Technical Issue'), ('feature', 'Feature Request'), ('billing', 'Billing / Payment Complaint'), ('complaint', 'User / Staff Complaint'), ('data', 'Data Error / Incorrect Record')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting on User'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('affected_url', models.CharField(blank=True, help_text='Auto-captured page URL', max_length=500)),
                ('affected_record', models.CharField(blank=True, help_text='e.g. Invoice #1042', max_length=200)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=suggestions.models.report_attachment_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('internal_note', models.TextField(blank=True, help_text='Private note — not visible to the user.')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('reply', 'Reply'), ('status_change', 'Status Change'), ('note', 'Internal Note')], default='reply', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('is_internal', models.BooleanField(default=False, help_text='If True, only admins see this update.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='suggestions.suggestion')),
            ],
            options={
                'verbose_name': 'Report Update',
                'ordering': ['created_at'],
            },
        ),
    ]
