# Generated by Django 5.0.6 on 2026-03-15 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 — Very poor'), (2, '2 — Poor'), (3, '3 — Okay'), (4, '4 — Good'), (5, '5 — Excellent')], help_text='1–5 star satisfaction rating.')),
                ('resolved_ok', models.BooleanField(help_text="Did this ticket resolve the user's issue?")),
                ('comment', models.TextField(blank=True, help_text='Optional free-text comment from the user.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='suggestions.suggestion')),
            ],
            options={
                'verbose_name': 'Report Feedback',
                'verbose_name_plural': 'Report Feedback',
            },
        ),
    ]
