# Generated by Django 5.0.6 on 2026-02-25 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('direction', models.CharField(choices=[('pull', 'Pull'), ('push', 'Push')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_in', models.IntegerField(default=0)),
                ('records_out', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['schema_name', 'started_at'], name='sync_syncse_schema__03ef33_idx'), models.Index(fields=['user', 'started_at'], name='sync_syncse_user_id_270bfe_idx')],
            },
        ),
    ]
