# Generated by Django 5.0.6 on 2025-11-17 04:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import expenses.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('gl_account', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Budget')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Requires Approval')),
                ('approval_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Expenses below this amount are auto-approved', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Auto-Approve Below Amount')),
                ('color_code', models.CharField(default='#6c757d', max_length=7, verbose_name='Color Code')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome or similar icon class', max_length=50, verbose_name='Icon Class')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Expense Number')),
                ('reference_number', models.CharField(blank=True, help_text='Receipt or invoice number', max_length=100, verbose_name='Reference Number')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Expense Title')),
                ('description', models.TextField(help_text='Detailed description of the expense', verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('currency', models.CharField(default='UGX', max_length=3, verbose_name='Currency')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax Amount')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax Rate (%)')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, validators=[expenses.validators.validate_expense_date], verbose_name='Expense Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Payment Due Date')),
                ('vendor_name', models.CharField(blank=True, max_length=200, verbose_name='Vendor/Supplier Name')),
                ('vendor_phone', models.CharField(blank=True, max_length=20, verbose_name='Vendor Phone')),
                ('vendor_email', models.EmailField(blank=True, max_length=254, verbose_name='Vendor Email')),
                ('vendor_tin', models.CharField(blank=True, max_length=20, verbose_name='Vendor TIN')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('COMPANY_CARD', 'Company Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20, verbose_name='Payment Method')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID or reference', max_length=100, verbose_name='Payment Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes not visible to expense creator', verbose_name='Admin Notes')),
                ('is_reimbursable', models.BooleanField(default=False, help_text='Should this be reimbursed to the user?', verbose_name='Reimbursable')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Recurring Expense')),
                ('is_billable', models.BooleanField(default=False, help_text='Can this be billed to a customer?', verbose_name='Billable to Customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Paid By')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='stores.store', verbose_name='Store/Branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
                'permissions': [('approve_expense', 'Can approve expenses'), ('reject_expense', 'Can reject expenses'), ('pay_expense', 'Can mark expenses as paid'), ('view_all_expenses', 'Can view all expenses')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='expenses/attachments/%Y/%m/', validators=[expenses.validators.validate_file_size, expenses.validators.validate_file_type], verbose_name='File')),
                ('filename', models.CharField(default='', max_length=255, verbose_name='Filename')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='File Type')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='expenses.expense', verbose_name='Expense')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Expense Attachment',
                'verbose_name_plural': 'Expense Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('is_internal', models.BooleanField(default=False, help_text='Only visible to approvers and admins', verbose_name='Internal Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='expenses.expense', verbose_name='Expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Expense Comment',
                'verbose_name_plural': 'Expense Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_number'], name='expenses_ex_expense_2fef2f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_by', '-expense_date'], name='expenses_ex_created_ce5c39_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', '-expense_date'], name='expenses_ex_status_e5d781_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['store', '-expense_date'], name='expenses_ex_store_i_5f5fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', '-expense_date'], name='expenses_ex_categor_6321f1_idx'),
        ),
    ]
