# Generated by Django 5.2.4 on 2025-11-09 06:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('is_internal', models.BooleanField(default=False, help_text='Only visible to approvers and admins', verbose_name='Internal Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Expense Comment',
                'verbose_name_plural': 'Expense Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='store',
        ),
        migrations.RemoveField(
            model_name='employeereimbursement',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='employeereimbursement',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeereimbursement',
            name='store',
        ),
        migrations.RemoveField(
            model_name='reimbursementitem',
            name='reimbursement',
        ),
        migrations.AlterUniqueTogether(
            name='expenseapproval',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='expenseapproval',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='expenseapproval',
            name='expense',
        ),
        migrations.AlterUniqueTogether(
            name='expenseapprovalflow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='expenseapprovalflow',
            name='approver_role',
        ),
        migrations.RemoveField(
            model_name='expenseapprovalflow',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expenseapprovalflow',
            name='store',
        ),
        migrations.RemoveField(
            model_name='expenseauditlog',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='expenseauditlog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='expenseauditlog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='expensesplit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='expensesplit',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='expensesplit',
            name='store',
        ),
        migrations.RemoveField(
            model_name='pettycash',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='pettycash',
            name='store',
        ),
        migrations.RemoveField(
            model_name='pettycashtransaction',
            name='petty_cash',
        ),
        migrations.RemoveField(
            model_name='pettycashtransaction',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='pettycashtransaction',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='store',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='recurring_schedule',
        ),
        migrations.RemoveField(
            model_name='reimbursementitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor',
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'permissions': [('approve_expense', 'Can approve expenses'), ('reject_expense', 'Can reject expenses'), ('pay_expense', 'Can mark expenses as paid'), ('view_all_expenses', 'Can view all expenses')], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_store_i_fa0907_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_categor_1f8714_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_vendor__59ca5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_status_33d883_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_created_2ebd44_idx',
        ),
        migrations.RemoveIndex(
            model_name='expensecategory',
            name='expenses_ex_code_87d722_idx',
        ),
        migrations.RemoveIndex(
            model_name='expensecategory',
            name='expenses_ex_categor_43a708_idx',
        ),
        migrations.RemoveIndex(
            model_name='expensecategory',
            name='expenses_ex_parent__3f2666_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='can_claim_input_tax',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='efris_invoice_number',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='efris_verification_code',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_type',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_efris_compliant',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_split',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='requires_approval',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='expenseattachment',
            name='attachment_type',
        ),
        migrations.RemoveField(
            model_name='expenseattachment',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='expenseattachment',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='approval_limit',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='budget_allocation',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='default_tax_rate',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='is_taxable',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='expense',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes not visible to expense creator', verbose_name='Admin Notes'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_billable',
            field=models.BooleanField(default=False, help_text='Can this be billed to a customer?', verbose_name='Billable to Customer'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_reimbursable',
            field=models.BooleanField(default=False, help_text='Should this be reimbursed to the user?', verbose_name='Reimbursable'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid At'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Receipt or invoice number', max_length=100, verbose_name='Reference Number'),
        ),
        migrations.AddField(
            model_name='expense',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected At'),
        ),
        migrations.AddField(
            model_name='expense',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted At'),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Expense Title'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Vendor Email'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vendor/Supplier Name'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vendor Phone'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_tin',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vendor TIN'),
        ),
        migrations.AddField(
            model_name='expenseattachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='File Type'),
        ),
        migrations.AddField(
            model_name='expenseattachment',
            name='filename',
            field=models.CharField(default='', max_length=255, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expenses below this amount are auto-approved', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Auto-Approve Below Amount'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='gl_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Budget'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(help_text='Detailed description of the expense', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Due Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('COMPANY_CARD', 'Company Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Transaction ID or reference', max_length=100, verbose_name='Payment Reference'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='stores.store', verbose_name='Store/Branch'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax Rate (%)'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='File Size (bytes)'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Category Code'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='color_code',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='Color Code'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome or similar icon class', max_length=50, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='requires_approval',
            field=models.BooleanField(default=True, verbose_name='Requires Approval'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_by', '-expense_date'], name='expenses_ex_created_ce5c39_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', '-expense_date'], name='expenses_ex_status_e5d781_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['store', '-expense_date'], name='expenses_ex_store_i_5f5fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', '-expense_date'], name='expenses_ex_categor_6321f1_idx'),
        ),
        migrations.AddField(
            model_name='expensecomment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='expenses.expense', verbose_name='Expense'),
        ),
        migrations.AddField(
            model_name='expensecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='EmployeeReimbursement',
        ),
        migrations.DeleteModel(
            name='ExpenseApproval',
        ),
        migrations.DeleteModel(
            name='ExpenseApprovalFlow',
        ),
        migrations.DeleteModel(
            name='ExpenseAuditLog',
        ),
        migrations.DeleteModel(
            name='ExpenseSplit',
        ),
        migrations.DeleteModel(
            name='PettyCash',
        ),
        migrations.DeleteModel(
            name='PettyCashTransaction',
        ),
        migrations.DeleteModel(
            name='RecurringExpense',
        ),
        migrations.DeleteModel(
            name='ReimbursementItem',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
