# Generated by Django 5.0.6 on 2025-12-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_categor_219ae6_idx',
            old_name='expenses_ex_categor_6321f1_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('STAFF_WELFARE', 'Staff Welfare'), ('RENT_EXPENSE', 'Rent Expense'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('UTILITIES', 'Utilities'), ('BANK_CHARGES', 'Bank Charges'), ('MORE', 'More')], max_length=20, verbose_name='Category'),
        ),
    ]
