# Generated by Django 5.0.6 on 2025-12-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_expenses_ex_categor_6321f1_idx_expenses_ex_categor_219ae6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='tax_rate',
        ),
    ]
