# Generated by Django 5.2.4 on 2025-11-09 15:22

import django.utils.timezone
import expenses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensecomment_remove_budget_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[expenses.validators.validate_expense_date], verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='file',
            field=models.FileField(upload_to='expenses/attachments/%Y/%m/', validators=[expenses.validators.validate_file_size, expenses.validators.validate_file_type], verbose_name='File'),
        ),
    ]
