# Generated by Django 5.0.6 on 2026-01-08 11:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_tax_amount_remove_expense_tax_rate'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', '6 Months'), ('yearly', 'Yearly')], max_length=20)),
                ('alert_threshold', models.IntegerField(default=80, help_text='Alert when spending reaches this percentage')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='expenseattachment',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='expenseattachment',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.RemoveField(
            model_name='expensecomment',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='expensecomment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_expense_2fef2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_created_ce5c39_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_status_e5d781_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_store_i_5f5fc6_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_categor_219ae6_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_number',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_billable',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_reimbursable',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='store',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor_email',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor_name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor_phone',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor_tin',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-date'], name='expenses_ex_date_2850f8_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', '-date'], name='expenses_ex_user_id_4af51e_idx'),
        ),
        migrations.AddField(
            model_name='budget',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Leave empty for overall budget', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExpenseAttachment',
        ),
        migrations.DeleteModel(
            name='ExpenseComment',
        ),
    ]
