# Generated by Django 5.0.6 on 2026-01-09 14:27

import django.core.validators
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_budget_remove_expenseattachment_expense_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', '💵 Cash'), ('CREDIT_CARD', '💳 Credit Card'), ('DEBIT_CARD', '💳 Debit Card'), ('BANK_TRANSFER', '🏦 Bank Transfer'), ('DIGITAL_WALLET', '📱 Digital Wallet'), ('OTHER', '📝 Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='alert_threshold',
            field=models.IntegerField(default=80, help_text='Alert percentage', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('daily', '📅 Daily'), ('weekly', '📅 Weekly'), ('fortnightly', '📅 Fortnightly'), ('monthly', '📅 Monthly'), ('quarterly', '📅 Quarterly'), ('semi_annual', '📅 6 Months'), ('yearly', '📅 Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Filter by specific tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
