# Generated by Django 5.0.6 on 2026-02-20 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_transaction_category_remove_budget_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='sync_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='sync_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
