# Generated by Django 5.0.6 on 2026-02-20 10:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_budget_sync_id_expense_sync_id'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_float', models.DecimalField(decimal_places=2, help_text='Total float allocated', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('low_balance_threshold', models.DecimalField(decimal_places=2, default=Decimal('200000'), help_text='Alert when balance falls below this value', max_digits=12)),
                ('last_topped_up', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Petty Cash Fund',
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.CharField(blank=True, choices=[('admin', '🏢 Office & Admin'), ('purchase', '🛒 Purchases'), ('expense', '📊 Running Costs'), ('salary', '👥 Staff Pay'), ('utility', '💡 Bills & Utilities'), ('maintenance', '🔧 Repairs & Maintenance'), ('tax', '🧾 Tax & Statutory'), ('petty_cash', '💰 Petty Cash'), ('loan', '🏦 Loan Repayment'), ('other', '📝 Other')], help_text='Scope budget to a specific category', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('admin', '🏢 Office & Admin'), ('purchase', '🛒 Purchases'), ('expense', '📊 Running Costs'), ('salary', '👥 Staff Pay'), ('utility', '💡 Bills & Utilities'), ('maintenance', '🔧 Repairs & Maintenance'), ('tax', '🧾 Tax & Statutory'), ('petty_cash', '💰 Petty Cash'), ('loan', '🏦 Loan Repayment'), ('other', '📝 Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('paid', '✅ Paid'), ('waiting', '⏳ Waiting for Approval'), ('cancelled', '❌ Cancelled')], db_index=True, default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, help_text='Payee / vendor / person paid', max_length=200),
        ),
        migrations.AlterField(
            model_name='budget',
            name='alert_threshold',
            field=models.IntegerField(default=80, help_text='Alert when spending reaches this percentage', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', '💵 Cash'), ('BANK_TRANSFER', '🏦 Bank Transfer'), ('MTN_MOMO', '📱 MTN Mobile Money'), ('AIRTEL_MONEY', '📲 Airtel Money'), ('CREDIT_CARD', '💳 Credit Card'), ('DEBIT_CARD', '💳 Debit Card'), ('CHEQUE', '📝 Cheque'), ('DIGITAL_WALLET', '📱 Digital Wallet'), ('OTHER', '📝 Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'status'], name='expenses_ex_user_id_8369a1_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category'], name='expenses_ex_user_id_207090_idx'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_funds', to=settings.AUTH_USER_MODEL),
        ),
    ]
