# Generated by Django 5.0.6 on 2026-02-25 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_pettycash_budget_category_expense_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettycash',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_user_id_8369a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_user_id_207090_idx',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='budget',
            name='alert_threshold',
            field=models.IntegerField(default=80, help_text='Alert percentage', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', '💵 Cash'), ('CREDIT_CARD', '💳 Credit Card'), ('DEBIT_CARD', '💳 Debit Card'), ('BANK_TRANSFER', '🏦 Bank Transfer'), ('DIGITAL_WALLET', '📱 Digital Wallet'), ('OTHER', '📝 Other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PettyCash',
        ),
    ]
