# Generated by Django 5.0.6 on 2026-03-04 09:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_remove_pettycash_user_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', '📤 Submitted for Approval'), ('under_review', '🔍 Marked Under Review'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected'), ('resubmit', '🔄 Returned for Resubmission'), ('cancelled', '🚫 Cancelled'), ('comment', '💬 Comment Added')], max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Optional note / rejection reason')),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('approve_expense', 'Can approve expenses')]},
        ),
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', '🇺🇸 US Dollar'), ('EUR', '🇪🇺 Euro'), ('GBP', '🇬🇧 British Pound'), ('UGX', '🇺🇬 Ugandan Shilling'), ('KES', '🇰🇪 Kenyan Shilling'), ('TZS', '🇹🇿 Tanzanian Shilling'), ('NGN', '🇳🇬 Nigerian Naira'), ('ZAR', '🇿🇦 South African Rand'), ('GHS', '🇬🇭 Ghanaian Cedi'), ('JPY', '🇯🇵 Japanese Yen'), ('CAD', '🇨🇦 Canadian Dollar'), ('AUD', '🇦🇺 Australian Dollar'), ('INR', '🇮🇳 Indian Rupee'), ('CNY', '🇨🇳 Chinese Yuan'), ('CHF', '🇨🇭 Swiss Franc')], help_text='Restrict to a single currency (leave blank for all)', max_length=3),
        ),
        migrations.AddField(
            model_name='expense',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount converted to base currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', '🇺🇸 US Dollar'), ('EUR', '🇪🇺 Euro'), ('GBP', '🇬🇧 British Pound'), ('UGX', '🇺🇬 Ugandan Shilling'), ('KES', '🇰🇪 Kenyan Shilling'), ('TZS', '🇹🇿 Tanzanian Shilling'), ('NGN', '🇳🇬 Nigerian Naira'), ('ZAR', '🇿🇦 South African Rand'), ('GHS', '🇬🇭 Ghanaian Cedi'), ('JPY', '🇯🇵 Japanese Yen'), ('CAD', '🇨🇦 Canadian Dollar'), ('AUD', '🇦🇺 Australian Dollar'), ('INR', '🇮🇳 Indian Rupee'), ('CNY', '🇨🇳 Chinese Yuan'), ('CHF', '🇨🇭 Swiss Franc')], db_index=True, default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Rate used to convert this expense to your base currency', max_digits=18),
        ),
        migrations.AddField(
            model_name='expense',
            name='next_recurrence_date',
            field=models.DateField(blank=True, help_text='Date when the next copy should be auto-created', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount detected by OCR', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_raw',
            field=models.TextField(blank=True, help_text='Raw OCR text extracted from receipt'),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_vendor',
            field=models.CharField(blank=True, help_text='Vendor name detected by OCR', max_length=200),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence_interval',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='Only used when is_recurring is True', max_length=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', '📝 Draft'), ('submitted', '📤 Submitted'), ('under_review', '🔍 Under Review'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected'), ('resubmit', '🔄 Needs Resubmission')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, help_text='Merchant or vendor name', max_length=200),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'status'], name='expenses_ex_user_id_8369a1_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['currency'], name='expenses_ex_currenc_f13b94_idx'),
        ),
        migrations.AddField(
            model_name='expenseapproval',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseapproval',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='expenses.expense'),
        ),
        migrations.AddIndex(
            model_name='expenseapproval',
            index=models.Index(fields=['expense', 'action'], name='expenses_ex_expense_c623f8_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseapproval',
            index=models.Index(fields=['actor'], name='expenses_ex_actor_i_435915_idx'),
        ),
    ]
