# Generated by Django 5.0.6 on 2026-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_expenseapproval_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.CharField(blank=True, choices=[('UGX', '🇺🇬 Ugandan Shilling'), ('KES', '🇰🇪 Kenyan Shilling'), ('TZS', '🇹🇿 Tanzanian Shilling'), ('USD', '🇺🇸 US Dollar'), ('EUR', '🇪🇺 Euro'), ('GBP', '🇬🇧 British Pound'), ('NGN', '🇳🇬 Nigerian Naira'), ('ZAR', '🇿🇦 South African Rand'), ('GHS', '🇬🇭 Ghanaian Cedi'), ('JPY', '🇯🇵 Japanese Yen'), ('CAD', '🇨🇦 Canadian Dollar'), ('AUD', '🇦🇺 Australian Dollar'), ('INR', '🇮🇳 Indian Rupee'), ('CNY', '🇨🇳 Chinese Yuan'), ('CHF', '🇨🇭 Swiss Franc')], help_text='Restrict to a single currency (leave blank for all)', max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('UGX', '🇺🇬 Ugandan Shilling'), ('KES', '🇰🇪 Kenyan Shilling'), ('TZS', '🇹🇿 Tanzanian Shilling'), ('USD', '🇺🇸 US Dollar'), ('EUR', '🇪🇺 Euro'), ('GBP', '🇬🇧 British Pound'), ('NGN', '🇳🇬 Nigerian Naira'), ('ZAR', '🇿🇦 South African Rand'), ('GHS', '🇬🇭 Ghanaian Cedi'), ('JPY', '🇯🇵 Japanese Yen'), ('CAD', '🇨🇦 Canadian Dollar'), ('AUD', '🇦🇺 Australian Dollar'), ('INR', '🇮🇳 Indian Rupee'), ('CNY', '🇨🇳 Chinese Yuan'), ('CHF', '🇨🇭 Swiss Franc')], db_index=True, default='UGX', max_length=3),
        ),
    ]
