# Generated by Django 5.0.6 on 2026-01-31 09:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('release_date', models.DateTimeField()),
                ('release_notes', models.TextField()),
                ('lifecycle_status', models.CharField(choices=[('active', '🟢 Active - Fully supported'), ('stable', '🔵 Stable - Security updates only'), ('deprecated', '⚠️ Deprecated - Limited support'), ('eol', '🔴 End of Life - No support')], default='active', max_length=20)),
                ('active_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stable_date', models.DateTimeField(blank=True, null=True)),
                ('deprecated_date', models.DateTimeField(blank=True, null=True)),
                ('eol_date', models.DateTimeField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False, help_text='Mark this version as critical - forces immediate attention')),
                ('deprecation_warning', models.TextField(blank=True, help_text='Message shown to users on deprecated version')),
                ('eol_warning', models.TextField(blank=True, help_text='Message shown to users on EOL version')),
                ('requires_rollback', models.BooleanField(default=False, help_text='Force users to rollback from this version')),
                ('rollback_reason', models.TextField(blank=True, help_text='Why rollback is required')),
                ('rollback_priority', models.CharField(blank=True, choices=[('low', 'Low - User can delay'), ('medium', 'Medium - User should update soon'), ('critical', 'Critical - Forced immediate rollback')], default='low', max_length=20)),
                ('windows_file', models.FileField(blank=True, null=True, upload_to='downloads/windows/', validators=[django.core.validators.FileExtensionValidator(['exe'])])),
                ('linux_file', models.FileField(blank=True, null=True, upload_to='downloads/linux/')),
                ('mac_file', models.FileField(blank=True, null=True, upload_to='downloads/mac/', validators=[django.core.validators.FileExtensionValidator(['dmg', 'pkg'])])),
                ('file_size_mb', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_latest', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rollback_target', models.ForeignKey(blank=True, help_text='Version to rollback to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_from', to='primebooks.appversion')),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=200)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField()),
                ('os_name', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('python_version', models.CharField(blank=True, max_length=20)),
                ('logs', models.TextField(blank=True)),
                ('system_info', models.JSONField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primebooks.appversion')),
            ],
            options={
                'verbose_name': 'Error Report',
                'verbose_name_plural': 'Error Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notify_24h_before', models.BooleanField(default=True)),
                ('notify_1h_before', models.BooleanField(default=True)),
                ('notification_sent_24h', models.BooleanField(default=False)),
                ('notification_sent_1h', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primebooks.appversion')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_started', models.DateTimeField(blank=True, null=True)),
                ('download_completed', models.DateTimeField(blank=True, null=True)),
                ('download_failed', models.BooleanField(default=False)),
                ('download_error', models.TextField(blank=True)),
                ('installation_started', models.DateTimeField(blank=True, null=True)),
                ('installation_completed', models.DateTimeField(blank=True, null=True)),
                ('installation_failed', models.BooleanField(default=False)),
                ('installation_error', models.TextField(blank=True)),
                ('platform', models.CharField(max_length=20)),
                ('update_type', models.CharField(choices=[('manual', 'Manual Update'), ('automatic', 'Automatic Update'), ('rollback', 'Rollback'), ('version_select', 'User Selected Version')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primebooks.appversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
