# Generated by Django 5.0.6 on 2026-02-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primebooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('windows_url', models.URLField(blank=True)),
                ('mac_url', models.URLField(blank=True)),
                ('linux_url', models.URLField(blank=True)),
                ('file_size_mb', models.IntegerField(default=0)),
                ('release_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_critical', models.BooleanField(default=False, help_text='If true, users must update immediately')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
