# Generated by Django 5.0.6 on 2026-02-28 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primebooks', '0003_appversion_sync_id_appversions_sync_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('platform', models.CharField(blank=True, default='', max_length=200)),
                ('traceback', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=20)),
                ('triage_notes', models.TextField(blank=True, default='')),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Crash Report',
                'verbose_name_plural': 'Crash Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrimeBooksVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Semver string e.g. '1.2.0'", max_length=32, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one active version is served. Activating a new one deactivates all others.')),
                ('is_critical', models.BooleanField(default=False, help_text='Critical = mandatory update dialog, no Later button.')),
                ('min_version', models.CharField(blank=True, default='', help_text='Clients older than this are force-updated even if is_critical=False.', max_length=32)),
                ('changelog', models.TextField(blank=True, default='', help_text="Shown in update dialog. Use bullet points: '• Fix\\n• Fix'")),
                ('download_url', models.URLField(help_text='Direct HTTPS URL to the .exe installer.', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, help_text='Optional — shown as download size in the dialog.', null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes — NOT shown to users.')),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
