# Generated by Django 5.0.6 on 2026-03-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primebooks', '0004_crashreport_primebooksversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrashReport',
        ),
        migrations.DeleteModel(
            name='PrimeBooksVersion',
        ),
    ]
