# Generated by Django 5.2.4 on 2025-10-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_nash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nash',
        ),
    ]
