# Generated by Django 5.0.6 on 2025-11-17 04:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='Old URL path (e.g., /old-page/)', max_length=255, unique=True)),
                ('new_path', models.CharField(help_text='New URL path or full URL', max_length=255)),
                ('redirect_type', models.IntegerField(choices=[(301, '301 - Permanent'), (302, '302 - Temporary')], default=301)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
                'db_table': 'public_seo_redirects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='User-agent: *\nAllow: /\nSitemap: https://yourdomain.com/sitemap.xml', help_text='robots.txt content')),
                ('is_active', models.BooleanField(default=True, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Robots.txt',
                'verbose_name_plural': 'Robots.txt',
                'db_table': 'public_seo_robots',
            },
        ),
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('HOME', 'Homepage'), ('PRICING', 'Pricing Page'), ('FEATURES', 'Features Page'), ('ABOUT', 'About Page'), ('BLOG_HOME', 'Blog Homepage'), ('BLOG_POST', 'Blog Post'), ('CONTACT', 'Contact Page'), ('SIGNUP', 'Signup Page'), ('CUSTOM', 'Custom Page')], max_length=20, unique=True)),
                ('url_path', models.CharField(help_text='URL path (e.g., /pricing/, /features/)', max_length=255, unique=True)),
                ('title', models.CharField(help_text='Page title (60-70 characters optimal)', max_length=70)),
                ('meta_description', models.CharField(help_text='Meta description (150-160 characters optimal)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('robots_meta', models.CharField(default='index, follow', help_text="e.g., 'index, follow' or 'noindex, nofollow'", max_length=100)),
                ('og_title', models.CharField(blank=True, max_length=95)),
                ('og_description', models.CharField(blank=True, max_length=200)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630px recommended', null=True, upload_to='seo/og_images/')),
                ('og_type', models.CharField(default='website', help_text="e.g., 'website', 'article', 'product'", max_length=50)),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', max_length=50)),
                ('twitter_title', models.CharField(blank=True, max_length=70)),
                ('twitter_description', models.CharField(blank=True, max_length=200)),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='seo/twitter_images/')),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='Schema.org JSON-LD structured data')),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary keyword for this page', max_length=100)),
                ('secondary_keywords', models.TextField(blank=True, help_text='One keyword per line')),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SEO Page',
                'verbose_name_plural': 'SEO Pages',
                'db_table': 'public_seo_pages',
                'ordering': ['page_type'],
            },
        ),
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(max_length=255, unique=True)),
                ('priority', models.FloatField(choices=[(1.0, 'Highest'), (0.8, 'High'), (0.5, 'Medium'), (0.3, 'Low')], default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('change_frequency', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', max_length=20)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sitemap Entry',
                'verbose_name_plural': 'Sitemap Entries',
                'db_table': 'public_seo_sitemap',
                'ordering': ['-priority', 'url_path'],
            },
        ),
        migrations.CreateModel(
            name='KeywordTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('target_url', models.URLField()),
                ('current_position', models.PositiveIntegerField(blank=True, null=True)),
                ('search_volume', models.PositiveIntegerField(blank=True, null=True)),
                ('competition', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('tracked_since', models.DateField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Keyword Tracking',
                'verbose_name_plural': 'Keyword Tracking',
                'db_table': 'public_seo_keyword_tracking',
                'unique_together': {('keyword', 'target_url')},
            },
        ),
        migrations.CreateModel(
            name='KeywordRankingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('keyword_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='public_seo.keywordtracking')),
            ],
            options={
                'verbose_name': 'Ranking History',
                'verbose_name_plural': 'Ranking History',
                'db_table': 'public_seo_ranking_history',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=20)),
                ('issue_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='public_seo.seopage')),
            ],
            options={
                'verbose_name': 'SEO Audit',
                'verbose_name_plural': 'SEO Audits',
                'db_table': 'public_seo_audits',
                'ordering': ['-detected_at'],
            },
        ),
    ]
