# Generated by Django 5.0.6 on 2026-03-10 19:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company_name', models.CharField(blank=True, help_text="Partner's own company/agency name", max_length=200)),
                ('referral_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before partner can share links')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission percentage e.g. 10.00 = 10%', max_digits=5)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ReferralSignup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_email', models.EmailField(max_length=254)),
                ('tenant_schema_name', models.CharField(blank=True, help_text='The schema_name of the created tenant, set after tenant creation', max_length=100)),
                ('subdomain', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission_paid', models.BooleanField(default=False)),
                ('referral_code_used', models.CharField(blank=True, max_length=20)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='referral.partner')),
            ],
            options={
                'verbose_name': 'Referral Signup',
                'verbose_name_plural': 'Referral Signups',
                'ordering': ['-registered_at'],
            },
        ),
    ]
