# Generated by Django 5.0.6 on 2026-03-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='ad_promo_text',
            field=models.CharField(blank=True, help_text="Short promotional text for the share card (e.g. 'Free 30-day trial + priority onboarding')", max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='ad_tagline',
            field=models.CharField(blank=True, help_text="Custom tagline shown on the partner's shareable QR card (e.g. 'Get your business on PrimeBooks today!')", max_length=120),
        ),
        migrations.AddField(
            model_name='referralsignup',
            name='commission_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referralsignup',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='referralsignup',
            name='utm_source',
            field=models.CharField(blank=True, help_text='e.g. whatsapp, instagram, qrcode', max_length=100),
        ),
        migrations.AlterField(
            model_name='referralsignup',
            name='tenant_schema_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
