# Generated by Django 5.0.6 on 2025-11-17 21:59

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=20, verbose_name='Export Type')),
                ('resource_type', models.CharField(help_text='What type of data was exported', max_length=100, verbose_name='Resource Type')),
                ('filters_applied', models.JSONField(default=dict, verbose_name='Filters Applied')),
                ('record_count', models.PositiveIntegerField(default=0, verbose_name='Record Count')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Data Export Log',
                'verbose_name_plural': 'Data Export Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], max_length=20, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Browser')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Device Type')),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=200, verbose_name='Location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='Failure Reason')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session Key')),
                ('logout_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Logout Timestamp')),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('color_code', models.CharField(default='#6c757d', max_length=7)),
                ('max_users', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-priority', 'group__name'],
                'permissions': [('can_manage_system_roles', 'Can manage system roles'), ('can_view_role_analytics', 'Can view role analytics'), ('can_bulk_assign_roles', 'Can bulk assign roles to users')],
            },
        ),
        migrations.CreateModel(
            name='RoleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('permissions_changed', 'Permissions Changed'), ('activated', 'Activated'), ('deactivated', 'Deactivated'), ('assigned', 'Assigned to User'), ('removed', 'Removed from User')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changes', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Role History',
                'verbose_name_plural': 'Role Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_info', models.JSONField(default=dict)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='user_signatures/')),
                ('signature_data', models.TextField(blank=True, help_text='Digital signature data for EFRIS', null=True)),
                ('signature_hash', models.CharField(blank=True, max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Signature',
                'verbose_name_plural': 'User Signatures',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Middle Name')),
                ('is_saas_admin', models.BooleanField(default=False, help_text='Designates whether this user can access all companies', verbose_name='SaaS Administrator')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden users are not shown in user listings', verbose_name='Hidden User')),
                ('can_access_all_companies', models.BooleanField(default=False, help_text='Allows user to access any company in the system', verbose_name='Can Access All Companies')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[accounts.models.validate_phone_number], verbose_name='Phone Number')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('company_admin', models.BooleanField(default=False, help_text='Tenant owner with full control', verbose_name='Company Admin')),
                ('is_device_operator', models.BooleanField(default=False, verbose_name='Device Operator')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Phone Verified')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(auto_now_add=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('backup_codes', models.JSONField(blank=True, default=list)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('timezone', models.CharField(default='Africa/Kampala', max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('lg', 'Luganda')], default='en', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional user metadata')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'permissions': [('can_manage_users', 'Can manage users'), ('can_view_reports', 'Can view reports'), ('can_manage_settings', 'Can manage settings'), ('can_export_data', 'Can export data'), ('can_access_saas_admin', 'Can access SaaS admin features'), ('can_manage_all_companies', 'Can manage all companies')],
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this token', max_length=100)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('permissions', models.JSONField(default=list, help_text='List of permissions for this token')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiration date', null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('email_verified', 'Email Verified'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('company_created', 'Company Created'), ('company_updated', 'Company Updated'), ('company_deleted', 'Company Deleted'), ('company_suspended', 'Company Suspended'), ('company_activated', 'Company Activated'), ('store_created', 'Store Created'), ('store_updated', 'Store Updated'), ('store_deleted', 'Store Deleted'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('stock_added', 'Stock Added'), ('stock_removed', 'Stock Removed'), ('stock_adjusted', 'Stock Adjusted'), ('sale_created', 'Sale Created'), ('sale_completed', 'Sale Completed'), ('sale_voided', 'Sale Voided'), ('sale_refunded', 'Sale Refunded'), ('invoice_created', 'Invoice Created'), ('invoice_sent', 'Invoice Sent'), ('invoice_paid', 'Invoice Paid'), ('invoice_cancelled', 'Invoice Cancelled'), ('efris_fiscalized', 'EFRIS Fiscalized'), ('efris_sync', 'EFRIS Sync'), ('efris_failed', 'EFRIS Failed'), ('report_generated', 'Report Generated'), ('report_exported', 'Report Exported'), ('report_scheduled', 'Report Scheduled'), ('expense_created', 'Expense Created'), ('expense_approved', 'Expense Approved'), ('expense_rejected', 'Expense Rejected'), ('expense_paid', 'Expense Paid'), ('settings_updated', 'Settings Updated'), ('permission_changed', 'Permission Changed'), ('impersonation_started', 'Impersonation Started'), ('impersonation_ended', 'Impersonation Ended'), ('suspicious_activity', 'Suspicious Activity'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('system_backup', 'System Backup'), ('system_restore', 'System Restore'), ('maintenance_mode', 'Maintenance Mode'), ('other', 'Other Action')], db_index=True, max_length=50, verbose_name='Action Type')),
                ('action_description', models.TextField(help_text='Human-readable description of the action', verbose_name='Action Description')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='Severity Level')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resource ID')),
                ('resource_name', models.CharField(blank=True, max_length=255, verbose_name='Resource Name')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Before and after values for updates', verbose_name='Changes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Additional Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='Request Path')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Request Method')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful', verbose_name='Success')),
                ('error_message', models.TextField(blank=True, help_text='Error details if action failed', verbose_name='Error Message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='How long the action took in milliseconds', null=True, verbose_name='Duration (ms)')),
                ('is_system_action', models.BooleanField(default=False, help_text='Action performed by system, not user', verbose_name='System Action')),
                ('requires_review', models.BooleanField(default=False, help_text='Flag for actions that need admin review', verbose_name='Requires Review')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='company.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Resource Type')),
                ('impersonated_by', models.ForeignKey(blank=True, help_text='If action was performed during impersonation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_logs', to=settings.AUTH_USER_MODEL, verbose_name='Impersonated By')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logs', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'permissions': [('view_all_audit_logs', 'Can view all audit logs'), ('export_audit_logs', 'Can export audit logs'), ('review_audit_logs', 'Can review flagged audit logs')],
            },
        ),
    ]
