# Generated by Django 5.2.4 on 2025-11-09 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=20, verbose_name='Export Type')),
                ('resource_type', models.CharField(help_text='What type of data was exported', max_length=100, verbose_name='Resource Type')),
                ('filters_applied', models.JSONField(default=dict, verbose_name='Filters Applied')),
                ('record_count', models.PositiveIntegerField(default=0, verbose_name='Record Count')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Data Export Log',
                'verbose_name_plural': 'Data Export Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('email_verified', 'Email Verified'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('company_created', 'Company Created'), ('company_updated', 'Company Updated'), ('company_deleted', 'Company Deleted'), ('company_suspended', 'Company Suspended'), ('company_activated', 'Company Activated'), ('store_created', 'Store Created'), ('store_updated', 'Store Updated'), ('store_deleted', 'Store Deleted'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('stock_added', 'Stock Added'), ('stock_removed', 'Stock Removed'), ('stock_adjusted', 'Stock Adjusted'), ('sale_created', 'Sale Created'), ('sale_completed', 'Sale Completed'), ('sale_voided', 'Sale Voided'), ('sale_refunded', 'Sale Refunded'), ('invoice_created', 'Invoice Created'), ('invoice_sent', 'Invoice Sent'), ('invoice_paid', 'Invoice Paid'), ('invoice_cancelled', 'Invoice Cancelled'), ('efris_fiscalized', 'EFRIS Fiscalized'), ('efris_sync', 'EFRIS Sync'), ('efris_failed', 'EFRIS Failed'), ('report_generated', 'Report Generated'), ('report_exported', 'Report Exported'), ('report_scheduled', 'Report Scheduled'), ('expense_created', 'Expense Created'), ('expense_approved', 'Expense Approved'), ('expense_rejected', 'Expense Rejected'), ('expense_paid', 'Expense Paid'), ('settings_updated', 'Settings Updated'), ('permission_changed', 'Permission Changed'), ('impersonation_started', 'Impersonation Started'), ('impersonation_ended', 'Impersonation Ended'), ('suspicious_activity', 'Suspicious Activity'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('system_backup', 'System Backup'), ('system_restore', 'System Restore'), ('maintenance_mode', 'Maintenance Mode'), ('other', 'Other Action')], db_index=True, max_length=50, verbose_name='Action Type')),
                ('action_description', models.TextField(help_text='Human-readable description of the action', verbose_name='Action Description')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='Severity Level')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resource ID')),
                ('resource_name', models.CharField(blank=True, max_length=255, verbose_name='Resource Name')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Before and after values for updates', verbose_name='Changes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Additional Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='Request Path')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Request Method')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful', verbose_name='Success')),
                ('error_message', models.TextField(blank=True, help_text='Error details if action failed', verbose_name='Error Message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='How long the action took in milliseconds', null=True, verbose_name='Duration (ms)')),
                ('is_system_action', models.BooleanField(default=False, help_text='Action performed by system, not user', verbose_name='System Action')),
                ('requires_review', models.BooleanField(default=False, help_text='Flag for actions that need admin review', verbose_name='Requires Review')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='company.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Resource Type')),
                ('impersonated_by', models.ForeignKey(blank=True, help_text='If action was performed during impersonation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_logs', to=settings.AUTH_USER_MODEL, verbose_name='Impersonated By')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logs', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='stores.store', verbose_name='Store')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'permissions': [('view_all_audit_logs', 'Can view all audit logs'), ('export_audit_logs', 'Can export audit logs'), ('review_audit_logs', 'Can review flagged audit logs')],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_au_user_id_1110c4_idx'), models.Index(fields=['company', '-timestamp'], name='accounts_au_company_3afa51_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_au_action_918219_idx'), models.Index(fields=['content_type', 'object_id'], name='accounts_au_content_659137_idx'), models.Index(fields=['ip_address', '-timestamp'], name='accounts_au_ip_addr_3cb18d_idx'), models.Index(fields=['severity', '-timestamp'], name='accounts_au_severit_2992a7_idx'), models.Index(fields=['success', '-timestamp'], name='accounts_au_success_dbada2_idx'), models.Index(fields=['requires_review', 'reviewed'], name='accounts_au_require_635a10_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], max_length=20, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Browser')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Device Type')),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=200, verbose_name='Location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='Failure Reason')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session Key')),
                ('logout_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Logout Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login History',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_lo_user_id_b490c1_idx'), models.Index(fields=['status', '-timestamp'], name='accounts_lo_status_e4ffd7_idx'), models.Index(fields=['ip_address', '-timestamp'], name='accounts_lo_ip_addr_962504_idx')],
            },
        ),
    ]
