# Generated by Django 5.0.6 on 2025-11-11 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dataexportlog_auditlog_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primary_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_primary_role', to='accounts.role'),
        ),
    ]
