# Generated by Django 5.0.6 on 2026-03-06 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_sync_id_role_sync_id_rolehistory_sync_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apitoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'API Token', 'verbose_name_plural': 'API Tokens'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_activity'], 'verbose_name': 'User Session', 'verbose_name_plural': 'User Sessions'},
        ),
        migrations.RemoveField(
            model_name='apitoken',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='apitoken',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='apitoken',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='is_current',
        ),
        migrations.AddField(
            model_name='apitoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Used At'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='token_type',
            field=models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('admin', 'Admin')], default='read', max_length=20, verbose_name='Token Type'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='browser',
            field=models.CharField(blank=True, max_length=100, verbose_name='Browser'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Device Type'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='os',
            field=models.CharField(blank=True, max_length=100, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='last_used_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Used IP'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='name',
            field=models.CharField(help_text='A label to identify this token', max_length=100, verbose_name='Token Name'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Activity'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Session Key'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['token'], name='accounts_ap_token_86256d_idx'),
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['user', 'is_active'], name='accounts_ap_user_id_42f198_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_91ed82_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='accounts_us_session_511f42_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='accounts_us_last_ac_a630f7_idx'),
        ),
    ]
