# Generated by Django 5.0.6 on 2026-04-19 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_apitoken_options_alter_usersession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePOSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_reduction_policy', models.CharField(choices=[('FREE', 'No restriction — employee can change prices freely'), ('NOTIFY', 'Requires admin approval — sale line is held until approved'), ('LOCKED', 'Fully locked — price changes are blocked entirely')], default='FREE', help_text='Controls what happens when this employee reduces an item price at POS. FREE = allowed. NOTIFY = held for admin approval. LOCKED = blocked.', max_length=10, verbose_name='Price Reduction Policy')),
                ('max_reduction_pct', models.DecimalField(decimal_places=2, default=0, help_text='Maximum percentage the employee is allowed to reduce a price. 0 means no percentage cap (policy still applies).', max_digits=5, verbose_name='Max Reduction % (0 = unlimited)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_settings_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last updated by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_settings', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee POS Settings',
                'verbose_name_plural': 'Employee POS Settings',
            },
        ),
    ]
