from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.chart import BarChart, LineChart, PieChart, Reference
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo
from django.utils import timezone
from io import BytesIO
from typing import Dict, Any, List
import logging

logger = logging.getLogger(__name__)


class ExcelStyler:
    """Excel styling configuration"""

    # Fonts
    HEADER_FONT = Font(name='Calibri', size=14, bold=True, color='FFFFFF')
    TITLE_FONT = Font(name='Calibri', size=18, bold=True, color='1F4E78')
    SECTION_FONT = Font(name='Calibri', size=12, bold=True, color='1F4E78')
    NORMAL_FONT = Font(name='Calibri', size=11)

    # Fills
    HEADER_FILL = PatternFill(start_color='2563EB', end_color='2563EB', fill_type='solid')
    SUMMARY_FILL = PatternFill(start_color='DBEAFE', end_color='DBEAFE', fill_type='solid')
    SUCCESS_FILL = PatternFill(start_color='D1FAE5', end_color='D1FAE5', fill_type='solid')
    WARNING_FILL = PatternFill(start_color='FEF3C7', end_color='FEF3C7', fill_type='solid')
    DANGER_FILL = PatternFill(start_color='FEE2E2', end_color='FEE2E2', fill_type='solid')
    NEUTRAL_FILL = PatternFill(start_color='F3F4F6', end_color='F3F4F6', fill_type='solid')

    # Alignment
    CENTER_ALIGN = Alignment(horizontal='center', vertical='center')
    LEFT_ALIGN = Alignment(horizontal='left', vertical='center')
    RIGHT_ALIGN = Alignment(horizontal='right', vertical='center')

    # Borders
    THIN_BORDER = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )


class ExcelExportService:
    """Professional Excel export with multiple sheets and charts"""

    def __init__(self, report_data: Dict[str, Any], report_name: str,
                 company_info: Dict[str, Any]):
        self.report_data = report_data
        self.report_name = report_name
        self.company_info = company_info
        self.wb = Workbook()
        self.current_row = 1

    def generate_excel(self) -> BytesIO:
        """Generate Excel workbook with multiple sheets"""
        # Remove default sheet
        if 'Sheet' in self.wb.sheetnames:
            del self.wb['Sheet']

        # Create summary sheet
        self._create_summary_sheet()

        # Create data sheets based on report content
        if 'grouped_data' in self.report_data and self.report_data['grouped_data']:
            self._create_data_sheet('Detailed Data', self.report_data['grouped_data'])

        if 'products' in self.report_data and self.report_data['products']:
            self._create_product_sheet()

        if 'inventory' in self.report_data and self.report_data['inventory']:
            self._create_inventory_sheet()

        if 'tax_breakdown' in self.report_data and self.report_data['tax_breakdown']:
            self._create_tax_sheet()

        if 'cashier_performance' in self.report_data:
            self._create_cashier_sheet()

        # Save to buffer
        buffer = BytesIO()
        self.wb.save(buffer)
        buffer.seek(0)
        return buffer

    def _create_summary_sheet(self):
        """Create executive summary sheet with charts"""
        ws = self.wb.create_sheet('Summary', 0)
        row = 1

        # Company header
        ws.merge_cells(f'A{row}:F{row}')
        cell = ws[f'A{row}']
        cell.value = self.company_info.get('name', 'Company Name')
        cell.font = ExcelStyler.TITLE_FONT
        cell.alignment = ExcelStyler.CENTER_ALIGN
        row += 1

        # Report title
        ws.merge_cells(f'A{row}:F{row}')
        cell = ws[f'A{row}']
        cell.value = self.report_name
        cell.font = ExcelStyler.SECTION_FONT
        cell.alignment = ExcelStyler.CENTER_ALIGN
        row += 2

        # Report metadata
        metadata = self.report_data.get('metadata', {})
        ws[f'A{row}'] = 'Generated On:'
        ws[f'B{row}'] = metadata.get('generated_at', timezone.now().isoformat())
        ws[f'A{row}'].font = Font(bold=True)
        row += 1

        ws[f'A{row}'] = 'Generated By:'
        ws[f'B{row}'] = metadata.get('generated_by', '')
        ws[f'A{row}'].font = Font(bold=True)
        row += 2

        # Summary statistics
        if 'summary' in self.report_data:
            ws.merge_cells(f'A{row}:F{row}')
            cell = ws[f'A{row}']
            cell.value = 'Key Metrics'
            cell.font = ExcelStyler.SECTION_FONT
            cell.fill = ExcelStyler.SUMMARY_FILL
            row += 1

            summary = self.report_data['summary']

            # Create 2-column layout for metrics
            col = 1
            for key, value in summary.items():
                if col > 4:
                    row += 1
                    col = 1

                # Metric name
                cell = ws.cell(row=row, column=col)
                cell.value = key.replace('_', ' ').title()
                cell.font = Font(bold=True)
                cell.alignment = ExcelStyler.LEFT_ALIGN

                # Metric value
                cell = ws.cell(row=row, column=col + 1)
                if isinstance(value, float):
                    if 'amount' in key.lower() or 'sales' in key.lower():
                        cell.value = value
                        cell.number_format = '#,##0.00'
                    elif 'rate' in key.lower() or 'percentage' in key.lower():
                        cell.value = value / 100
                        cell.number_format = '0.00%'
                    else:
                        cell.value = value
                        cell.number_format = '#,##0.00'
                else:
                    cell.value = value
                    if isinstance(value, int):
                        cell.number_format = '#,##0'

                cell.font = Font(bold=True, size=12)
                cell.alignment = ExcelStyler.RIGHT_ALIGN

                # Color coding
                if 'rate' in key.lower() or 'percentage' in key.lower():
                    if isinstance(value, (int, float)):
                        if value >= 75:
                            cell.fill = ExcelStyler.SUCCESS_FILL
                        elif value >= 50:
                            cell.fill = ExcelStyler.WARNING_FILL
                        else:
                            cell.fill = ExcelStyler.DANGER_FILL

                col += 2

            row += 2

        # Add chart if payment methods data exists
        if 'payment_methods' in self.report_data:
            self._add_pie_chart(ws, self.report_data['payment_methods'],
                                'Payment Methods Distribution', row)
            row += 15

        # Adjust column widths
        ws.column_dimensions['A'].width = 25
        ws.column_dimensions['B'].width = 20
        ws.column_dimensions['C'].width = 25
        ws.column_dimensions['D'].width = 20
        ws.column_dimensions['E'].width = 25
        ws.column_dimensions['F'].width = 20

    def _create_data_sheet(self, sheet_name: str, data: List[Dict]):
        """Create sheet with detailed data table"""
        ws = self.wb.create_sheet(sheet_name)

        if not data:
            ws['A1'] = 'No data available'
            return

        # Get headers
        headers = list(data[0].keys())

        # Write headers
        for col_num, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col_num)
            cell.value = header.replace('_', ' ').title()
            cell.font = ExcelStyler.HEADER_FONT
            cell.fill = ExcelStyler.HEADER_FILL
            cell.alignment = ExcelStyler.CENTER_ALIGN
            cell.border = ExcelStyler.THIN_BORDER

        # Write data rows
        for row_num, row_data in enumerate(data, 2):
            for col_num, header in enumerate(headers, 1):
                cell = ws.cell(row=row_num, column=col_num)
                value = row_data.get(header)

                if value is None:
                    cell.value = ''
                elif isinstance(value, float):
                    cell.value = value
                    if 'amount' in header.lower() or 'price' in header.lower():
                        cell.number_format = '#,##0.00'
                    elif 'rate' in header.lower() or 'percentage' in header.lower():
                        cell.number_format = '0.00%'
                    else:
                        cell.number_format = '#,##0.00'
                elif isinstance(value, int):
                    cell.value = value
                    cell.number_format = '#,##0'
                else:
                    cell.value = str(value)

                cell.border = ExcelStyler.THIN_BORDER
                cell.alignment = ExcelStyler.CENTER_ALIGN

                # Alternate row colors
                if row_num % 2 == 0:
                    cell.fill = ExcelStyler.NEUTRAL_FILL

        # Auto-adjust column widths
        for col_num, header in enumerate(headers, 1):
            ws.column_dimensions[get_column_letter(col_num)].width = 18

        # Add table formatting
        tab = Table(displayName=sheet_name.replace(' ', ''),
                    ref=f"A1:{get_column_letter(len(headers))}{len(data) + 1}")
        style = TableStyleInfo(name="TableStyleMedium9", showFirstColumn=False,
                               showLastColumn=False, showRowStripes=True,
                               showColumnStripes=False)
        tab.tableStyleInfo = style
        ws.add_table(tab)

        # Add chart if numeric data exists
        if len(data) > 1 and len(data) < 50:  # Chart for reasonable data size
            self._add_data_chart(ws, headers, len(data))

    def _create_product_sheet(self):
        """Create product performance sheet"""
        ws = self.wb.create_sheet('Product Performance')
        products = self.report_data['products']

        # Headers
        headers = ['Product Name', 'SKU', 'Category', 'Quantity Sold',
                   'Revenue', 'Cost', 'Profit', 'Profit Margin %']

        for col_num, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col_num)
            cell.value = header
            cell.font = ExcelStyler.HEADER_FONT
            cell.fill = ExcelStyler.HEADER_FILL
            cell.alignment = ExcelStyler.CENTER_ALIGN
            cell.border = ExcelStyler.THIN_BORDER

        # Data rows
        for row_num, product in enumerate(products, 2):
            ws.cell(row=row_num, column=1).value = product.get('product__name', '')
            ws.cell(row=row_num, column=2).value = product.get('product__sku', '')
            ws.cell(row=row_num, column=3).value = product.get('product__category__name', '')

            qty_cell = ws.cell(row=row_num, column=4)
            qty_cell.value = product.get('total_quantity', 0)
            qty_cell.number_format = '#,##0'

            rev_cell = ws.cell(row=row_num, column=5)
            rev_cell.value = product.get('total_revenue', 0)
            rev_cell.number_format = '#,##0.00'

            cost_cell = ws.cell(row=row_num, column=6)
            cost_cell.value = product.get('total_cost', 0)
            cost_cell.number_format = '#,##0.00'

            profit_cell = ws.cell(row=row_num, column=7)
            profit_cell.value = product.get('total_profit', 0)
            profit_cell.number_format = '#,##0.00'

            margin_cell = ws.cell(row=row_num, column=8)
            margin_value = product.get('profit_margin', 0)
            margin_cell.value = margin_value / 100
            margin_cell.number_format = '0.00%'

            # Color code profit margin
            if margin_value >= 30:
                margin_cell.fill = ExcelStyler.SUCCESS_FILL
            elif margin_value >= 15:
                margin_cell.fill = ExcelStyler.WARNING_FILL
            else:
                margin_cell.fill = ExcelStyler.DANGER_FILL

            # Apply borders
            for col in range(1, 9):
                ws.cell(row=row_num, column=col).border = ExcelStyler.THIN_BORDER
                if row_num % 2 == 0:
                    ws.cell(row=row_num, column=col).fill = ExcelStyler.NEUTRAL_FILL

        # Column widths
        ws.column_dimensions['A'].width = 30
        ws.column_dimensions['B'].width = 15
        ws.column_dimensions['C'].width = 20
        for col in ['D', 'E', 'F', 'G', 'H']:
            ws.column_dimensions[col].width = 15

        # Add bar chart for top 10 products
        if len(products) > 0:
            chart = BarChart()
            chart.type = "col"
            chart.title = "Top Products by Revenue"
            chart.y_axis.title = 'Revenue (UGX)'
            chart.x_axis.title = 'Products'

            data = Reference(ws, min_col=5, min_row=1, max_row=min(11, len(products) + 1))
            cats = Reference(ws, min_col=1, min_row=2, max_row=min(11, len(products) + 1))
            chart.add_data(data, titles_from_data=True)
            chart.set_categories(cats)
            chart.height = 10
            chart.width = 20

            ws.add_chart(chart, f"J2")

    def _create_inventory_sheet(self):
        """Create inventory status sheet"""
        ws = self.wb.create_sheet('Inventory Status')
        inventory = self.report_data['inventory']

        # Headers
        headers = ['Product', 'SKU', 'Store', 'Quantity', 'Reorder Level',
                   'Status', 'Unit Cost', 'Stock Value']

        for col_num, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col_num)
            cell.value = header
            cell.font = ExcelStyler.HEADER_FONT
            cell.fill = ExcelStyler.HEADER_FILL
            cell.alignment = ExcelStyler.CENTER_ALIGN
            cell.border = ExcelStyler.THIN_BORDER

        # Data rows
        for row_num, item in enumerate(inventory, 2):
            ws.cell(row=row_num, column=1).value = item.get('product__name', '')
            ws.cell(row=row_num, column=2).value = item.get('product__sku', '')
            ws.cell(row=row_num, column=3).value = item.get('store__name', '')

            qty_cell = ws.cell(row=row_num, column=4)
            qty_cell.value = item.get('quantity', 0)
            qty_cell.number_format = '#,##0'

            reorder_cell = ws.cell(row=row_num, column=5)
            reorder_cell.value = item.get('low_stock_threshold', 0)
            reorder_cell.number_format = '#,##0'

            status_cell = ws.cell(row=row_num, column=6)
            status = item.get('status', 'in_stock')

            if status == 'out_of_stock':
                status_cell.value = 'OUT OF STOCK'
                status_cell.fill = ExcelStyler.DANGER_FILL
                status_cell.font = Font(bold=True, color='DC2626')
            elif status == 'low_stock':
                status_cell.value = 'LOW STOCK'
                status_cell.fill = ExcelStyler.WARNING_FILL
                status_cell.font = Font(bold=True, color='D97706')
            else:
                status_cell.value = 'IN STOCK'
                status_cell.fill = ExcelStyler.SUCCESS_FILL
                status_cell.font = Font(bold=True, color='059669')

            cost_cell = ws.cell(row=row_num, column=7)
            cost_cell.value = item.get('product__cost_price', 0)
            cost_cell.number_format = '#,##0.00'

            value_cell = ws.cell(row=row_num, column=8)
            value_cell.value = item.get('stock_value', 0)
            value_cell.number_format = '#,##0.00'

            # Apply borders
            for col in range(1, 9):
                ws.cell(row=row_num, column=col).border = ExcelStyler.THIN_BORDER

        # Column widths
        ws.column_dimensions['A'].width = 30
        ws.column_dimensions['B'].width = 15
        ws.column_dimensions['C'].width = 20
        for col in ['D', 'E', 'F', 'G', 'H']:
            ws.column_dimensions[col].width = 15

    def _create_tax_sheet(self):
        """Create tax breakdown sheet"""
        ws = self.wb.create_sheet('Tax Report')
        tax_data = self.report_data['tax_breakdown']

        # Headers
        headers = ['Tax Rate', 'Category', 'Total Sales', 'Tax Collected',
                   'Transactions', 'Items']

        for col_num, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col_num)
            cell.value = header
            cell.font = ExcelStyler.HEADER_FONT
            cell.fill = ExcelStyler.HEADER_FILL
            cell.alignment = ExcelStyler.CENTER_ALIGN
            cell.border = ExcelStyler.THIN_BORDER

        # Data rows
        total_sales = 0
        total_tax = 0

        for row_num, tax in enumerate(tax_data, 2):
            ws.cell(row=row_num, column=1).value = tax.get('tax_rate', '')
            ws.cell(row=row_num, column=2).value = tax.get('tax_rate_display', '')

            sales_cell = ws.cell(row=row_num, column=3)
            sales_value = tax.get('total_sales', 0)
            sales_cell.value = sales_value
            sales_cell.number_format = '#,##0.00'
            total_sales += sales_value

            tax_cell = ws.cell(row=row_num, column=4)
            tax_value = tax.get('total_tax', 0)
            tax_cell.value = tax_value
            tax_cell.number_format = '#,##0.00'
            tax_cell.fill = ExcelStyler.SUCCESS_FILL
            total_tax += tax_value

            trans_cell = ws.cell(row=row_num, column=5)
            trans_cell.value = tax.get('transaction_count', 0)
            trans_cell.number_format = '#,##0'

            items_cell = ws.cell(row=row_num, column=6)
            items_cell.value = tax.get('item_count', 0)
            items_cell.number_format = '#,##0'

            # Apply borders
            for col in range(1, 7):
                ws.cell(row=row_num, column=col).border = ExcelStyler.THIN_BORDER

        # Add totals row
        total_row = len(tax_data) + 2
        ws.cell(row=total_row, column=2).value = 'TOTAL'
        ws.cell(row=total_row, column=2).font = Font(bold=True)

        total_sales_cell = ws.cell(row=total_row, column=3)
        total_sales_cell.value = total_sales
        total_sales_cell.number_format = '#,##0.00'
        total_sales_cell.font = Font(bold=True)
        total_sales_cell.fill = ExcelStyler.SUMMARY_FILL

        total_tax_cell = ws.cell(row=total_row, column=4)
        total_tax_cell.value = total_tax
        total_tax_cell.number_format = '#,##0.00'
        total_tax_cell.font = Font(bold=True)
        total_tax_cell.fill = ExcelStyler.SUMMARY_FILL

        # Column widths
        for col in ['A', 'B', 'C', 'D', 'E', 'F']:
            ws.column_dimensions[col].width = 18

        # Add EFRIS compliance info if available
        if 'efris_stats' in self.report_data:
            efris = self.report_data['efris_stats']
            row = total_row + 3

            ws.merge_cells(f'A{row}:F{row}')
            cell = ws[f'A{row}']
            cell.value = 'EFRIS Compliance Status'
            cell.font = ExcelStyler.SECTION_FONT
            cell.fill = ExcelStyler.SUMMARY_FILL
            row += 1

            ws[f'A{row}'] = 'Compliance Rate:'
            compliance_cell = ws[f'B{row}']
            compliance_rate = efris.get('compliance_rate', 0)
            compliance_cell.value = compliance_rate / 100
            compliance_cell.number_format = '0.00%'
            compliance_cell.font = Font(bold=True, size=12)

            if compliance_rate >= 95:
                compliance_cell.fill = ExcelStyler.SUCCESS_FILL
            elif compliance_rate >= 85:
                compliance_cell.fill = ExcelStyler.WARNING_FILL
            else:
                compliance_cell.fill = ExcelStyler.DANGER_FILL
            row += 1

            ws[f'A{row}'] = 'Fiscalized:'
            ws[f'B{row}'] = efris.get('fiscalized', 0)
            ws[f'B{row}'].number_format = '#,##0'
            row += 1

            ws[f'A{row}'] = 'Pending:'
            ws[f'B{row}'] = efris.get('pending', 0)
            ws[f'B{row}'].number_format = '#,##0'

    def _create_cashier_sheet(self):
        """Create cashier performance sheet"""
        ws = self.wb.create_sheet('Cashier Performance')
        performance = self.report_data.get('cashier_performance', [])

        if not performance:
            ws['A1'] = 'No cashier data available'
            return

        # Headers
        headers = ['Cashier', 'Store', 'Total Sales', 'Transactions',
                   'Avg Transaction', 'Items Sold', 'Refunds']

        for col_num, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col_num)
            cell.value = header
            cell.font = ExcelStyler.HEADER_FONT
            cell.fill = ExcelStyler.HEADER_FILL
            cell.alignment = ExcelStyler.CENTER_ALIGN
            cell.border = ExcelStyler.THIN_BORDER

        # Data rows
        for row_num, cashier in enumerate(performance, 2):
            cashier_name = f"{cashier.get('created_by__first_name', '')} {cashier.get('created_by__last_name', '')}".strip()
            if not cashier_name:
                cashier_name = cashier.get('created_by__username', '')

            ws.cell(row=row_num, column=1).value = cashier_name
            ws.cell(row=row_num, column=2).value = cashier.get('store__name', '')

            sales_cell = ws.cell(row=row_num, column=3)
            sales_cell.value = cashier.get('total_sales', 0)
            sales_cell.number_format = '#,##0.00'

            trans_cell = ws.cell(row=row_num, column=4)
            trans_cell.value = cashier.get('transaction_count', 0)
            trans_cell.number_format = '#,##0'

            avg_cell = ws.cell(row=row_num, column=5)
            avg_cell.value = cashier.get('avg_transaction', 0)
            avg_cell.number_format = '#,##0.00'

            items_cell = ws.cell(row=row_num, column=6)
            items_cell.value = cashier.get('total_items', 0)
            items_cell.number_format = '#,##0'

            refund_cell = ws.cell(row=row_num, column=7)
            refund_cell.value = cashier.get('refund_count', 0)
            refund_cell.number_format = '#,##0'

            # Apply borders
            for col in range(1, 8):
                ws.cell(row=row_num, column=col).border = ExcelStyler.THIN_BORDER
                if row_num % 2 == 0:
                    ws.cell(row=row_num, column=col).fill = ExcelStyler.NEUTRAL_FILL

        # Column widths
        ws.column_dimensions['A'].width = 25
        ws.column_dimensions['B'].width = 20
        for col in ['C', 'D', 'E', 'F', 'G']:
            ws.column_dimensions[col].width = 15

    def _add_pie_chart(self, ws, data: List[Dict], title: str, start_row: int):
        """Add pie chart to worksheet"""
        if not data:
            return

        # Write data for chart
        ws.cell(row=start_row, column=1).value = 'Payment Method'
        ws.cell(row=start_row, column=2).value = 'Amount'

        for idx, item in enumerate(data, 1):
            ws.cell(row=start_row + idx, column=1).value = item.get('payment_method', '')
            ws.cell(row=start_row + idx, column=2).value = item.get('amount', 0)

        # Create chart
        chart = PieChart()
        chart.title = title
        chart.style = 10

        data_ref = Reference(ws, min_col=2, min_row=start_row,
                             max_row=start_row + len(data))
        labels = Reference(ws, min_col=1, min_row=start_row + 1,
                           max_row=start_row + len(data))

        chart.add_data(data_ref, titles_from_data=True)
        chart.set_categories(labels)
        chart.height = 10
        chart.width = 15

        ws.add_chart(chart, f"D{start_row}")

    def _add_data_chart(self, ws, headers: List[str], row_count: int):
        """Add chart for data visualization"""
        # Find numeric columns
        numeric_cols = []
        for col_num, header in enumerate(headers, 1):
            if any(keyword in header.lower() for keyword in
                   ['amount', 'quantity', 'count', 'total', 'revenue']):
                numeric_cols.append(col_num)

        if not numeric_cols or row_count < 2:
            return

        # Create line chart for first numeric column
        chart = LineChart()
        chart.title = f"{headers[numeric_cols[0] - 1]} Trend"
        chart.style = 10
        chart.height = 10
        chart.width = 20

        data = Reference(ws, min_col=numeric_cols[0], min_row=1,
                         max_row=min(row_count + 1, 52))  # Limit to 50 data points
        chart.add_data(data, titles_from_data=True)

        ws.add_chart(chart, f"{get_column_letter(len(headers) + 2)}2")