# Generated by Django 5.2.4 on 2025-10-24 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('nin', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIN')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Branch Code')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('efris_device_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tin', models.CharField(blank=True, max_length=20, null=True, verbose_name='TIN')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9]+$', 'Enter a valid phone number.')], verbose_name='Branch Phone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Branch Email')),
                ('address', models.TextField(blank=True, verbose_name='Physical Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_main_branch', models.BooleanField(default=False, verbose_name='Main Branch')),
                ('allows_sales', models.BooleanField(default=True, verbose_name='Allows Sales')),
                ('allows_inventory', models.BooleanField(default=True, verbose_name='Manages Inventory')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Branch Manager')),
                ('manager_phone', models.CharField(blank=True, max_length=20, verbose_name='Manager Phone')),
                ('operating_hours', models.JSONField(default=dict, help_text='Operating hours for each day of the week')),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company Branch',
                'verbose_name_plural': 'Company Branches',
                'ordering': ['-is_main_branch', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='branches_co_company_3152f7_idx'), models.Index(fields=['is_main_branch'], name='branches_co_is_main_00b517_idx')],
                'unique_together': {('company', 'code'), ('company', 'name')},
            },
        ),
    ]
