# Generated by Django 5.0.6 on 2026-01-03 12:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_crosscompanyprocurement_crosscompanyprocurementitem_and_more'),
        ('stores', '0006_stockstore_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crosscompanyprocurementitem',
            name='procurement',
        ),
        migrations.RemoveField(
            model_name='crosscompanyprocurementitem',
            name='our_product',
        ),
        migrations.RemoveField(
            model_name='stockstoreinventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockstoreinventory',
            name='stockstore',
        ),
        migrations.RemoveField(
            model_name='stockstoremovement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockstoremovement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockstoremovement',
            name='stockstore',
        ),
        migrations.RemoveField(
            model_name='stockstoremovement',
            name='transfer_request',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='stocktransferrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='stocktransferrequest',
            name='destination_stockstore',
        ),
        migrations.RemoveField(
            model_name='stocktransferrequest',
            name='destination_store',
        ),
        migrations.RemoveField(
            model_name='stocktransferrequest',
            name='dispatched_by',
        ),
        migrations.RemoveField(
            model_name='stocktransferrequest',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='stocktransferrequest',
            name='related_sale',
        ),
        migrations.RemoveField(
            model_name='stocktransferrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='stocktransferrequest',
            name='source_stockstore',
        ),
        migrations.RemoveField(
            model_name='stocktransferrequest',
            name='source_store',
        ),
        migrations.RemoveField(
            model_name='storetransferitem',
            name='destination_stock_movement',
        ),
        migrations.RemoveField(
            model_name='storetransferitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storetransferitem',
            name='source_stock_movement',
        ),
        migrations.RemoveField(
            model_name='storetransferitem',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='storetransferrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='storetransferrequest',
            name='dispatched_by',
        ),
        migrations.RemoveField(
            model_name='storetransferrequest',
            name='from_store',
        ),
        migrations.RemoveField(
            model_name='storetransferrequest',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='storetransferrequest',
            name='related_sale',
        ),
        migrations.RemoveField(
            model_name='storetransferrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='storetransferrequest',
            name='to_store',
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='Transfer Number')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantity')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_completions', to=settings.AUTH_USER_MODEL, verbose_name='Completed By')),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='stores.store', verbose_name='From Store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.product', verbose_name='Product')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='stores.store', verbose_name='To Store')),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CrossCompanyProcurement',
        ),
        migrations.DeleteModel(
            name='CrossCompanyProcurementItem',
        ),
        migrations.DeleteModel(
            name='StockStoreInventory',
        ),
        migrations.DeleteModel(
            name='StockStoreMovement',
        ),
        migrations.DeleteModel(
            name='StockTransferItem',
        ),
        migrations.DeleteModel(
            name='StockTransferRequest',
        ),
        migrations.DeleteModel(
            name='StoreTransferItem',
        ),
        migrations.DeleteModel(
            name='StoreTransferRequest',
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['transfer_number'], name='inventory_s_transfe_639a89_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['from_store', 'to_store'], name='inventory_s_from_st_d8f474_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status', 'created_at'], name='inventory_s_status_404290_idx'),
        ),
    ]
