# Generated by Django 5.0.6 on 2026-01-06 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_crosscompanyprocurementitem_procurement_and_more'),
        ('stores', '0006_stockstore_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='defer_efris_sync',
            field=models.BooleanField(default=False, verbose_name='Defer EFRIS Sync'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='efris_sync_attempted',
            field=models.BooleanField(default=False, verbose_name='EFRIS Sync Attempted'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='efris_sync_error',
            field=models.TextField(blank=True, verbose_name='EFRIS Sync Error'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='efris_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='EFRIS Synced At'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='synced_to_efris',
            field=models.BooleanField(default=False, verbose_name='Synced to EFRIS'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['store', 'product', '-created_at'], name='inventory_s_store_i_4bbccb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['synced_to_efris', 'efris_sync_attempted'], name='inventory_s_synced__1db109_idx'),
        ),
    ]
