# Generated by Django 5.0.6 on 2026-01-31 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockmovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customs_measure_unit',
            field=models.CharField(blank=True, help_text='Customs measure unit for exports (from T115 exportRateUnit) - e.g., NTT, KGM, LTR', max_length=10, null=True, verbose_name='Customs Measure Unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='customs_scaled_value',
            field=models.DecimalField(blank=True, decimal_places=8, default=1, help_text='Conversion factor between units (usually 1)', max_digits=12, null=True, verbose_name='Customs Scaled Value'),
        ),
        migrations.AddField(
            model_name='product',
            name='customs_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price in customs measure unit (for export documentation)', max_digits=12, null=True, verbose_name='Customs Unit Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_export_ready',
            field=models.BooleanField(db_index=True, default=False, help_text='Product has customs UoM configured and is ready for export invoices', verbose_name='Export Ready'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_scaled_value_customs',
            field=models.DecimalField(blank=True, decimal_places=8, default=1, help_text='Package scaling factor for customs unit (usually 1)', max_digits=12, null=True, verbose_name='Package Scaled Value (Customs)'),
        ),
        migrations.AddField(
            model_name='product',
            name='piece_measure_unit',
            field=models.CharField(blank=True, help_text='Piece measure unit (from T115 rateUnit) - e.g., 101=Per Stick, 102=Per Litre', max_length=10, null=True, verbose_name='Piece Measure Unit'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_export_ready'], name='inventory_p_is_expo_5183cf_idx'),
        ),
    ]
