# Generated by Django 5.0.6 on 2026-02-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_customs_measure_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='efris_customs_measure_unit',
            field=models.CharField(blank=True, help_text='From T115 exportRateUnit (e.g., KGM, LTR, NTT)', max_length=10, verbose_name='Customs Measure Unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='efris_customs_scaled_value',
            field=models.DecimalField(decimal_places=8, default=1, help_text='Conversion factor for customs unit', max_digits=12, verbose_name='Customs Scaled Value'),
        ),
        migrations.AddField(
            model_name='product',
            name='efris_customs_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price in customs measure unit', max_digits=12, null=True, verbose_name='Customs Unit Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='efris_has_other_units',
            field=models.BooleanField(default=False, help_text='Product has alternative measurement units', verbose_name='Has Other Units'),
        ),
        migrations.AddField(
            model_name='product',
            name='efris_other_units',
            field=models.JSONField(blank=True, help_text='Array of {otherUnit, otherPrice, otherScaled, packageScaled}', null=True, verbose_name='Other Units'),
        ),
        migrations.AddField(
            model_name='product',
            name='efris_package_scaled_value',
            field=models.DecimalField(decimal_places=8, default=1, help_text='MANDATORY when havePieceUnit=101', max_digits=12, verbose_name='Package Scaled Value'),
        ),
        migrations.AddField(
            model_name='product',
            name='efris_package_scaled_value_customs',
            field=models.DecimalField(decimal_places=8, default=1, help_text='Package scaling for customs unit', max_digits=12, verbose_name='Package Scaled Value (Customs)'),
        ),
        migrations.AddField(
            model_name='product',
            name='efris_piece_scaled_value',
            field=models.DecimalField(decimal_places=8, default=1, help_text='MANDATORY when havePieceUnit=101', max_digits=12, verbose_name='Piece Scaled Value'),
        ),
        migrations.AddField(
            model_name='product',
            name='efris_service_mark',
            field=models.CharField(blank=True, default='102', help_text='101=Service, 102=Product', max_length=3, verbose_name='Service Mark'),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Harmonized System code for exports', max_length=50, verbose_name='HS Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_name',
            field=models.CharField(blank=True, help_text='Description of HS code', max_length=1000, verbose_name='HS Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_export_product',
            field=models.BooleanField(default=False, help_text='Product configured for export sales', verbose_name='Export Product'),
        ),
        migrations.AddField(
            model_name='service',
            name='efris_service_mark',
            field=models.CharField(default='101', help_text='Always 101 for services', max_length=3, verbose_name='Service Mark'),
        ),
    ]
