# Generated by Django 5.0.6 on 2026-02-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_efris_customs_measure_unit_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_is_expo_5183cf_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_export_ready',
        ),
        migrations.AddField(
            model_name='product',
            name='item_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight per unit in KG (required for export)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='piece_qty',
            field=models.IntegerField(blank=True, default=1, help_text='Number of pieces per unit', null=True),
        ),
    ]
