# Generated by Django 5.0.6 on 2026-02-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_inventory_p_is_expo_5183cf_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='efris_package_scaled_value',
            field=models.DecimalField(blank=True, decimal_places=8, default=1, help_text='MANDATORY when havePieceUnit=101', max_digits=12, null=True, verbose_name='Package Scaled Value'),
        ),
    ]
