# Generated by Django 5.0.6 on 2026-02-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_efris_package_scaled_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='efris_customs_scaled_value',
            field=models.DecimalField(blank=True, decimal_places=8, default=1, help_text='Conversion factor for customs unit', max_digits=12, null=True, verbose_name='Customs Scaled Value'),
        ),
        migrations.AlterField(
            model_name='product',
            name='efris_package_scaled_value_customs',
            field=models.DecimalField(blank=True, decimal_places=8, default=1, help_text='Package scaling for customs unit', max_digits=12, null=True, verbose_name='Package Scaled Value (Customs)'),
        ),
    ]
