# Generated by Django 5.0.6 on 2026-03-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_category_sync_id_importlog_sync_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='transfer_date',
            field=models.DateField(blank=True, help_text='Actual date when the stock was physically transferred.', null=True, verbose_name='Transfer Date'),
        ),
    ]
