# Generated by Django 5.0.6 on 2026-03-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_stocktransfer_transfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person'),
        ),
    ]
