# Generated by Django 5.0.6 on 2026-03-10 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_supplier_address_alter_supplier_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Percentage'),
        ),
    ]
