# Generated by Django 5.0.6 on 2026-03-25 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_product_discount_percentage'),
        ('stores', '0009_alter_store_physical_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_type', models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer barcode (EAN/UPC on product)'), ('internal', 'Internal barcode (generated by us)')], default='manufacturer', help_text='Manufacturer = barcode already on the product. Internal = we generated and printed this barcode.', max_length=20, verbose_name='Barcode type')),
                ('barcode_image', models.ImageField(blank=True, help_text='Auto-generated barcode PNG for label printing', null=True, upload_to='barcodes/', verbose_name='Barcode image')),
                ('is_bundle', models.BooleanField(default=False, help_text='Enable if this product is a bundle/carton that maps to child unit products.', verbose_name='Is a bundle / carton')),
                ('sync_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('child_qty', models.PositiveIntegerField(default=1, help_text='e.g. 24 for a carton of 24 bottles', verbose_name='Units per Bundle')),
                ('is_separate_product', models.BooleanField(default=False, help_text='ON = carton has its own stock level. OFF = scanning carton adds units directly to child product.', verbose_name='Track carton stock separately')),
                ('cost_price_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use child product's cost price", max_digits=12, null=True, verbose_name='Cost price per unit (override)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_product', models.ForeignKey(help_text="The individual item (e.g. 'Soda Bottle 300ml')", on_delete=django.db.models.deletion.CASCADE, related_name='contained_in_bundles', to='inventory.product', verbose_name='Child / Unit Product')),
                ('parent_product', models.ForeignKey(help_text="The product that represents the bundle (e.g. 'Soda Carton x24')", on_delete=django.db.models.deletion.CASCADE, related_name='bundle_definitions', to='inventory.product', verbose_name='Bundle / Carton Product')),
            ],
            options={
                'verbose_name': 'Product Bundle',
                'verbose_name_plural': 'Product Bundles',
                'ordering': ['parent_product__name'],
                'unique_together': {('parent_product', 'child_product')},
            },
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('mode', models.CharField(choices=[('receive_stock', 'Receive Stock'), ('stock_count', 'Stock Count'), ('product_lookup', 'Product Lookup'), ('pos_checkout', 'POS Checkout')], default='receive_stock', max_length=20, verbose_name='Scan mode')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=20)),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('successful_scans', models.PositiveIntegerField(default=0)),
                ('failed_scans', models.PositiveIntegerField(default=0)),
                ('new_products_created', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_sessions', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Session',
                'verbose_name_plural': 'Scan Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BarcodeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Number of labels to print')),
                ('label_size', models.CharField(choices=[('small', 'Small (38×19mm)'), ('medium', 'Medium (57×32mm)'), ('large', 'Large (100×50mm)')], default='medium', max_length=10, verbose_name='Label size')),
                ('include_price', models.BooleanField(default=True, verbose_name='Print price on label')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_labels_printed', to=settings.AUTH_USER_MODEL, verbose_name='Printed by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_labels', to='inventory.product', verbose_name='Product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_label_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
                ('store', models.ForeignKey(blank=True, help_text='Store requesting the print (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_labels', to='stores.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Barcode Label',
                'verbose_name_plural': 'Barcode Labels',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='inventory_b_status_8348f4_idx'), models.Index(fields=['product', 'status'], name='inventory_b_product_3ecb1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_scanned', models.CharField(db_index=True, max_length=100)),
                ('outcome', models.CharField(choices=[('stock_added', 'Stock Added'), ('product_created', 'Product Created'), ('product_found', 'Product Found (lookup)'), ('added_to_cart', 'Added to Cart (POS)'), ('not_found', 'Not Found'), ('error', 'Error')], db_index=True, max_length=20)),
                ('quantity_added', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('was_bundle_scan', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='inventory.productbundle')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='inventory.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.scansession')),
            ],
            options={
                'verbose_name': 'Scan Event',
                'verbose_name_plural': 'Scan Events',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['session', 'scanned_at'], name='inventory_s_session_c15cae_idx'), models.Index(fields=['barcode_scanned'], name='inventory_s_barcode_a8cb9d_idx')],
            },
        ),
    ]
