# Generated by Django 5.0.6 on 2026-03-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_productbundle_scansession_barcodelabel_scanevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbundle',
            name='barcode_image',
        ),
        migrations.RemoveField(
            model_name='productbundle',
            name='barcode_type',
        ),
        migrations.RemoveField(
            model_name='productbundle',
            name='is_bundle',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, help_text='Auto-generated barcode PNG for label printing', null=True, upload_to='barcodes/', verbose_name='Barcode image'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_type',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer barcode (EAN/UPC on product)'), ('internal', 'Internal barcode (generated by us)')], default='manufacturer', help_text='Manufacturer = barcode already on the product. Internal = we generated and printed this barcode.', max_length=20, verbose_name='Barcode type'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False, help_text='Enable if this product is a bundle/carton that maps to child unit products.', verbose_name='Is a bundle / carton'),
        ),
    ]
