# Generated by Django 5.0.6 on 2026-04-06 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_productbundle_barcode_image_and_more'),
        ('stores', '0009_alter_store_physical_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category - EFRIS commodity category will be inherited from this', limit_choices_to={'category_type': 'product', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='from_store',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='stores.store', verbose_name='From Store'),
        ),
    ]
