# Generated by Django 5.2.4 on 2025-10-24 08:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EFRISReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('report_type', models.CharField(choices=[('SALES_SUMMARY', 'Sales Summary'), ('PRODUCT_PERFORMANCE', 'Product Performance'), ('INVENTORY_STATUS', 'Inventory Status'), ('TAX_REPORT', 'Tax Report'), ('Z_REPORT', 'Z Report'), ('PRICE_LOOKUP', 'Price Lookup Report'), ('EFRIS_COMPLIANCE', 'EFRIS Compliance Report'), ('CASHIER_PERFORMANCE', 'Cashier Performance'), ('PROFIT_LOSS', 'Profit & Loss Statement'), ('STOCK_MOVEMENT', 'Stock Movement Report'), ('CUSTOMER_ANALYTICS', 'Customer Analytics'), ('CUSTOM', 'Custom Report')], max_length=50, verbose_name='Report Type')),
                ('template_file', models.FileField(upload_to='reports/efris_templates/', verbose_name='Template File')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Template')),
                ('version', models.CharField(max_length=20, verbose_name='Template Version')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid To')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('ura_approved', models.BooleanField(default=False, verbose_name='URA Approved')),
            ],
            options={
                'verbose_name': 'EFRIS Report Template',
                'verbose_name_plural': 'EFRIS Report Templates',
                'ordering': ['-valid_from', 'report_type'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict, verbose_name='Generation Parameters')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='File Path')),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=10, verbose_name='File Format')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Progress (%)')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('is_efris_verified', models.BooleanField(default=False, verbose_name='EFRIS Verified')),
                ('efris_verification_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='EFRIS Verification Code')),
                ('efris_verification_date', models.DateTimeField(blank=True, null=True, verbose_name='EFRIS Verification Date')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task ID')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Row Count')),
                ('generation_time', models.FloatField(default=0.0, verbose_name='Generation Time (seconds)')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Report Name')),
                ('report_type', models.CharField(choices=[('SALES_SUMMARY', 'Sales Summary'), ('PRODUCT_PERFORMANCE', 'Product Performance'), ('INVENTORY_STATUS', 'Inventory Status'), ('TAX_REPORT', 'Tax Report'), ('Z_REPORT', 'Z Report'), ('PRICE_LOOKUP', 'Price Lookup Report'), ('EFRIS_COMPLIANCE', 'EFRIS Compliance Report'), ('CASHIER_PERFORMANCE', 'Cashier Performance'), ('PROFIT_LOSS', 'Profit & Loss Statement'), ('STOCK_MOVEMENT', 'Stock Movement Report'), ('CUSTOMER_ANALYTICS', 'Customer Analytics'), ('CUSTOM', 'Custom Report')], max_length=50, verbose_name='Report Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('last_executed', models.DateTimeField(blank=True, null=True, verbose_name='Last Executed')),
                ('execution_count', models.PositiveIntegerField(default=0, verbose_name='Execution Count')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Is Shared')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Is Favorite')),
                ('columns', models.JSONField(default=list, verbose_name='Report Columns')),
                ('filters', models.JSONField(default=dict, verbose_name='Report Filters')),
                ('parameters', models.JSONField(default=dict, help_text='Additional parameters for report generation', verbose_name='Report Parameters')),
                ('visualization_config', models.JSONField(default=dict, help_text='Chart.js configuration for visualizations', verbose_name='Visualization Configuration')),
                ('is_efris_approved', models.BooleanField(default=False, help_text='Whether this report format is approved by URA', verbose_name='EFRIS Approved')),
                ('cache_duration', models.PositiveIntegerField(default=300, help_text='How long to cache report results', verbose_name='Cache Duration (seconds)')),
                ('enable_caching', models.BooleanField(default=True, verbose_name='Enable Caching')),
                ('pdf_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape'), ('auto', 'Auto')], default='auto', max_length=10, verbose_name='PDF Orientation')),
                ('include_charts', models.BooleanField(default=True, verbose_name='Include Charts in Export')),
                ('tags', models.JSONField(default=list, help_text='Tags for categorizing reports', verbose_name='Tags')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Report',
                'verbose_name_plural': 'Saved Reports',
                'ordering': ['-last_modified'],
                'permissions': [('generate_efris_reports', 'Can generate EFRIS reports'), ('approve_efris_reports', 'Can approve EFRIS reports'), ('export_reports', 'Can export reports'), ('schedule_reports', 'Can schedule reports'), ('share_reports', 'Can share reports')],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20, verbose_name='Frequency')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Required for weekly frequency', null=True, verbose_name='Day of Week')),
                ('day_of_month', models.IntegerField(blank=True, help_text='Required for monthly frequency', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Day of Month')),
                ('time_of_day', models.TimeField(default='09:00:00', verbose_name='Time of Day')),
                ('recipients', models.TextField(help_text='Comma-separated email addresses', verbose_name='Recipients')),
                ('cc_recipients', models.TextField(blank=True, help_text='Comma-separated email addresses', null=True, verbose_name='CC Recipients')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON')], default='PDF', max_length=10, verbose_name='Export Format')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Last Sent At')),
                ('next_scheduled', models.DateTimeField(blank=True, null=True, verbose_name='Next Scheduled Run')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('include_efris', models.BooleanField(default=False, help_text='Include EFRIS verification data in scheduled reports', verbose_name='Include EFRIS Data')),
                ('efris_report_format', models.CharField(blank=True, help_text='Format required by Uganda Revenue Authority', max_length=50, null=True, verbose_name='EFRIS Report Format')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max Retries')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.savedreport')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['next_scheduled'],
            },
        ),
        migrations.CreateModel(
            name='ReportComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Comparison Name')),
                ('base_period', models.JSONField(help_text='Start and end dates for base period', verbose_name='Base Period')),
                ('compare_period', models.JSONField(help_text='Start and end dates for comparison period', verbose_name='Compare Period')),
                ('metrics', models.JSONField(default=list, verbose_name='Metrics to Compare')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='reports.savedreport')),
            ],
            options={
                'verbose_name': 'Report Comparison',
                'verbose_name_plural': 'Report Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Viewed'), ('GENERATE', 'Generated'), ('DOWNLOAD', 'Downloaded'), ('EXPORT', 'Exported'), ('SHARE', 'Shared'), ('DELETE', 'Deleted'), ('SCHEDULE', 'Scheduled')], max_length=20, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('parameters', models.JSONField(default=dict, verbose_name='Request Parameters')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('duration', models.FloatField(default=0.0, verbose_name='Duration (seconds)')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('generated_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='reports.generatedreport')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_accesses', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='reports.savedreport')),
            ],
            options={
                'verbose_name': 'Report Access Log',
                'verbose_name_plural': 'Report Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_instances', to='reports.savedreport'),
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['report_type', 'is_shared'], name='reports_sav_report__104a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['created_by', 'is_favorite'], name='reports_sav_created_66146e_idx'),
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['last_executed'], name='reports_sav_last_ex_51a714_idx'),
        ),
        migrations.AddIndex(
            model_name='reportaccesslog',
            index=models.Index(fields=['user', '-timestamp'], name='reports_rep_user_id_05dfad_idx'),
        ),
        migrations.AddIndex(
            model_name='reportaccesslog',
            index=models.Index(fields=['report', '-timestamp'], name='reports_rep_report__7f8053_idx'),
        ),
        migrations.AddIndex(
            model_name='reportaccesslog',
            index=models.Index(fields=['action', '-timestamp'], name='reports_rep_action_64e2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['status', 'generated_at'], name='reports_gen_status_4d1741_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['generated_by', '-generated_at'], name='reports_gen_generat_e2bb98_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['task_id'], name='reports_gen_task_id_b7f6e8_idx'),
        ),
    ]
