# Generated by Django 5.0.6 on 2025-12-20 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='generatedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'PROCESSING'])), fields=('report', 'generated_by'), name='one_active_report_per_user'),
        ),
    ]
