# Generated by Django 5.0.6 on 2025-12-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_generatedreport_one_active_report_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='generatedreport',
            name='one_active_report_per_user',
        ),
    ]
