# Generated by Django 5.0.6 on 2026-01-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_generatedreport_one_active_report_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efrisreporttemplate',
            name='report_type',
            field=models.CharField(choices=[('SALES_SUMMARY', 'Sales Summary'), ('PRODUCT_PERFORMANCE', 'Product Performance'), ('INVENTORY_STATUS', 'Inventory Status'), ('TAX_REPORT', 'Tax Report'), ('EFRIS_COMPLIANCE', 'EFRIS Compliance Report'), ('CASHIER_PERFORMANCE', 'Cashier Performance'), ('PROFIT_LOSS', 'Profit & Loss Statement'), ('STOCK_MOVEMENT', 'Stock Movement Report'), ('CUSTOMER_ANALYTICS', 'Customer Analytics'), ('CUSTOM', 'Custom Report')], max_length=50, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='report_type',
            field=models.CharField(choices=[('SALES_SUMMARY', 'Sales Summary'), ('PRODUCT_PERFORMANCE', 'Product Performance'), ('INVENTORY_STATUS', 'Inventory Status'), ('TAX_REPORT', 'Tax Report'), ('EFRIS_COMPLIANCE', 'EFRIS Compliance Report'), ('CASHIER_PERFORMANCE', 'Cashier Performance'), ('PROFIT_LOSS', 'Profit & Loss Statement'), ('STOCK_MOVEMENT', 'Stock Movement Report'), ('CUSTOMER_ANALYTICS', 'Customer Analytics'), ('CUSTOM', 'Custom Report')], max_length=50, verbose_name='Report Type'),
        ),
    ]
