# Generated by Django 5.0.6 on 2026-02-20 07:30

import uuid
from django.db import migrations, models


def populate_sync_ids(apps, schema_editor):
    models_to_update = [
        ('reports', 'EFRISReportTemplate'),
        ('reports', 'GeneratedReport'),
        ('reports', 'ReportAccessLog'),
        ('reports', 'ReportComparison'),
        ('reports', 'ReportSchedule'),
        ('reports', 'SavedReport'),
    ]
    for app_label, model_name in models_to_update:
        try:
            Model = apps.get_model(app_label, model_name)
            for obj in Model.objects.filter(sync_id__isnull=True):
                obj.sync_id = uuid.uuid4()
                obj.save(update_fields=['sync_id'])
        except Exception as e:
            print(f"Skipping {app_label}.{model_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_efrisreporttemplate_report_type_and_more'),
    ]

    operations = [
        # STEP 1: Add columns without unique constraint
        migrations.AddField(
            model_name='efrisreporttemplate',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='reportaccesslog',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='reportcomparison',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),

        # STEP 2: Populate unique UUIDs for all existing rows per tenant
        migrations.RunPython(
            populate_sync_ids,
            migrations.RunPython.noop,
        ),

        # STEP 3: Now safe to add unique constraint
        migrations.AlterField(
            model_name='efrisreporttemplate',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='reportaccesslog',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='reportcomparison',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]