# Generated by Django 5.2.4 on 2025-11-08 04:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_type', models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat'), ('channel', 'Channel'), ('department', 'Department'), ('broadcast', 'Broadcast')], default='direct', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Name for groups/channels only', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('encrypted_symmetric_key', models.TextField(help_text='AES key encrypted for each participant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_cross_tenant', models.BooleanField(default=False, help_text='Can include users from multiple tenants (SaaS admin only)')),
                ('tenant_schemas', models.JSONField(default=list, help_text='List of tenant schemas involved (for cross-tenant only)')),
                ('message_retention_days', models.IntegerField(default=365, help_text='Auto-delete messages older than this (0 = never)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_conversation_key', models.TextField(help_text="Conversation symmetric key encrypted with user's public key")),
                ('can_send_messages', models.BooleanField(default=True)),
                ('can_add_participants', models.BooleanField(default=False)),
                ('can_remove_participants', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('display_name', models.CharField(blank=True, help_text='Custom name for this user in this conversation', max_length=100)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_participants',
            },
        ),
        migrations.CreateModel(
            name='EncryptionKeyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(help_text='RSA public key (PEM format)')),
                ('encrypted_private_key', models.TextField(help_text='RSA private key encrypted with user password')),
                ('key_created_at', models.DateTimeField(auto_now_add=True)),
                ('key_version', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encryption_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_encryption_keys',
            },
        ),
        migrations.CreateModel(
            name='LegalAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(help_text='Official case/request number', max_length=100, unique=True)),
                ('request_type', models.CharField(choices=[('court_order', 'Court Order'), ('subpoena', 'Subpoena'), ('warrant', 'Search Warrant'), ('law_enforcement', 'Law Enforcement Request'), ('regulatory', 'Regulatory Investigation')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('denied', 'Denied'), ('fulfilled', 'Fulfilled'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('authority_name', models.CharField(help_text='Name of requesting authority', max_length=255)),
                ('authority_contact', models.EmailField(help_text='Contact email', max_length=254)),
                ('badge_number', models.CharField(blank=True, help_text='Badge/ID number of requesting officer', max_length=100)),
                ('date_range_start', models.DateTimeField(blank=True, help_text='Start date for messages to retrieve', null=True)),
                ('date_range_end', models.DateTimeField(blank=True, help_text='End date for messages to retrieve', null=True)),
                ('legal_document', models.FileField(help_text='Upload court order/warrant/subpoena', upload_to='legal_requests/%Y/%m/')),
                ('request_description', models.TextField(help_text='Description of what is being requested')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('export_file', models.FileField(blank=True, help_text='Exported decrypted messages', null=True, upload_to='legal_exports/%Y/%m/')),
                ('export_password', models.CharField(blank=True, help_text='Password for encrypted export (store securely!)', max_length=255)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retention_until', models.DateField(help_text='Delete exported data after this date')),
                ('accessed_count', models.IntegerField(default=0, help_text='Number of times export was accessed')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_legal_requests', to=settings.AUTH_USER_MODEL)),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exported_legal_requests', to=settings.AUTH_USER_MODEL)),
                ('target_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.conversation')),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_legal_access_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed (viewed, exported, downloaded, etc.)', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='messaging.legalaccessrequest')),
            ],
            options={
                'db_table': 'messaging_legal_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_content', models.TextField(help_text="Message encrypted with conversation's symmetric key")),
                ('encrypted_iv', models.CharField(help_text='Initialization vector for AES encryption', max_length=255)),
                ('message_hash', models.CharField(help_text='SHA-256 hash for integrity verification', max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('system', 'System'), ('announcement', 'Announcement')], default='text', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('original_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('edit_history', models.JSONField(default=list, help_text='History of edits (timestamps only, not content)')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL)),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='message_mentions', to=settings.AUTH_USER_MODEL)),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_file', models.FileField(upload_to='messaging/attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'rar', 'txt', 'csv', 'mp4', 'mp3'])])),
                ('encrypted_filename', models.CharField(max_length=500)),
                ('encrypted_file_size', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('encrypted_iv', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='messaging/thumbnails/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message')),
            ],
            options={
                'db_table': 'messaging_attachments',
            },
        ),
        migrations.CreateModel(
            name='MessageAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Message Created'), ('edited', 'Message Edited'), ('deleted', 'Message Deleted'), ('conversation_created', 'Conversation Created'), ('participant_added', 'Participant Added'), ('participant_removed', 'Participant Removed')], max_length=30)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context (participant count, file count, etc.)')),
                ('tenant_id', models.IntegerField(blank=True, help_text='Tenant ID from django-tenants', null=True)),
                ('tenant_name', models.CharField(blank=True, help_text='Tenant schema name', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.message')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(help_text='Emoji unicode or shortcode', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_reactions',
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_read_receipts',
            },
        ),
        migrations.CreateModel(
            name='MessageSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(help_text='Extracted keywords for search (not full content)')),
                ('sender_name', models.CharField(max_length=255)),
                ('conversation_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='messaging.message')),
            ],
            options={
                'db_table': 'messaging_search_index',
            },
        ),
        migrations.CreateModel(
            name='MessagingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tenant_id', models.CharField(max_length=50)),
                ('tenant_name', models.CharField(blank=True, max_length=255)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_conversations', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('direct_conversations', models.IntegerField(default=0)),
                ('group_conversations', models.IntegerField(default=0)),
                ('files_shared', models.IntegerField(default=0)),
                ('total_storage_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messaging_statistics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'tenant_id'], name='messaging_s_date_c6b6f7_idx')],
                'unique_together': {('date', 'tenant_id')},
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('maintenance', 'Maintenance'), ('update', 'Update'), ('feature', 'New Feature'), ('critical', 'Critical Alert')], default='info', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('target_all_tenants', models.BooleanField(default=True, help_text='Send to all tenants')),
                ('target_tenant_ids', models.JSONField(default=list, help_text='Specific tenant IDs if not all')),
                ('target_user_roles', models.JSONField(default=list, help_text="Target specific roles: ['admin', 'manager', etc.]")),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Schedule for future delivery', null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('show_in_app', models.BooleanField(default=True, help_text='Show as in-app notification')),
                ('send_email', models.BooleanField(default=False, help_text='Send email notification')),
                ('is_dismissible', models.BooleanField(default=True, help_text='Users can dismiss this announcement')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-hide after this date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_text', models.CharField(blank=True, help_text="Button text (e.g., 'Learn More')", max_length=100)),
                ('action_url', models.URLField(blank=True, help_text='URL for action button')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_system_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='messaging.systemannouncement')),
            ],
            options={
                'db_table': 'messaging_announcement_reads',
            },
        ),
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to='messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_typing_indicators',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', 'is_active'], name='messaging_c_convers_32b9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='messaging_c_created_bf9c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_cross_tenant'], name='messaging_c_is_cros_d6a438_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_by'], name='messaging_c_created_2fd3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', 'is_active'], name='messaging_p_user_id_a70b37_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation', 'is_active'], name='messaging_p_convers_85a799_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['last_read_at'], name='messaging_p_last_re_ae2f50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='encryptionkeymanager',
            index=models.Index(fields=['user'], name='messaging_e_user_id_6f00c8_idx'),
        ),
        migrations.AddIndex(
            model_name='legalaccessrequest',
            index=models.Index(fields=['status', 'created_at'], name='messaging_l_status_4b2224_idx'),
        ),
        migrations.AddIndex(
            model_name='legalaccessrequest',
            index=models.Index(fields=['request_number'], name='messaging_l_request_b2a2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messaging_m_convers_5aa9d6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='messaging_m_sender__375c73_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted', 'created_at'], name='messaging_m_is_dele_9ca4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_pinned'], name='messaging_m_is_pinn_4e2ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='messaging_a_message_0c16ba_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['uploaded_at'], name='messaging_a_uploade_dc46eb_idx'),
        ),
        migrations.AddIndex(
            model_name='messageauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='messaging_a_user_id_e46043_idx'),
        ),
        migrations.AddIndex(
            model_name='messageauditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='messaging_a_action__45bb19_idx'),
        ),
        migrations.AddIndex(
            model_name='messageauditlog',
            index=models.Index(fields=['tenant_id', 'timestamp'], name='messaging_a_tenant__fa2385_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message'], name='messaging_r_message_b01d17_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user'], name='messaging_r_user_id_129015_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['message', 'user'], name='messaging_r_message_ecacc8_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['user', 'read_at'], name='messaging_r_user_id_2c89bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadreceipt',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='messagesearchindex',
            index=models.Index(fields=['conversation_id', 'created_at'], name='messaging_s_convers_c40afe_idx'),
        ),
        migrations.AddIndex(
            model_name='messagesearchindex',
            index=models.Index(fields=['sender_name'], name='messaging_s_sender__ccf953_idx'),
        ),
        migrations.AddIndex(
            model_name='systemannouncement',
            index=models.Index(fields=['is_sent', 'scheduled_for'], name='messaging_s_is_sent_e8588c_idx'),
        ),
        migrations.AddIndex(
            model_name='systemannouncement',
            index=models.Index(fields=['created_at'], name='messaging_s_created_285053_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['user', 'is_dismissed'], name='messaging_a_user_id_935853_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementread',
            unique_together={('announcement', 'user')},
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['conversation', 'started_at'], name='messaging_t_convers_0b2197_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typingindicator',
            unique_together={('conversation', 'user')},
        ),
    ]
