# Generated by Django 5.0.6 on 2025-11-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageauditlog',
            name='tenant_id',
            field=models.CharField(blank=True, help_text='Tenant ID from django-tenants', max_length=255, null=True),
        ),
    ]
