# Generated by Django 5.0.6 on 2025-11-18 04:41

import customers.efris
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Customer ID')),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business'), ('GOVERNMENT', 'Government Agency'), ('NGO', 'Non-Profit Organization')], default='INDIVIDUAL', max_length=20, verbose_name='Customer Type')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]+$', 'Enter a valid phone number.')], verbose_name='Phone Number')),
                ('tin', models.CharField(blank=True, help_text='Required for B2B transactions', max_length=20, null=True, verbose_name='Tax Identification Number (TIN)')),
                ('nin', models.CharField(blank=True, max_length=20, null=True, verbose_name='National ID Number (NIN)')),
                ('brn', models.CharField(blank=True, max_length=20, null=True, verbose_name='Business Registration Number (BRN)')),
                ('physical_address', models.TextField(blank=True, null=True, verbose_name='Physical Address')),
                ('postal_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal Address')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('country', models.CharField(default='Uganda', max_length=100, verbose_name='Country')),
                ('is_vat_registered', models.BooleanField(default=False, verbose_name='VAT Registered')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Credit Limit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('efris_customer_type', models.CharField(blank=True, choices=[('1', 'Individual'), ('2', 'Business'), ('3', 'Government'), ('4', 'NGO')], help_text='Customer type code for eFRIS system', max_length=10, null=True, verbose_name='eFRIS Customer Type')),
                ('efris_customer_id', models.CharField(blank=True, help_text='Unique customer ID from eFRIS system', max_length=50, null=True, unique=True, verbose_name='eFRIS Customer ID')),
                ('efris_status', models.CharField(choices=[('NOT_REGISTERED', 'Not Registered'), ('PENDING', 'Registration Pending'), ('REGISTERED', 'Registered'), ('FAILED', 'Registration Failed'), ('UPDATED', 'Updated')], default='NOT_REGISTERED', max_length=20, verbose_name='eFRIS Registration Status')),
                ('efris_registered_at', models.DateTimeField(blank=True, null=True, verbose_name='eFRIS Registration Date')),
                ('efris_last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last eFRIS Sync')),
                ('efris_reference_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='eFRIS Reference Number')),
                ('efris_sync_error', models.TextField(blank=True, help_text='Last error message from eFRIS sync', null=True, verbose_name='eFRIS Sync Error')),
                ('passport_number', models.CharField(blank=True, help_text='For foreign customers', max_length=20, null=True, verbose_name='Passport Number')),
                ('driving_license', models.CharField(blank=True, max_length=20, null=True, verbose_name='Driving License Number')),
                ('voter_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Voter ID Number')),
                ('alien_id', models.CharField(blank=True, help_text='For non-citizen residents', max_length=20, null=True, verbose_name='Alien ID Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('store', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='stores.store')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
            bases=(models.Model, customers.efris.EFRISCustomerMixin),
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount Percentage')),
                ('auto_sync_to_efris', models.BooleanField(default=False, help_text='Automatically sync new customers in this group to eFRIS', verbose_name='Auto Sync to eFRIS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customers', models.ManyToManyField(blank=True, related_name='groups', to='customers.customer', verbose_name='Customers')),
            ],
            options={
                'verbose_name': 'Customer Group',
                'verbose_name_plural': 'Customer Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Note')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('EFRIS', 'eFRIS Related'), ('TAX', 'Tax Information'), ('PAYMENT', 'Payment Related'), ('SUPPORT', 'Support Issue')], default='GENERAL', max_length=20, verbose_name='Category')),
                ('is_important', models.BooleanField(default=False, verbose_name='Important')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Note',
                'verbose_name_plural': 'Customer Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EFRISCustomerSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('REGISTER', 'Registration'), ('UPDATE', 'Update'), ('QUERY', 'Query')], max_length=20, verbose_name='Sync Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRY', 'Retry Required')], default='PENDING', max_length=20, verbose_name='Status')),
                ('request_payload', models.JSONField(blank=True, null=True, verbose_name='Request Payload')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Response Data')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('efris_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='eFRIS Reference')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Max Retries')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efris_syncs', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'eFRIS Customer Sync',
                'verbose_name_plural': 'eFRIS Customer Syncs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tin'], name='customers_c_tin_c45370_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['nin'], name='customers_c_nin_b726f4_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['brn'], name='customers_c_brn_c90352_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['efris_customer_id'], name='customers_c_efris_c_b6e5be_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['efris_status'], name='customers_c_efris_s_1514a7_idx'),
        ),
        migrations.AddIndex(
            model_name='efriscustomersync',
            index=models.Index(fields=['customer', 'sync_type'], name='customers_e_custome_1b92aa_idx'),
        ),
        migrations.AddIndex(
            model_name='efriscustomersync',
            index=models.Index(fields=['status'], name='customers_e_status_260115_idx'),
        ),
        migrations.AddIndex(
            model_name='efriscustomersync',
            index=models.Index(fields=['created_at'], name='customers_e_created_1cd0db_idx'),
        ),
    ]
