# Generated by Django 5.0.6 on 2025-12-23 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0006_saleitem_stock_deducted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allow_credit',
            field=models.BooleanField(default=False, help_text='Whether this customer can buy on credit', verbose_name='Allow Credit Sales'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_available',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credit limit minus current balance', max_digits=12, verbose_name='Available Credit'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total outstanding amount owed', max_digits=12, verbose_name='Current Credit Balance'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days allowed for credit payment', verbose_name='Credit Payment Days'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_status',
            field=models.CharField(choices=[('GOOD', 'Good Standing'), ('WARNING', 'Payment Warning'), ('SUSPENDED', 'Credit Suspended'), ('BLOCKED', 'Blocked')], default='GOOD', max_length=20, verbose_name='Credit Status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_credit_review',
            field=models.DateField(blank=True, null=True, verbose_name='Last Credit Review Date'),
        ),
        migrations.CreateModel(
            name='CustomerCreditStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INVOICE', 'Invoice Created'), ('PAYMENT', 'Payment Received'), ('CREDIT_NOTE', 'Credit Note'), ('ADJUSTMENT', 'Balance Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_statements', to='customers.customer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.payment')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Customer Credit Statement',
                'verbose_name_plural': 'Customer Credit Statements',
                'ordering': ['-created_at'],
            },
        ),
    ]
