# Generated by Django 5.0.6 on 2026-02-04 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_allow_credit_customer_credit_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9]+$', 'Enter a valid phone number.')], verbose_name='Phone Number'),
        ),
    ]
