# Generated by Django 5.0.6 on 2026-03-24 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('platform', models.CharField(blank=True, default='', max_length=200)),
                ('traceback', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=20)),
                ('triage_notes', models.TextField(blank=True, default='')),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Crash Report',
                'verbose_name_plural': 'Crash Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrimeBooksVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Semver string e.g. '1.2.0'", max_length=32, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one active version is served to the desktop updater. Activating a new one deactivates all others.')),
                ('is_critical', models.BooleanField(default=False, help_text='Critical = mandatory update dialog, no Later button.')),
                ('min_version', models.CharField(blank=True, default='', help_text='Clients older than this are force-updated even if is_critical=False.', max_length=32)),
                ('changelog', models.TextField(blank=True, default='', help_text="Shown in the update dialog AND the public Download Center. Use bullet points: '• Fix one\\n• Fix two'")),
                ('download_url', models.URLField(help_text='Direct HTTPS URL to the primary Windows .exe installer. Returned by /api/v1/updates/check/ — must stay a flat URL for backward compatibility with updater.py.', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, help_text='Primary Windows installer size in bytes (optional, shown in update dialog).', null=True)),
                ('windows_builds', models.JSONField(blank=True, default=list, help_text='List of Windows build objects. First entry = primary download button. See module docstring for field structure.')),
                ('macos_builds', models.JSONField(blank=True, default=list, help_text='List of macOS build objects (same structure as windows_builds).')),
                ('linux_builds', models.JSONField(blank=True, default=list, help_text='List of Linux build objects (same structure as windows_builds).')),
                ('released_at', models.DateTimeField(blank=True, help_text='Public release date/time. Auto-set to created_at if left blank.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes — NOT shown to users.')),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
