# Generated by Django 5.0.6 on 2026-04-09 16:06

import saad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primebooksversion',
            name='linux_file',
            field=models.FileField(blank=True, help_text='Upload the primary Linux package (.AppImage, .deb, .tar.gz…). Stored under MEDIA_ROOT/primebooks/releases/linux/.', null=True, upload_to=saad.models.upload_to_linux),
        ),
        migrations.AddField(
            model_name='primebooksversion',
            name='linux_file_label',
            field=models.CharField(blank=True, default='Linux AppImage (.AppImage)', help_text='Button label for the uploaded Linux file.', max_length=100),
        ),
        migrations.AddField(
            model_name='primebooksversion',
            name='linux_min_os',
            field=models.CharField(blank=True, default='Ubuntu 20.04 / equivalent', help_text='Minimum Linux distro/version shown on the Download Center.', max_length=100),
        ),
        migrations.AddField(
            model_name='primebooksversion',
            name='linux_url',
            field=models.URLField(blank=True, default='', help_text='Manual Linux URL (fallback if no file is uploaded).', max_length=500),
        ),
        migrations.AddField(
            model_name='primebooksversion',
            name='macos_file',
            field=models.FileField(blank=True, help_text='Upload the primary macOS installer (.dmg or .pkg). Stored under MEDIA_ROOT/primebooks/releases/macos/.', null=True, upload_to=saad.models.upload_to_macos),
        ),
        migrations.AddField(
            model_name='primebooksversion',
            name='macos_file_label',
            field=models.CharField(blank=True, default='macOS Installer (.dmg)', help_text='Button label for the uploaded macOS file.', max_length=100),
        ),
        migrations.AddField(
            model_name='primebooksversion',
            name='macos_min_os',
            field=models.CharField(blank=True, default='macOS 11 Big Sur', help_text='Minimum macOS version shown on the Download Center.', max_length=100),
        ),
        migrations.AddField(
            model_name='primebooksversion',
            name='macos_url',
            field=models.URLField(blank=True, default='', help_text='Manual macOS URL (fallback if no file is uploaded).', max_length=500),
        ),
        migrations.AddField(
            model_name='primebooksversion',
            name='windows_file',
            field=models.FileField(blank=True, help_text='Upload the primary Windows installer (.exe). When set, this overrides the manual URL below. File is stored on your server under MEDIA_ROOT/primebooks/releases/windows/.', null=True, upload_to=saad.models.upload_to_windows),
        ),
        migrations.AddField(
            model_name='primebooksversion',
            name='windows_file_label',
            field=models.CharField(blank=True, default='Windows Installer (.exe)', help_text='Button label for the uploaded Windows file.', max_length=100),
        ),
        migrations.AddField(
            model_name='primebooksversion',
            name='windows_min_os',
            field=models.CharField(blank=True, default='Windows 10 64-bit', help_text='Minimum OS requirement shown on the Download Center.', max_length=100),
        ),
        migrations.AlterField(
            model_name='primebooksversion',
            name='download_url',
            field=models.URLField(blank=True, default='', help_text='Manual Windows .exe URL (fallback if no file is uploaded). Returned by /api/v1/updates/check/ — must stay a flat URL for backward compatibility with updater.py.', max_length=500),
        ),
        migrations.AlterField(
            model_name='primebooksversion',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, help_text='Primary Windows installer size in bytes (auto-detected on upload if left blank).', null=True),
        ),
        migrations.AlterField(
            model_name='primebooksversion',
            name='linux_builds',
            field=models.JSONField(blank=True, default=list, help_text='Extra Linux builds (same structure as windows_builds).'),
        ),
        migrations.AlterField(
            model_name='primebooksversion',
            name='macos_builds',
            field=models.JSONField(blank=True, default=list, help_text='Extra macOS builds (same structure as windows_builds).'),
        ),
        migrations.AlterField(
            model_name='primebooksversion',
            name='windows_builds',
            field=models.JSONField(blank=True, default=list, help_text='Extra Windows builds (e.g. portable .zip). List of {label, url, sha256, file_size, min_os}. The primary build is taken from windows_file / download_url — do NOT duplicate it here.'),
        ),
    ]
