# Generated by Django 5.2.4 on 2025-10-24 15:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(help_text='SMTP server hostname (e.g., smtp.gmail.com)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('smtp_username', models.CharField(help_text='SMTP authentication username', max_length=255)),
                ('smtp_password', models.CharField(help_text='SMTP authentication password (encrypted)', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption (port 587)')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption (port 465)')),
                ('from_email', models.EmailField(help_text="Default 'from' email address for this tenant", max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Display name for from email', max_length=255)),
                ('reply_to_email', models.EmailField(blank=True, help_text='Reply-to email address', max_length=254, null=True)),
                ('timeout', models.IntegerField(default=30, help_text='Connection timeout in seconds', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)])),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this email configuration')),
                ('is_verified', models.BooleanField(default=False, help_text='Email configuration has been tested and verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('test_result', models.TextField(blank=True, help_text='Result of last connection test')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='company.company')),
            ],
            options={
                'verbose_name': 'Tenant Email Settings',
                'verbose_name_plural': 'Tenant Email Settings',
                'db_table': 'tenant_email_settings',
            },
        ),
        migrations.CreateModel(
            name='TenantInvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers (e.g., INV, BILL)', max_length=10)),
                ('invoice_number_start', models.IntegerField(default=1000, help_text='Starting number for invoices')),
                ('invoice_number_padding', models.IntegerField(default=4, help_text='Number of digits in invoice number', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)])),
                ('default_payment_terms_days', models.IntegerField(default=30, help_text='Default payment terms in days')),
                ('invoice_notes', models.TextField(blank=True, help_text='Default notes to include on invoices')),
                ('invoice_terms', models.TextField(blank=True, help_text='Default terms and conditions for invoices')),
                ('show_company_logo', models.BooleanField(default=True)),
                ('invoice_template', models.CharField(choices=[('default', 'Default Template'), ('modern', 'Modern Template'), ('classic', 'Classic Template'), ('minimal', 'Minimal Template')], default='default', max_length=50)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default tax rate percentage', max_digits=5)),
                ('tax_name', models.CharField(default='VAT', help_text='Tax name (e.g., VAT, GST, Sales Tax)', max_length=50)),
                ('send_invoice_email', models.BooleanField(default=True, help_text='Automatically send invoice via email')),
                ('invoice_email_subject', models.CharField(default='Invoice {invoice_number} from {company_name}', help_text='Email subject template. Variables: {invoice_number}, {company_name}', max_length=255)),
                ('invoice_email_body', models.TextField(default='Please find attached your invoice.', help_text='Email body for invoice notifications')),
                ('enable_efris', models.BooleanField(default=False, help_text='Enable EFRIS integration for this tenant')),
                ('efris_tin', models.CharField(blank=True, help_text='TIN number for EFRIS', max_length=50)),
                ('efris_device_no', models.CharField(blank=True, help_text='EFRIS device number', max_length=50)),
                ('efris_private_key', models.TextField(blank=True, help_text='EFRIS private key for signing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='company.company')),
            ],
            options={
                'verbose_name': 'Tenant Invoice Settings',
                'verbose_name_plural': 'Tenant Invoice Settings',
                'db_table': 'tenant_invoice_settings',
            },
        ),
    ]
