# Generated by Django 5.0.6 on 2025-11-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='brand_colors',
            field=models.JSONField(blank=True, default=dict, help_text='Primary and secondary brand colors'),
        ),
        migrations.AlterField(
            model_name='company',
            name='efris_certificate_data',
            field=models.JSONField(blank=True, default=dict, help_text='RSA keys and certificate information', verbose_name='EFRIS Certificate Data'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ip_whitelist',
            field=models.JSONField(blank=True, default=list, help_text='Allowed IP addresses'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for categorizing companies'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Feature flags for this plan'),
        ),
    ]
