# Generated by Django 5.0.6 on 2025-11-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_vat_enabled',
            field=models.BooleanField(default=False, verbose_name='On VAT'),
        ),
    ]
