# Generated by Django 5.0.6 on 2025-11-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_vat_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_vat_enabled',
            field=models.BooleanField(default=False, help_text='Confirm wether company is on VAT', verbose_name='On VAT'),
        ),
    ]
