# Generated by Django 5.0.6 on 2025-11-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_is_vat_enabled'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='efriscommoditycategory',
            index=models.Index(fields=['service_mark', 'enable_status_code', 'is_leaf_node'], name='company_efr_service_962966_idx'),
        ),
        migrations.AddIndex(
            model_name='efriscommoditycategory',
            index=models.Index(fields=['parent_code', 'enable_status_code'], name='company_efr_parent__2dbe28_idx'),
        ),
    ]
