# Generated by Django 5.0.6 on 2025-11-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_efriscommoditycategory_company_efr_service_962966_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efriscommoditycategory',
            name='service_mark',
            field=models.CharField(choices=[('102', 'Product'), ('101', 'Service')], default='101', help_text='101 = Product, 102 = Service', max_length=3),
        ),
    ]
