# Generated by Django 5.0.6 on 2025-12-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_efriscommoditycategory_service_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efriscommoditycategory',
            name='service_mark',
            field=models.CharField(choices=[('101', 'Service'), ('102', 'Product')], default='102', help_text='101 = Service, 102 = Product', max_length=3),
        ),
    ]
