# Generated by Django 5.0.6 on 2025-12-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_efriscommoditycategory_service_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='efris_api_key',
        ),
        migrations.RemoveField(
            model_name='company',
            name='efris_client_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vat_registration_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vat_registration_number',
        ),
    ]
