# Generated by Django 5.0.6 on 2025-12-27 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_company_efris_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossCompanyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('PROCUREMENT', 'Procurement'), ('SALE', 'Sale'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('transaction_data', models.JSONField(default=dict)),
                ('source_reference_id', models.CharField(blank=True, help_text='Sale/Transfer ID in source company', max_length=50)),
                ('destination_reference_id', models.CharField(blank=True, help_text='Purchase ID in destination company', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('destination_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='company.company')),
                ('source_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('PARTNER', 'Business Partner'), ('COMPETITOR', 'Competitor')], max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_terms_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_relationships', to='company.company')),
                ('related_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='company.company')),
            ],
            options={
                'unique_together': {('company', 'related_company', 'relationship_type')},
            },
        ),
    ]
