# Generated by Django 5.0.6 on 2026-02-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_crosscompanytransaction_companyrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFRISHsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('parent_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('is_leaf', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField()),
            ],
            options={
                'ordering': ['hs_code'],
            },
        ),
    ]
