# Generated by Django 5.0.6 on 2026-03-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_efrishscode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi bi-puzzle', max_length=50)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_publicly_available', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='required_by', to='company.availablemodule')),
            ],
            options={
                'verbose_name': 'Available Module',
                'verbose_name_plural': 'Available Modules',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CompanyModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='company.company')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_subscriptions', to='company.availablemodule')),
            ],
            options={
                'verbose_name': 'Company Module',
                'verbose_name_plural': 'Company Modules',
                'unique_together': {('company', 'module')},
            },
        ),
    ]
