# Generated by Django 5.0.6 on 2026-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_availablemodule_companymodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodule',
            name='paid_through',
            field=models.DateField(blank=True, help_text='Last date of paid access', null=True),
        ),
    ]
