# Generated by Django 5.0.6 on 2026-04-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_companymodule_paid_through'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_efris_pause', 'Can activate/deactivate EFRIS pause mode')], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='efris_fiscalization_mode',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('paused', 'Paused – exempt window active')], default='disabled', help_text='"disabled" = normal off, catch-up on re-enable. "paused" = invoices/sales in this window are permanently exempt. Only admins with can_manage_efris_pause permission can set "paused".', max_length=10, verbose_name='EFRIS Fiscalization Mode'),
        ),
        migrations.AddField(
            model_name='company',
            name='efris_paused_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the current pause window started.', null=True, verbose_name='EFRIS Paused At'),
        ),
        migrations.AddField(
            model_name='company',
            name='efris_paused_by_id',
            field=models.CharField(blank=True, help_text='ID of admin user who activated pause mode.', max_length=50, null=True, verbose_name='EFRIS Paused By (User ID)'),
        ),
        migrations.AddField(
            model_name='company',
            name='efris_paused_by_name',
            field=models.CharField(blank=True, help_text='Display name of admin who activated pause mode (denormalized).', max_length=255, null=True, verbose_name='EFRIS Paused By (Name)'),
        ),
    ]
