# Generated by Django 5.0.6 on 2025-11-18 04:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifier', models.CharField(db_index=True, editable=False, help_text='Format: PRIME-XXXXPF-YYMM-LTD', max_length=50, unique=True, verbose_name='Login Identifier')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]+$', 'Enter a valid phone number.')], verbose_name='Phone Number')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'Administrator'), ('CONTENT_MANAGER', 'Content Manager'), ('SEO_MANAGER', 'SEO Manager'), ('BLOG_EDITOR', 'Blog Editor'), ('SUPPORT_AGENT', 'Support Agent'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Staff Status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser Status')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('password_changed_at', models.DateTimeField(auto_now_add=True)),
                ('force_password_change', models.BooleanField(default=True, help_text='User must change password on first login')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='public_accounts/avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('can_manage_seo', models.BooleanField(default=False)),
                ('can_manage_blog', models.BooleanField(default=False)),
                ('can_manage_support', models.BooleanField(default=False)),
                ('can_manage_companies', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Public User',
                'verbose_name_plural': 'Public Users',
                'db_table': 'public_users',
                'ordering': ['-date_joined'],
                'permissions': [('manage_seo_content', 'Can manage SEO content'), ('manage_blog_posts', 'Can manage blog posts'), ('manage_support_tickets', 'Can manage support tickets'), ('view_public_analytics', 'Can view public analytics'), ('manage_public_users', 'Can manage public users')],
                'indexes': [models.Index(fields=['identifier'], name='public_user_identif_cc919c_idx'), models.Index(fields=['email'], name='public_user_email_4d094c_idx'), models.Index(fields=['is_active', 'is_staff'], name='public_user_is_acti_d36014_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to='public_accounts.publicuser')),
            ],
            options={
                'db_table': 'public_password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset')], max_length=20)),
                ('app_name', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='public_accounts.publicuser')),
            ],
            options={
                'db_table': 'public_user_activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='public_user_user_id_c0976b_idx'), models.Index(fields=['action', 'timestamp'], name='public_user_action_3329d1_idx')],
            },
        ),
    ]
