# Generated by Django 5.0.6 on 2025-11-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'Administrator'), ('CONTENT_MANAGER', 'Content Manager'), ('SEO_MANAGER', 'SEO Manager'), ('BLOG_EDITOR', 'Blog Editor'), ('SUPPORT_AGENT', 'Support Agent'), ('VIEWER', 'Viewer')], default='SUPER_ADMIN', max_length=20, verbose_name='Role'),
        ),
    ]
