"""
sync/push_view.py
=================
POST /api/v1/sync/push/

Body:
  {
    "schema_name": "rem",
    "client_timestamp": 1234567890.123,
    "changes": {
      "customers": {
        "created": [{...}, ...],   ← sync_id generated by desktop
        "updated": [{...}, ...],   ← sync_id matches existing server record
        "deleted": ["<sync_id>", ...]
      },
      "sales":        { ... },
      "sale_items":   { ... },
      "expenses":     { ... },
      "categories":   { ... },
      "suppliers":    { ... },
      "products":     { ... },
      "stock":        { ... },
      "stock_movements": { ... }
    }
  }

Response:
  {
    "accepted": {
      "customers": ["<sync_id>", ...],
      "sales": [...],
      ...
    },
    "rejected": {
      "customers": [{"sync_id": "...", "error": "..."}, ...]
    },
    "conflicts": {
      "products": [{...server record...}]   ← server version, desktop should adopt
    }
  }

Conflict strategy:
  - For inventory (products, stock, categories, suppliers):
    server WINS on conflict (web is authoritative for inventory).
  - For sales, expenses, customers:
    desktop WINS (desktop is authoritative for what happened in the store).

sync_id lookup:
  1. Query by sync_id field (UUID from desktop)
  2. If not found → create new record, set sync_id
  3. On update → only overwrite if server record is not newer
     (compare updated_at — server wins on tie)

Field mapping notes (desktop → server):
  Sale:     status/payment_method/payment_status uppercased (server stores uppercase)
            amount_paid and change_amount are NOT DB fields on Sale — omitted from push
  SaleItem: subtotal → total_price, discount_percentage → discount
            total is a computed property (line_total) — not written directly
  Expense:  title → description, notes → description fallback
            date (DateField) not DateTimeField, payment_method uppercased
            no store FK on Expense model — store_id ignored on push
            user FK used instead of created_by
"""

import time
import logging
from decimal import Decimal, InvalidOperation
from datetime import datetime, timezone as tz

from django.db import transaction, IntegrityError
from django.utils import timezone as dj_timezone
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from .utils import (
    parse_sync_id, safe_decimal, safe_int, safe_bool,
    unix_to_dt, now_unix, get_client_ip, bulk_resolve_fk,
)

logger = logging.getLogger(__name__)

# Hard cap on records accepted per table per push request.
# Protects the server from runaway clients or malformed payloads.
MAX_RECORDS_PER_TABLE = 5_000


@api_view(["POST"])
@permission_classes([IsAuthenticated])
def sync_push(request):
    """
    Accept dirty records from desktop, apply to server DB.
    """
    data = request.data
    changes = data.get("changes", {})
    schema_name = _get_schema_name(request)

    logger.info(
        f"Push request: user={request.user.email}, "
        f"schema={schema_name}, "
        f"tables={list(changes.keys())}"
    )

    accepted = {}
    rejected = {}
    conflicts = {}

    for table_name, table_changes in changes.items():
        handler = PUSH_HANDLERS.get(table_name)
        if not handler:
            logger.warning(f"Push: unknown table '{table_name}' — skipping")
            continue

        try:
            table_accepted, table_rejected, table_conflicts = handler(
                table_changes, request.user, schema_name
            )
            if table_accepted:
                accepted[table_name] = table_accepted
            if table_rejected:
                rejected[table_name] = table_rejected
            if table_conflicts:
                conflicts[table_name] = table_conflicts
        except Exception as e:
            logger.error(f"Push handler error for '{table_name}': {e}", exc_info=True)
            all_sync_ids = (
                [r.get("sync_id") for r in table_changes.get("created", [])]
                + [r.get("sync_id") for r in table_changes.get("updated", [])]
                + table_changes.get("deleted", [])
            )
            rejected[table_name] = [
                {"sync_id": sid, "error": str(e)} for sid in all_sync_ids if sid
            ]

    total_accepted = sum(len(v) for v in accepted.values())
    total_rejected = sum(len(v) for v in rejected.values())
    logger.info(f"Push complete: accepted={total_accepted}, rejected={total_rejected}")

    return Response({
        "accepted": accepted,
        "rejected": rejected,
        "conflicts": conflicts,
    })


# ─────────────────────────────────────────────────────────────────────────────
# Per-table push handlers
# ─────────────────────────────────────────────────────────────────────────────

def _push_customers(changes, user, schema_name):
    from customers.models import Customer

    accepted, rejected, conflicts = [], [], []

    records = (changes.get("created", []) + changes.get("updated", []))[:MAX_RECORDS_PER_TABLE]

    # One outer transaction for the entire table batch.
    # Per-record savepoints provide isolation so a failure on record N
    # does not roll back the records before it.
    with transaction.atomic():
        for record in records:
            sync_id = parse_sync_id(record.get("sync_id"))
            if not sync_id:
                rejected.append({"sync_id": None, "error": "Missing sync_id"})
                continue
            sid = transaction.savepoint()
            try:
                obj, created = Customer.objects.get_or_create(
                    sync_id=sync_id,
                    defaults=_customer_defaults(record),
                )
                if not created:
                    _apply_customer(obj, record)
                    obj.save()
                transaction.savepoint_commit(sid)
                accepted.append(sync_id)
            except Exception as e:
                transaction.savepoint_rollback(sid)
                logger.warning(f"Customer push error {sync_id}: {e}")
                rejected.append({"sync_id": sync_id, "error": str(e)[:200]})

    for sync_id in changes.get("deleted", []):
        sid = parse_sync_id(sync_id)
        if not sid:
            continue
        try:
            Customer.objects.filter(sync_id=sid).update(is_active=False)
            accepted.append(sid)
        except Exception as e:
            rejected.append({"sync_id": sid, "error": str(e)[:200]})

    return accepted, rejected, conflicts


def _push_sales(changes, user, schema_name):
    from sales.models import Sale
    from stores.models import Store
    from customers.models import Customer

    accepted, rejected, conflicts = [], [], []
    records = (changes.get("created", []) + changes.get("updated", []))[:MAX_RECORDS_PER_TABLE]

    # Pre-resolve all FK objects in bulk — one query per FK model
    # instead of one query per record per FK field.
    store_map    = bulk_resolve_fk(Store,    [r.get("store_id")    for r in records])
    customer_map = bulk_resolve_fk(Customer, [r.get("customer_id") for r in records])

    with transaction.atomic():
        for record in records:
            sync_id = parse_sync_id(record.get("sync_id"))
            if not sync_id:
                rejected.append({"sync_id": None, "error": "Missing sync_id"})
                continue
            sid = transaction.savepoint()
            try:
                store    = store_map.get(str(record.get("store_id", "")))
                customer = customer_map.get(str(record.get("customer_id", "")))

                obj, created = Sale.objects.get_or_create(
                    sync_id=sync_id,
                    defaults=_sale_defaults(record, store, customer, user),
                )
                if not created:
                    _apply_sale(obj, record, store, customer)
                    obj.save()
                transaction.savepoint_commit(sid)
                accepted.append(sync_id)
            except IntegrityError as e:
                transaction.savepoint_rollback(sid)
                logger.warning(f"Sale push IntegrityError {sync_id}: {e}")
                rejected.append({"sync_id": sync_id, "error": "Duplicate document number"})
            except Exception as e:
                transaction.savepoint_rollback(sid)
                logger.warning(f"Sale push error {sync_id}: {e}")
                rejected.append({"sync_id": sync_id, "error": str(e)[:200]})

    for sync_id in changes.get("deleted", []):
        sid = parse_sync_id(sync_id)
        if not sid:
            continue
        try:
            Sale.objects.filter(sync_id=sid).update(status="CANCELLED")
            accepted.append(sid)
        except Exception as e:
            rejected.append({"sync_id": sid, "error": str(e)[:200]})

    return accepted, rejected, conflicts


def _push_sale_items(changes, user, schema_name):
    """
    SaleItems are child records — pushed alongside sales.

    Field mapping (desktop → server):
      subtotal           → total_price  (server field name)
      discount_percentage → discount    (server field name)
      total              → NOT written  (line_total is a computed property)
    """
    try:
        from sales.models import SaleItem, Sale
        from inventory.models import Product
    except ImportError:
        return [], [], []

    accepted, rejected, conflicts = [], [], []
    records = (changes.get("created", []) + changes.get("updated", []))[:MAX_RECORDS_PER_TABLE]

    # Bulk-resolve both FK models in 2 queries instead of 2 per record
    sale_map    = bulk_resolve_fk(Sale,    [r.get("sale_id")    for r in records])
    product_map = bulk_resolve_fk(Product, [r.get("product_id") for r in records])

    with transaction.atomic():
        for record in records:
            sync_id = parse_sync_id(record.get("sync_id"))
            if not sync_id:
                rejected.append({"sync_id": None, "error": "Missing sync_id"})
                continue

            sale    = sale_map.get(str(record.get("sale_id", "")))
            product = product_map.get(str(record.get("product_id", "")))

            if not sale:
                rejected.append({"sync_id": sync_id, "error": "Parent sale not found"})
                continue

            sid = transaction.savepoint()
            try:
                defaults = {
                    "sale":        sale,
                    "product":     product,
                    "quantity":    int(_d(record.get("quantity", 1))),
                    "unit_price":  _d(record.get("unit_price", 0)),
                    "discount":    _d(record.get("discount_percentage", 0)),
                    "tax_rate":    record.get("tax_rate", "A") or "A",
                    "tax_amount":  _d(record.get("tax_amount", 0)),
                    "total_price": _d(record.get("subtotal", 0)),
                }
                obj, created = SaleItem.objects.get_or_create(
                    sync_id=sync_id, defaults=defaults
                )
                if not created:
                    for k, v in defaults.items():
                        setattr(obj, k, v)
                    obj._skip_deduction   = True
                    obj._skip_sale_update = True
                    obj.save()
                transaction.savepoint_commit(sid)
                accepted.append(sync_id)
            except Exception as e:
                transaction.savepoint_rollback(sid)
                logger.warning(f"SaleItem push error {sync_id}: {e}")
                rejected.append({"sync_id": sync_id, "error": str(e)[:200]})

    return accepted, rejected, conflicts


def _push_expenses(changes, user, schema_name):
    """
    Push expenses from desktop.

    Field mapping (desktop → server):
      title          → description  (server's main field)
      description    → notes        (secondary text)
      expense_date   → date         (DateField, not DateTimeField)
      payment_method → uppercased   (server stores CASH, CREDIT_CARD etc.)
      store_id       → IGNORED      (Expense has no store FK on server)
      created_by_id  → user         (server uses user FK not created_by)
    """
    try:
        from expenses.models import Expense
    except ImportError:
        return [], [], []

    accepted, rejected, conflicts = [], [], []
    records = (changes.get("created", []) + changes.get("updated", []))[:MAX_RECORDS_PER_TABLE]

    _VALID_PMS = {"CASH", "CREDIT_CARD", "DEBIT_CARD", "BANK_TRANSFER", "DIGITAL_WALLET", "OTHER"}
    _PM_MAP    = {"MOBILE_MONEY": "DIGITAL_WALLET", "CARD": "CREDIT_CARD"}

    with transaction.atomic():
        for record in records:
            sync_id = parse_sync_id(record.get("sync_id"))
            if not sync_id:
                rejected.append({"sync_id": None, "error": "Missing sync_id"})
                continue
            sid = transaction.savepoint()
            try:
                expense_dt   = unix_to_dt(record.get("expense_date"))
                expense_date = expense_dt.date() if expense_dt else dj_timezone.now().date()

                raw_pm         = (record.get("payment_method", "cash") or "cash").upper()
                payment_method = _PM_MAP.get(raw_pm, raw_pm)
                if payment_method not in _VALID_PMS:
                    payment_method = "OTHER"

                defaults = {
                    "description":    record.get("title", "") or record.get("description", ""),
                    "notes":          record.get("notes", "") or record.get("description", ""),
                    "amount":         _d(record.get("amount", 0)),
                    "date":           expense_date,
                    "payment_method": payment_method,
                    "user":           user,
                }
                obj, created = Expense.objects.get_or_create(
                    sync_id=sync_id, defaults=defaults
                )
                if not created:
                    for k, v in defaults.items():
                        setattr(obj, k, v)
                    obj.save()
                transaction.savepoint_commit(sid)
                accepted.append(sync_id)
            except Exception as e:
                transaction.savepoint_rollback(sid)
                logger.warning(f"Expense push error {sync_id}: {e}")
                rejected.append({"sync_id": sync_id, "error": str(e)[:200]})

    for sync_id in changes.get("deleted", []):
        sid = parse_sync_id(sync_id)
        if not sid:
            continue
        # Expense has no status field — soft delete not supported, accept silently
        accepted.append(sid)

    return accepted, rejected, conflicts


def _push_categories(changes, user, schema_name):
    from inventory.models import Category

    accepted, rejected, conflicts = [], [], []
    records = (changes.get("created", []) + changes.get("updated", []))[:MAX_RECORDS_PER_TABLE]

    # Collect conflict serializations after the transaction to avoid
    # nested serializer DB calls inside the write transaction.
    conflict_objs = []

    with transaction.atomic():
        for record in records:
            sync_id = parse_sync_id(record.get("sync_id"))
            if not sync_id:
                rejected.append({"sync_id": None, "error": "Missing sync_id"})
                continue
            sid = transaction.savepoint()
            try:
                obj, created = Category.objects.get_or_create(
                    sync_id=sync_id,
                    defaults={
                        "name":          record.get("name", ""),
                        "code":          record.get("code", "") or None,
                        "description":   record.get("description", ""),
                        "category_type": record.get("category_type", "product"),
                        "is_active":     safe_bool(record.get("is_active", True)),
                    }
                )
                transaction.savepoint_commit(sid)
                if not created:
                    conflict_objs.append(obj)
                else:
                    accepted.append(sync_id)
            except Exception as e:
                transaction.savepoint_rollback(sid)
                rejected.append({"sync_id": sync_id, "error": str(e)[:200]})

    # Serialize conflicts outside the write transaction
    from .serializers import serialize_category
    for obj in conflict_objs:
        conflicts.append(serialize_category(obj, schema_name))

    return accepted, rejected, conflicts


def _push_suppliers(changes, user, schema_name):
    from inventory.models import Supplier

    accepted, rejected, conflicts = [], [], []
    records      = (changes.get("created", []) + changes.get("updated", []))[:MAX_RECORDS_PER_TABLE]
    conflict_objs = []

    with transaction.atomic():
        for record in records:
            sync_id = parse_sync_id(record.get("sync_id"))
            if not sync_id:
                rejected.append({"sync_id": None, "error": "Missing sync_id"})
                continue
            sid = transaction.savepoint()
            try:
                obj, created = Supplier.objects.get_or_create(
                    sync_id=sync_id,
                    defaults={
                        "name":           record.get("name", ""),
                        "tin":            record.get("tin", "") or None,
                        "contact_person": record.get("contact_person", ""),
                        "phone":          record.get("phone", ""),
                        "email":          record.get("email", ""),
                        "address":        record.get("address", ""),
                        "country":        record.get("country", "Uganda"),
                        "is_active":      safe_bool(record.get("is_active", True)),
                    }
                )
                transaction.savepoint_commit(sid)
                if not created:
                    conflict_objs.append(obj)
                else:
                    accepted.append(sync_id)
            except Exception as e:
                transaction.savepoint_rollback(sid)
                rejected.append({"sync_id": sync_id, "error": str(e)[:200]})

    from .serializers import serialize_supplier
    for obj in conflict_objs:
        conflicts.append(serialize_supplier(obj, schema_name))

    return accepted, rejected, conflicts


def _push_products(changes, user, schema_name):
    from inventory.models import Product, Category, Supplier

    accepted, rejected, conflicts = [], [], []
    records       = (changes.get("created", []) + changes.get("updated", []))[:MAX_RECORDS_PER_TABLE]
    conflict_objs = []

    # Bulk-resolve category and supplier FKs — 2 queries for the whole batch
    category_map = bulk_resolve_fk(Category, [r.get("category_id") for r in records])
    supplier_map = bulk_resolve_fk(Supplier, [r.get("supplier_id") for r in records])

    with transaction.atomic():
        for record in records:
            sync_id = parse_sync_id(record.get("sync_id"))
            if not sync_id:
                rejected.append({"sync_id": None, "error": "Missing sync_id"})
                continue
            sid = transaction.savepoint()
            try:
                category = category_map.get(str(record.get("category_id", "")))
                supplier = supplier_map.get(str(record.get("supplier_id", "")))

                obj, created = Product.objects.get_or_create(
                    sync_id=sync_id,
                    defaults={
                        "name":                record.get("name", ""),
                        "sku":                 record.get("sku", ""),
                        "barcode":             record.get("barcode") or None,
                        "description":         record.get("description", ""),
                        "selling_price":       _d(record.get("selling_price", 0)),
                        "cost_price":          _d(record.get("cost_price", 0)),
                        "discount_percentage": _d(record.get("discount_percentage", 0)),
                        "tax_rate":            record.get("tax_rate", "A") or "A",
                        "unit_of_measure":     record.get("unit_of_measure", "103") or "103",
                        "min_stock_level":     safe_int(record.get("min_stock_level"), 5),
                        "is_active":           safe_bool(record.get("is_active", True)),
                        "category":            category,
                        "supplier":            supplier,
                    }
                )
                transaction.savepoint_commit(sid)
                if not created:
                    conflict_objs.append(obj)
                else:
                    accepted.append(sync_id)
            except IntegrityError:
                transaction.savepoint_rollback(sid)
                rejected.append({"sync_id": sync_id, "error": "SKU already exists"})
            except Exception as e:
                transaction.savepoint_rollback(sid)
                rejected.append({"sync_id": sync_id, "error": str(e)[:200]})

    from .serializers import serialize_product
    for obj in conflict_objs:
        conflicts.append(serialize_product(obj, schema_name))

    return accepted, rejected, conflicts


def _push_stock(changes, user, schema_name):
    """
    Stock adjustments from desktop.
    Desktop wins — it's the physical point of truth.
    """
    from inventory.models import Stock, Product
    from stores.models import Store

    accepted, rejected, conflicts = [], [], []
    records = (changes.get("created", []) + changes.get("updated", []))[:MAX_RECORDS_PER_TABLE]

    # Bulk-resolve FK models — 2 queries for the whole batch
    product_map = bulk_resolve_fk(Product, [r.get("product_id") for r in records])
    store_map   = bulk_resolve_fk(Store,   [r.get("store_id")   for r in records])

    with transaction.atomic():
        for record in records:
            sync_id = parse_sync_id(record.get("sync_id"))
            if not sync_id:
                rejected.append({"sync_id": None, "error": "Missing sync_id"})
                continue
            sid = transaction.savepoint()
            try:
                product = product_map.get(str(record.get("product_id", "")))
                store   = store_map.get(str(record.get("store_id", "")))

                defaults = {
                    "product":             product,
                    "store":               store,
                    "quantity":            _d(record.get("quantity", 0)),
                    "low_stock_threshold": _d(record.get("low_stock_threshold", 5)),
                    "reorder_quantity":    _d(record.get("reorder_quantity", 10)),
                }
                obj, created = Stock.objects.get_or_create(
                    sync_id=sync_id, defaults=defaults
                )
                if not created:
                    for k, v in defaults.items():
                        setattr(obj, k, v)
                    obj.save()
                transaction.savepoint_commit(sid)
                accepted.append(sync_id)
            except Exception as e:
                transaction.savepoint_rollback(sid)
                rejected.append({"sync_id": sync_id, "error": str(e)[:200]})

    return accepted, rejected, conflicts


def _push_stock_movements(changes, user, schema_name):
    from inventory.models import StockMovement, Product
    from stores.models import Store

    accepted, rejected, conflicts = [], [], []
    records       = (changes.get("created", []) + changes.get("updated", []))[:MAX_RECORDS_PER_TABLE]
    conflict_objs = []

    # Bulk-resolve FK models — 2 queries for the whole batch
    product_map = bulk_resolve_fk(Product, [r.get("product_id") for r in records])
    store_map   = bulk_resolve_fk(Store,   [r.get("store_id")   for r in records])

    with transaction.atomic():
        for record in records:
            sync_id = parse_sync_id(record.get("sync_id"))
            if not sync_id:
                rejected.append({"sync_id": None, "error": "Missing sync_id"})
                continue
            sid = transaction.savepoint()
            try:
                product = product_map.get(str(record.get("product_id", "")))
                store   = store_map.get(str(record.get("store_id", "")))

                defaults = {
                    "product":       product,
                    "store":         store,
                    "movement_type": record.get("movement_type", "adjustment"),
                    "quantity":      _d(record.get("quantity", 0)),
                    "reference":     record.get("reference", "") or None,
                    "notes":         record.get("notes", "") or None,
                    "unit_price":    _d(record.get("unit_price")) if record.get("unit_price") else None,
                    "total_value":   _d(record.get("total_value")) if record.get("total_value") else None,
                    "created_by":    user,
                }
                obj, created = StockMovement.objects.get_or_create(
                    sync_id=sync_id, defaults=defaults
                )
                transaction.savepoint_commit(sid)
                if not created:
                    # Movements are append-only — send conflict back
                    conflict_objs.append(obj)
                else:
                    accepted.append(sync_id)
            except Exception as e:
                transaction.savepoint_rollback(sid)
                rejected.append({"sync_id": sync_id, "error": str(e)[:200]})

    # Serialize conflicts outside the write transaction
    from .serializers import serialize_stock_movement
    for obj in conflict_objs:
        conflicts.append(serialize_stock_movement(obj, schema_name))

    return accepted, rejected, conflicts


PUSH_HANDLERS = {
    "customers":       _push_customers,
    "sales":           _push_sales,
    "sale_items":      _push_sale_items,
    "expenses":        _push_expenses,
    "categories":      _push_categories,
    "suppliers":       _push_suppliers,
    "products":        _push_products,
    "stock":           _push_stock,
    "stock_movements": _push_stock_movements,
}


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _resolve_fk(model_class, sync_id_value):
    """Look up a model instance by its sync_id. Returns None if not found."""
    if not sync_id_value:
        return None
    sid = parse_sync_id(sync_id_value)
    if not sid:
        return None
    try:
        return model_class.objects.get(sync_id=sid)
    except model_class.DoesNotExist:
        logger.debug(f"FK not found: {model_class.__name__} sync_id={sid}")
        return None


def _d(value) -> Decimal:
    """Safe Decimal conversion for Django model fields."""
    if value is None or value == "":
        return Decimal("0")
    try:
        return Decimal(str(value))
    except (InvalidOperation, TypeError):
        return Decimal("0")

def _customer_defaults(record: dict) -> dict:
    return {
        "name":           record.get("name", ""),
        "email":          record.get("email", "") or "",
        "phone":          record.get("phone", "") or "",
        # desktop sends address, server field is physical_address
        "physical_address": record.get("address", "") or "",
        "tin":            record.get("tin", "") or None,
        "is_active":      safe_bool(record.get("is_active", True)),
        "credit_limit":   _d(record.get("credit_limit", 0)),
        # desktop sends current_balance, server field is credit_balance
        "credit_balance": _d(record.get("current_balance", 0)),
    }


def _apply_customer(obj, record: dict):
    obj.name             = record.get("name", obj.name)
    obj.email            = record.get("email", obj.email) or ""
    obj.phone            = record.get("phone", obj.phone) or ""
    obj.physical_address = record.get("address", obj.physical_address) or ""
    obj.tin              = record.get("tin") or obj.tin
    obj.is_active        = safe_bool(record.get("is_active", obj.is_active))
    obj.credit_limit     = _d(record.get("credit_limit", obj.credit_limit))
    obj.credit_balance   = _d(record.get("current_balance", obj.credit_balance))

def _sale_defaults(record: dict, store, customer, user) -> dict:
    """
    Build defaults dict for Sale.objects.get_or_create().

    Notes:
      - status, payment_method, payment_status must be UPPERCASE (server choices)
      - amount_paid is a @property on Sale (from payments relation) — not a DB field
      - change_amount does not exist on the server Sale model — omitted
    """
    return {
        "document_number": record.get("document_number") or f"DESK-{str(record.get('sync_id', ''))[:8]}",
        "store":           store,
        "customer":        customer,
        "created_by":      user,
        "subtotal":        _d(record.get("subtotal", 0)),
        "tax_amount":      _d(record.get("tax_amount", 0)),
        "discount_amount": _d(record.get("discount_amount", 0)),
        "total_amount":    _d(record.get("total_amount", 0)),
        # status/payment values come lowercased from desktop — uppercase for server
        "status":          (record.get("status", "completed") or "completed").upper(),
        "payment_method":  (record.get("payment_method", "cash") or "cash").upper(),
        "payment_status":  (record.get("payment_status", "paid") or "paid").upper(),
        "notes":           record.get("notes", "") or "",
    }


def _apply_sale(obj, record: dict, store, customer):
    """
    Apply desktop record values to an existing Sale instance.
    Desktop wins for all sale fields.
    """
    if store:
        obj.store = store
    if customer is not None:
        obj.customer = customer
    obj.subtotal        = _d(record.get("subtotal", obj.subtotal))
    obj.tax_amount      = _d(record.get("tax_amount", obj.tax_amount))
    obj.discount_amount = _d(record.get("discount_amount", obj.discount_amount))
    obj.total_amount    = _d(record.get("total_amount", obj.total_amount))
    obj.status          = (record.get("status", obj.status) or obj.status).upper()
    obj.payment_method  = (record.get("payment_method", obj.payment_method) or obj.payment_method).upper()
    obj.payment_status  = (record.get("payment_status", getattr(obj, "payment_status", "PAID")) or "PAID").upper()
    obj.notes           = record.get("notes", obj.notes) or ""


def _get_schema_name(request) -> str:
    if hasattr(request, "tenant"):
        return request.tenant.schema_name
    return getattr(request, "schema_name", "")