# Generated by Django 5.0.6 on 2026-04-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='fcm_token',
            field=models.TextField(blank=True, default='', unique=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.TextField(blank=True, default='', unique=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.TextField(blank=True, default=''),
        ),
    ]
