# Generated by Django 5.0.6 on 2026-04-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0002_pushsubscription_fcm_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.TextField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='fcm_token',
            field=models.TextField(blank=True, default=None, null=True, unique=True),
        ),
    ]
