# Generated by Django 5.0.6 on 2026-03-17 02:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords to improve search matching.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['sort_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SupportWidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_message', models.CharField(default='👋 Hi there! How can we help you today?', max_length=255)),
                ('widget_title', models.CharField(default='Support', max_length=100)),
                ('brand_color', models.CharField(default='#6366f1', help_text='Hex colour, e.g. #6366f1', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='support_widget/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('business_hours_message', models.CharField(blank=True, default="Our agents are currently offline. Leave a message and we'll reply shortly.", max_length=255)),
                ('offline_email', models.EmailField(blank=True, help_text='Fallback email for offline messages.', max_length=254)),
                ('call_recording_notice', models.TextField(default='⚠️ This call is recorded for quality and training purposes. By continuing you consent to the recording.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support Widget Config',
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='support_widget/avatars/')),
                ('status', models.CharField(choices=[('online', 'Online'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('accept_calls', models.BooleanField(default=True, help_text='Allow incoming WebRTC calls.')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Profile',
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_room_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ringing', 'Ringing'), ('active', 'Active'), ('ended', 'Ended'), ('missed', 'Missed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_secs', models.PositiveIntegerField(default=0)),
                ('recording_consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support_widget/recordings/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Bytes')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='support_widget.callsession')),
            ],
            options={
                'verbose_name': 'Call Recording',
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visitor_name', models.CharField(blank=True, max_length=150)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('faq', 'FAQ'), ('chatting', 'Chatting'), ('escalated', 'Escalated'), ('in_call', 'In Call'), ('resolved', 'Resolved')], default='onboarding', max_length=20)),
                ('referrer_url', models.URLField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor Session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('visitor', 'Visitor'), ('agent', 'Agent'), ('bot', 'Bot'), ('system', 'System')], max_length=10)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_widget.visitorsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='callsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='support_widget.visitorsession'),
        ),
    ]
