# Generated by Django 5.0.6 on 2026-02-11 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_efrishscode'),
        ('efris', '0002_productuploadtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_invoice_no', models.CharField(help_text='Original invoice FDN', max_length=50)),
                ('original_invoice_id', models.CharField(blank=True, help_text='Original invoice EFRIS ID', max_length=50)),
                ('reference_no', models.CharField(help_text='EFRIS credit note reference number', max_length=50, unique=True)),
                ('reason_code', models.CharField(help_text='Credit note reason code (101-105)', max_length=3)),
                ('reason', models.TextField(blank=True, help_text='Detailed reason if code is 105')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('application_data', models.JSONField(default=dict, help_text='Complete T110 request data')),
                ('response_data', models.JSONField(default=dict, help_text='EFRIS response data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_applications', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='efris_credi_company_a7a0ac_idx'), models.Index(fields=['original_invoice_no'], name='efris_credi_origina_6eb7eb_idx'), models.Index(fields=['reference_no'], name='efris_credi_referen_efe179_idx')],
            },
        ),
    ]
