# Generated by Django 5.0.6 on 2026-02-20 07:30

import uuid
from django.db import migrations, models


def populate_sync_ids(apps, schema_editor):
    models_to_update = [
        ('efris', 'CreditNoteApplication'),
        ('efris', 'EFRISApiLog'),
        ('efris', 'EFRISCommodityCategorry'),
        ('efris', 'EFRISConfiguration'),
        ('efris', 'EFRISDeviceInfo'),
        ('efris', 'EFRISDigitalKey'),
        ('efris', 'EFRISErrorPattern'),
        ('efris', 'EFRISExceptionLog'),
        ('efris', 'EFRISFiscalizationBatch'),
        ('efris', 'EFRISIntegrationSettings'),
        ('efris', 'EFRISNotification'),
        ('efris', 'EFRISOperationMetrics'),
        ('efris', 'EFRISSyncQueue'),
        ('efris', 'EFRISSystemDictionary'),
        ('efris', 'FiscalizationAudit'),
        ('efris', 'ProductUploadTask'),
    ]
    for app_label, model_name in models_to_update:
        try:
            Model = apps.get_model(app_label, model_name)
            for obj in Model.objects.filter(sync_id__isnull=True):
                obj.sync_id = uuid.uuid4()
                obj.save(update_fields=['sync_id'])
        except Exception as e:
            print(f"Skipping {app_label}.{model_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('efris', '0003_creditnoteapplication'),
    ]

    operations = [
        # STEP 1: Add columns without unique constraint
        migrations.AddField(
            model_name='creditnoteapplication',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efrisapilog',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efriscommoditycategorry',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efrisconfiguration',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efrisdeviceinfo',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efrisdigitalkey',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efriserrorpattern',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efrisexceptionlog',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efrisfiscalizationbatch',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efrisintegrationsettings',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efrisnotification',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efrisoperationmetrics',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efrissyncqueue',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='efrissystemdictionary',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='fiscalizationaudit',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='productuploadtask',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),

        # STEP 2: Populate unique UUIDs for all existing rows per tenant
        migrations.RunPython(
            populate_sync_ids,
            migrations.RunPython.noop,
        ),

        # STEP 3: Now safe to add unique constraint
        migrations.AlterField(
            model_name='creditnoteapplication',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efrisapilog',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efriscommoditycategorry',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efrisconfiguration',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efrisdeviceinfo',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efrisdigitalkey',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efriserrorpattern',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efrisexceptionlog',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efrisfiscalizationbatch',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efrisintegrationsettings',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efrisnotification',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efrisoperationmetrics',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efrissyncqueue',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='efrissystemdictionary',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='fiscalizationaudit',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='productuploadtask',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]