# Generated by Django 5.0.6 on 2026-03-15 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_profile', models.BooleanField(default=False)),
                ('first_product', models.BooleanField(default=False)),
                ('invite_user', models.BooleanField(default=False)),
                ('first_invoice', models.BooleanField(default=False)),
                ('efris_config', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed', models.BooleanField(default=False, help_text='User permanently dismissed onboarding.')),
                ('welcome_seen', models.BooleanField(default=False, help_text='Welcome modal has been shown.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Progress',
                'verbose_name_plural': 'Onboarding Progress',
            },
        ),
    ]
