# Generated by Django 5.2.4 on 2025-11-08 04:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Store Name')),
                ('code', models.CharField(blank=True, help_text='Internal identifier for the store', max_length=20, null=True, unique=True, verbose_name='Store Code')),
                ('store_type', models.CharField(choices=[('MAIN', 'Main Store'), ('BRANCH', 'Branch Store'), ('WAREHOUSE', 'Warehouse'), ('OUTLET', 'Retail Outlet')], default='BRANCH', max_length=20, verbose_name='Store Type')),
                ('nin', models.CharField(blank=True, help_text='National Identification Number', max_length=20, null=True, verbose_name='NIN')),
                ('tin', models.CharField(blank=True, help_text='Tax Identification Number', max_length=20, null=True, verbose_name='TIN')),
                ('is_main_branch', models.BooleanField(default=False, help_text='Designates this as the primary store for the company', verbose_name='Main Branch/Store')),
                ('allows_sales', models.BooleanField(default=True, verbose_name='Allows Sales')),
                ('allows_inventory', models.BooleanField(default=True, verbose_name='Manages Inventory')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Store Manager')),
                ('manager_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]+$', 'Enter a valid phone number.')], verbose_name='Manager Phone')),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='Operating hours for each day of the week')),
                ('timezone', models.CharField(blank=True, default='Africa/Kampala', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Used for ordering stores in lists')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location/Area')),
                ('physical_address', models.TextField(verbose_name='Physical Address')),
                ('location_gps', models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Coordinates')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region/District')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9]+$', 'Enter a valid phone number.')], verbose_name='Primary Phone')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9]+$', 'Enter a valid phone number.')], verbose_name='Secondary Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Store Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store-logos/', verbose_name='Store Logo')),
                ('efris_device_number', models.CharField(blank=True, help_text='Device number assigned by URA', max_length=50, null=True, verbose_name='EFRIS Device Number')),
                ('device_serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Device Serial Number')),
                ('efris_enabled', models.BooleanField(default=False, verbose_name='EFRIS Enabled')),
                ('is_registered_with_efris', models.BooleanField(default=False, verbose_name='Registered with EFRIS')),
                ('efris_registration_date', models.DateTimeField(blank=True, null=True, verbose_name='EFRIS Registration Date')),
                ('efris_last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last EFRIS Sync')),
                ('last_stock_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Stock Sync')),
                ('auto_fiscalize_sales', models.BooleanField(default=True, verbose_name='Auto-Fiscalize Sales')),
                ('allow_manual_fiscalization', models.BooleanField(default=True, verbose_name='Allow Manual Fiscalization')),
                ('report_stock_movements', models.BooleanField(default=True, verbose_name='Report Stock Movements to EFRIS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='company.company', verbose_name='Company')),
                ('staff', models.ManyToManyField(blank=True, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['-is_main_branch', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('device_number', models.CharField(help_text='Device identifier (URA assigned for fiscal devices)', max_length=50, unique=True, verbose_name='Device Number')),
                ('device_type', models.CharField(choices=[('POS', 'Point of Sale'), ('INVOICE', 'Invoice Printer'), ('SCANNER', 'Barcode Scanner'), ('EFRIS_FISCAL', 'EFRIS Fiscal Device'), ('OTHER', 'Other Device')], default='POS', max_length=20, verbose_name='Device Type')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial Number')),
                ('mac_address', models.CharField(blank=True, help_text='Hardware MAC address for dedicated terminals', max_length=17, null=True, verbose_name='MAC Address')),
                ('hardware_id', models.CharField(blank=True, help_text='Unique hardware identifier', max_length=100, null=True, verbose_name='Hardware ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_efris_linked', models.BooleanField(default=False, help_text='Is this device linked to EFRIS system', verbose_name='EFRIS Linked')),
                ('require_approval', models.BooleanField(default=True, help_text='Require admin approval before use', verbose_name='Require Approval')),
                ('max_concurrent_users', models.PositiveIntegerField(default=3, help_text='Maximum number of users that can use this device simultaneously', verbose_name='Max Concurrent Users')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('last_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='Last Maintenance')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time this device was used', null=True, verbose_name='Last Seen')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='stores.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Store Device',
                'verbose_name_plural': 'Store Devices',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreOperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('opening_time', models.TimeField(verbose_name='Opening Time')),
                ('closing_time', models.TimeField(verbose_name='Closing Time')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed All Day')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours_detailed', to='stores.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Operating Hour',
                'verbose_name_plural': 'Operating Hours',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='UserDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='Session Key')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('LOGGED_OUT', 'Logged Out'), ('FORCE_CLOSED', 'Force Closed'), ('SUSPICIOUS', 'Suspicious')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('device_fingerprint', models.CharField(db_index=True, help_text='Unique hash identifying this device', max_length=64, verbose_name='Device Fingerprint')),
                ('browser_name', models.CharField(blank=True, max_length=50, verbose_name='Browser Name')),
                ('browser_version', models.CharField(blank=True, max_length=20, verbose_name='Browser Version')),
                ('os_name', models.CharField(blank=True, max_length=50, verbose_name='OS Name')),
                ('os_version', models.CharField(blank=True, max_length=20, verbose_name='OS Version')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent String')),
                ('screen_resolution', models.CharField(blank=True, help_text='Format: 1920x1080', max_length=20, verbose_name='Screen Resolution')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('location_accuracy', models.FloatField(blank=True, null=True, verbose_name='Location Accuracy (meters)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Login Time')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('logged_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Logout Time')),
                ('is_new_device', models.BooleanField(default=False, help_text='First time user logged in from this device', verbose_name='New Device')),
                ('is_suspicious', models.BooleanField(default=False, help_text='Flagged for suspicious activity', verbose_name='Suspicious Activity')),
                ('suspicious_reason', models.TextField(blank=True, verbose_name='Suspicious Reason')),
                ('security_alerts_count', models.PositiveIntegerField(default=0, verbose_name='Security Alerts Count')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Additional Metadata')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='stores.store', verbose_name='Store')),
                ('store_device', models.ForeignKey(blank=True, help_text='Physical POS device if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_sessions', to='stores.storedevice', verbose_name='Store Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Device Session',
                'verbose_name_plural': 'User Device Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('NEW_DEVICE', 'New Device Login'), ('NEW_LOCATION', 'New Location Login'), ('MULTIPLE_FAILED_LOGINS', 'Multiple Failed Login Attempts'), ('CONCURRENT_SESSIONS_EXCEEDED', 'Too Many Concurrent Sessions'), ('UNUSUAL_ACTIVITY', 'Unusual Activity Pattern'), ('IP_CHANGE', 'IP Address Changed During Session'), ('SUSPICIOUS_TRANSACTION', 'Suspicious Transaction'), ('DEVICE_CAPACITY_EXCEEDED', 'Device Capacity Exceeded'), ('OTHER', 'Other Security Concern')], max_length=50, verbose_name='Alert Type')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20, verbose_name='Severity')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('IGNORED', 'Ignored')], default='OPEN', max_length=20, verbose_name='Status')),
                ('title', models.CharField(max_length=200, verbose_name='Alert Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('alert_data', models.JSONField(default=dict, help_text='Additional data related to the alert', verbose_name='Alert Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Notes')),
                ('notified', models.BooleanField(default=False, verbose_name='Admin Notified')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notified At')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to='stores.store', verbose_name='Store')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to='stores.storedevice', verbose_name='Device')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to='stores.userdevicesession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Security Alert',
                'verbose_name_plural': 'Security Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceOperatorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Device Login'), ('LOGOUT', 'Device Logout'), ('SALE', 'Sale Transaction'), ('REFUND', 'Refund Transaction'), ('FISCALIZE', 'Manual Fiscalization'), ('STOCK_UPDATE', 'Stock Update'), ('EFRIS_SYNC', 'EFRIS Synchronization'), ('MAINTENANCE', 'Device Maintenance'), ('SESSION_EXTENDED', 'Session Extended'), ('SESSION_TERMINATED', 'Session Terminated'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity Detected'), ('ERROR', 'Error Occurred'), ('OTHER', 'Other Action')], max_length=50, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('details', models.JSONField(default=dict, help_text='Additional action details in JSON format', verbose_name='Details')),
                ('is_efris_related', models.BooleanField(default=False, help_text='Whether this action is related to EFRIS operations', verbose_name='EFRIS Related')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful', verbose_name='Success')),
                ('error_message', models.TextField(blank=True, help_text='Error details if action failed', verbose_name='Error Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logs', to='stores.store', verbose_name='Store')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_logs', to='stores.storedevice', verbose_name='Device')),
                ('session', models.ForeignKey(blank=True, help_text='Associated device session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='stores.userdevicesession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Device Operator Log',
                'verbose_name_plural': 'Device Operator Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64, verbose_name='Fingerprint Hash')),
                ('device_name', models.CharField(help_text='User-friendly device name', max_length=100, verbose_name='Device Name')),
                ('browser_name', models.CharField(blank=True, max_length=50)),
                ('os_name', models.CharField(blank=True, max_length=50)),
                ('is_trusted', models.BooleanField(default=False, verbose_name='Trusted Device')),
                ('trust_score', models.IntegerField(default=0, help_text='Higher score = more trusted (0-100)', verbose_name='Trust Score')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='First Seen')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Last Seen')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Login Count')),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last IP Address')),
                ('last_location', models.CharField(blank=True, max_length=200, verbose_name='Last Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_devices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Device Fingerprint',
                'verbose_name_plural': 'Device Fingerprints',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='stores_devi_user_id_0f318d_idx'), models.Index(fields=['fingerprint_hash'], name='stores_devi_fingerp_293540_idx'), models.Index(fields=['is_trusted'], name='stores_devi_is_trus_2a5a0d_idx')],
                'unique_together': {('user', 'fingerprint_hash')},
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['company', 'is_active'], name='stores_stor_company_58eccd_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_main_branch'], name='stores_stor_is_main_46003d_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['company', 'store_type'], name='stores_stor_company_1410e7_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['latitude', 'longitude'], name='stores_stor_latitud_161be0_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['region'], name='stores_stor_region_ca19e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_store_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(condition=models.Q(('efris_device_number__isnull', False)), fields=('efris_device_number',), name='unique_efris_device_number'),
        ),
        migrations.AddIndex(
            model_name='storedevice',
            index=models.Index(fields=['store', 'is_active'], name='stores_stor_store_i_b9bdc7_idx'),
        ),
        migrations.AddIndex(
            model_name='storedevice',
            index=models.Index(fields=['device_type', 'is_active'], name='stores_stor_device__52b6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='storedevice',
            index=models.Index(fields=['mac_address'], name='stores_stor_mac_add_0699fa_idx'),
        ),
        migrations.AddIndex(
            model_name='storedevice',
            index=models.Index(fields=['hardware_id'], name='stores_stor_hardwar_6127b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='storeoperatinghours',
            constraint=models.UniqueConstraint(fields=('store', 'day'), name='unique_store_day'),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['user', 'is_active'], name='stores_user_user_id_709097_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['store', 'is_active'], name='stores_user_store_i_b9cd77_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['store_device', 'is_active'], name='stores_user_store_d_c0c8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['device_fingerprint'], name='stores_user_device__05ecf7_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['ip_address', 'created_at'], name='stores_user_ip_addr_1005d0_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['is_suspicious', 'is_active'], name='stores_user_is_susp_32de1a_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['status', 'created_at'], name='stores_user_status_ccb730_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['expires_at'], name='stores_user_expires_ef11e2_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['user', 'status'], name='stores_secu_user_id_978ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['store', 'status'], name='stores_secu_store_i_687909_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['alert_type', 'status'], name='stores_secu_alert_t_054805_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['severity', 'status'], name='stores_secu_severit_dd9547_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['created_at', 'status'], name='stores_secu_created_3045d3_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['notified', 'status'], name='stores_secu_notifie_948149_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceoperatorlog',
            index=models.Index(fields=['store', 'timestamp'], name='stores_devi_store_i_f6c8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceoperatorlog',
            index=models.Index(fields=['user', 'timestamp'], name='stores_devi_user_id_01915e_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceoperatorlog',
            index=models.Index(fields=['device', 'timestamp'], name='stores_devi_device__542214_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceoperatorlog',
            index=models.Index(fields=['action', 'timestamp'], name='stores_devi_action_b0799f_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceoperatorlog',
            index=models.Index(fields=['is_efris_related', 'timestamp'], name='stores_devi_is_efri_0104d4_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceoperatorlog',
            index=models.Index(fields=['session', 'timestamp'], name='stores_devi_session_f97d89_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceoperatorlog',
            index=models.Index(fields=['success', 'timestamp'], name='stores_devi_success_203f94_idx'),
        ),
    ]
