# Generated by Django 5.0.6 on 2025-12-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_auto_fiscalize_sales',
            field=models.BooleanField(default=True, verbose_name='Store Auto-Fiscalize Sales'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_auto_sync_products',
            field=models.BooleanField(default=True, verbose_name='Store Auto-Sync Products'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_efris_api_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Store EFRIS API Key'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_efris_client_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Store EFRIS Client ID'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_efris_integration_mode',
            field=models.CharField(choices=[('online', 'Online Mode'), ('offline', 'Offline Mode')], default='online', max_length=10, verbose_name='Store EFRIS Integration Mode'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_efris_is_active',
            field=models.BooleanField(default=False, verbose_name='Store EFRIS Active'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_efris_is_production',
            field=models.BooleanField(default=False, verbose_name='Store EFRIS Production Mode'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_efris_key_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Store Key Password'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_efris_last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Store EFRIS Last Sync'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_efris_private_key',
            field=models.TextField(blank=True, null=True, verbose_name='Store Private Key'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_efris_public_certificate',
            field=models.TextField(blank=True, null=True, verbose_name='Store Public Certificate'),
        ),
        migrations.AddField(
            model_name='store',
            name='use_company_efris',
            field=models.BooleanField(default=True, help_text='When checked, uses company-level EFRIS settings. Uncheck to use store-specific settings.', verbose_name='Use Company EFRIS Configuration'),
        ),
    ]
