# Generated by Django 5.0.6 on 2025-12-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_store_auto_fiscalize_sales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accessible_by_all',
            field=models.BooleanField(default=False, help_text='If checked, all users in the company can access this store', verbose_name='Accessible by All Company Users'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_managers',
            field=models.ManyToManyField(blank=True, help_text='Users who can manage this store', related_name='managed_stores', to=settings.AUTH_USER_MODEL, verbose_name='Store Managers'),
        ),
        migrations.AlterField(
            model_name='store',
            name='staff',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this store', related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Staff'),
        ),
        migrations.CreateModel(
            name='StoreAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view', 'View Only'), ('staff', 'Staff Access'), ('manager', 'Manager Access'), ('admin', 'Admin Access')], default='staff', max_length=20, verbose_name='Access Level')),
                ('can_view_sales', models.BooleanField(default=True)),
                ('can_create_sales', models.BooleanField(default=True)),
                ('can_view_inventory', models.BooleanField(default=True)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_fiscalize', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_access_grants', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='stores.store', verbose_name='Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_access_permissions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Store Access Permission',
                'verbose_name_plural': 'Store Access Permissions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='stores_stor_user_id_5fd29b_idx'), models.Index(fields=['store', 'is_active'], name='stores_stor_store_i_a57e73_idx'), models.Index(fields=['access_level', 'is_active'], name='stores_stor_access__7e72af_idx')],
                'unique_together': {('user', 'store')},
            },
        ),
    ]
