# Generated by Django 5.0.6 on 2025-12-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_accessible_by_all_store_store_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_efris_certificate_fingerprint',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Store Certificate Fingerprint'),
        ),
    ]
