# Generated by Django 5.0.6 on 2025-12-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_store_efris_certificate_fingerprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_efris_api_key',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_efris_client_id',
        ),
    ]
