# Generated by Django 5.0.6 on 2025-12-27 14:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_crosscompanytransaction_companyrelationship'),
        ('stores', '0005_remove_store_store_efris_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Main Warehouse', 'Central Depot'", max_length=255, verbose_name='StockStore Name')),
                ('code', models.CharField(help_text="Unique identifier, e.g., 'WH-001'", max_length=20, unique=True, verbose_name='StockStore Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('physical_address', models.TextField(verbose_name='Physical Address')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region/District')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9]+$', 'Enter a valid phone number.')], verbose_name='Primary Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Warehouse Manager')),
                ('manager_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]+$', 'Enter a valid phone number.')], verbose_name='Manager Phone')),
                ('is_main_stockstore', models.BooleanField(default=False, help_text='Primary warehouse for the company', verbose_name='Main StockStore')),
                ('auto_approve_transfers', models.BooleanField(default=False, help_text='Automatically approve transfer requests to branches', verbose_name='Auto-Approve Transfers')),
                ('requires_manager_approval', models.BooleanField(default=True, help_text='Transfers need manager approval', verbose_name='Requires Manager Approval')),
                ('min_stock_alert_enabled', models.BooleanField(default=True, help_text='Alert when stock falls below threshold', verbose_name='Enable Low Stock Alerts')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Used for ordering in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_stores', to='company.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stockstores', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('managers', models.ManyToManyField(blank=True, help_text='Users who can manage this stockstore', related_name='managed_stockstores', to=settings.AUTH_USER_MODEL, verbose_name='Warehouse Managers')),
                ('staff', models.ManyToManyField(blank=True, help_text='Users who can access this stockstore', related_name='accessible_stockstores', to=settings.AUTH_USER_MODEL, verbose_name='Warehouse Staff')),
            ],
            options={
                'verbose_name': 'Stock Store (Warehouse)',
                'verbose_name_plural': 'Stock Stores (Warehouses)',
                'ordering': ['-is_main_stockstore', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='stores_stoc_company_6f3b2b_idx'), models.Index(fields=['is_main_stockstore'], name='stores_stoc_is_main_0afdea_idx'), models.Index(fields=['code'], name='stores_stoc_code_e6b458_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockstore',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_stockstore_code_per_company'),
        ),
    ]
