# Generated by Django 5.0.6 on 2026-02-20 07:30

import uuid
from django.db import migrations, models


def populate_sync_ids(apps, schema_editor):
    models_to_update = [
        ('stores', 'DeviceFingerprint'),
        ('stores', 'DeviceOperatorLog'),
        ('stores', 'SecurityAlert'),
        ('stores', 'StockStore'),
        ('stores', 'Store'),
        ('stores', 'StoreAccess'),
        ('stores', 'StoreDevice'),
        ('stores', 'StoreOperatingHours'),
        ('stores', 'UserDeviceSession'),
    ]
    for app_label, model_name in models_to_update:
        try:
            Model = apps.get_model(app_label, model_name)
            for obj in Model.objects.filter(sync_id__isnull=True):
                obj.sync_id = uuid.uuid4()
                obj.save(update_fields=['sync_id'])
        except Exception as e:
            print(f"Skipping {app_label}.{model_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_stockstore_and_more'),
    ]

    operations = [
        # STEP 1: Add columns without unique constraint
        migrations.AddField(
            model_name='devicefingerprint',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='deviceoperatorlog',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='stockstore',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='store',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='storeaccess',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='storedevice',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='storeoperatinghours',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='userdevicesession',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),

        # STEP 2: Populate unique UUIDs for all existing rows per tenant
        migrations.RunPython(
            populate_sync_ids,
            migrations.RunPython.noop,
        ),

        # STEP 3: Now safe to add unique constraint
        migrations.AlterField(
            model_name='devicefingerprint',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='deviceoperatorlog',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='stockstore',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='storeaccess',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='storedevice',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='storeoperatinghours',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='userdevicesession',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]