# Generated by Django 5.0.6 on 2026-03-06 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_devicefingerprint_sync_id_deviceoperatorlog_sync_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevicesession',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=100, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='devicefingerprint',
            name='device_name',
            field=models.CharField(max_length=100, verbose_name='Device Name'),
        ),
        migrations.AlterField(
            model_name='devicefingerprint',
            name='trust_score',
            field=models.IntegerField(default=0, verbose_name='Trust Score'),
        ),
        migrations.AlterField(
            model_name='deviceoperatorlog',
            name='details',
            field=models.JSONField(default=dict, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='deviceoperatorlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='deviceoperatorlog',
            name='is_efris_related',
            field=models.BooleanField(default=False, verbose_name='EFRIS Related'),
        ),
        migrations.AlterField(
            model_name='deviceoperatorlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='stores.userdevicesession', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='deviceoperatorlog',
            name='success',
            field=models.BooleanField(default=True, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='alert_data',
            field=models.JSONField(default=dict, verbose_name='Alert Data'),
        ),
        migrations.AlterField(
            model_name='stockstore',
            name='auto_approve_transfers',
            field=models.BooleanField(default=False, verbose_name='Auto-Approve Transfers'),
        ),
        migrations.AlterField(
            model_name='stockstore',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='StockStore Code'),
        ),
        migrations.AlterField(
            model_name='stockstore',
            name='is_main_stockstore',
            field=models.BooleanField(default=False, verbose_name='Main StockStore'),
        ),
        migrations.AlterField(
            model_name='stockstore',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_stockstores', to=settings.AUTH_USER_MODEL, verbose_name='Warehouse Managers'),
        ),
        migrations.AlterField(
            model_name='stockstore',
            name='min_stock_alert_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable Low Stock Alerts'),
        ),
        migrations.AlterField(
            model_name='stockstore',
            name='name',
            field=models.CharField(max_length=255, verbose_name='StockStore Name'),
        ),
        migrations.AlterField(
            model_name='stockstore',
            name='requires_manager_approval',
            field=models.BooleanField(default=True, verbose_name='Requires Manager Approval'),
        ),
        migrations.AlterField(
            model_name='stockstore',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockstore',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='accessible_stockstores', to=settings.AUTH_USER_MODEL, verbose_name='Warehouse Staff'),
        ),
        migrations.AlterField(
            model_name='userdevicesession',
            name='is_new_device',
            field=models.BooleanField(default=False, verbose_name='New Device'),
        ),
        migrations.AlterField(
            model_name='userdevicesession',
            name='is_suspicious',
            field=models.BooleanField(default=False, verbose_name='Suspicious Activity'),
        ),
    ]
