# Generated by Django 5.0.6 on 2026-03-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_userdevicesession_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='physical_address',
            field=models.TextField(blank=True, verbose_name='Physical Address'),
        ),
    ]
