# Generated by Django 5.0.6 on 2025-11-17 04:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(max_length=50, verbose_name='Batch Type')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('recipient_count', models.IntegerField(default=0, verbose_name='Recipient Count')),
                ('success_count', models.IntegerField(default=0, verbose_name='Success Count')),
                ('failure_count', models.IntegerField(default=0, verbose_name='Failure Count')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Notification Batch',
                'verbose_name_plural': 'Notification Batches',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('maintenance', 'Maintenance'), ('update', 'Update'), ('feature', 'New Feature'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='Type')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_dismissible', models.BooleanField(default=True, verbose_name='Dismissible')),
                ('show_on_dashboard', models.BooleanField(default=True, verbose_name='Show on Dashboard')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Action URL')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='Action Text')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dismissed_by', models.ManyToManyField(blank=True, related_name='dismissed_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_expense_approved', models.BooleanField(default=True, verbose_name='Email on Expense Approved')),
                ('email_on_expense_rejected', models.BooleanField(default=True, verbose_name='Email on Expense Rejected')),
                ('email_on_expense_paid', models.BooleanField(default=True, verbose_name='Email on Expense Paid')),
                ('email_on_comment', models.BooleanField(default=True, verbose_name='Email on Comment')),
                ('email_on_budget_alert', models.BooleanField(default=True, verbose_name='Email on Budget Alert')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push Notifications Enabled')),
                ('push_on_expense_approved', models.BooleanField(default=True, verbose_name='Push on Expense Approved')),
                ('push_on_expense_rejected', models.BooleanField(default=True, verbose_name='Push on Expense Rejected')),
                ('digest_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='realtime', max_length=20, verbose_name='Digest Frequency')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text="Don't send notifications during this time", null=True, verbose_name='Quiet Hours Start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours End')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('expense_created', 'Expense Created'), ('expense_submitted', 'Expense Submitted'), ('expense_approved', 'Expense Approved'), ('expense_rejected', 'Expense Rejected'), ('expense_paid', 'Expense Paid'), ('expense_comment', 'Expense Comment'), ('expense_reminder', 'Expense Reminder'), ('expense_overdue', 'Expense Overdue'), ('budget_alert', 'Budget Alert'), ('export_complete', 'Export Complete'), ('system', 'System Notification'), ('announcement', 'Announcement')], db_index=True, default='info', max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('action_url', models.CharField(blank=True, help_text='URL to redirect when notification is clicked', max_length=500, verbose_name='Action URL')),
                ('action_text', models.CharField(blank=True, default='View', max_length=100, verbose_name='Action Text')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('is_emailed', models.BooleanField(default=False, verbose_name='Emailed')),
                ('emailed_at', models.DateTimeField(blank=True, null=True, verbose_name='Emailed At')),
                ('priority', models.IntegerField(default=0, help_text='Higher numbers = higher priority', verbose_name='Priority')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx')],
            },
        ),
    ]
