# Generated by Django 5.0.6 on 2025-11-21 13:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('SALES', 'Sales & Orders'), ('INVENTORY', 'Inventory & Stock'), ('EFRIS', 'EFRIS & Compliance'), ('FINANCE', 'Finance & Payments'), ('SYSTEM', 'System & Security'), ('USER', 'User Activity'), ('MESSAGING', 'Messages'), ('REPORTS', 'Reports'), ('COMPANY', 'Company Updates')], max_length=20)),
                ('icon', models.CharField(choices=[('shopping-cart', 'Shopping Cart'), ('package', 'Package'), ('file-text', 'Document'), ('alert-triangle', 'Alert'), ('check-circle', 'Success'), ('info', 'Information'), ('dollar-sign', 'Money'), ('user', 'User'), ('bell', 'Bell'), ('settings', 'Settings')], default='bell', max_length=30)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Notification Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_model', models.CharField(help_text="Model that triggers notification (e.g., 'sales.Sale')", max_length=100)),
                ('trigger_event', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('threshold_reached', 'Threshold Reached')], max_length=50)),
                ('conditions', models.JSONField(default=dict, help_text='Conditions that must be met for rule to trigger')),
                ('recipient_type', models.CharField(choices=[('SPECIFIC_USERS', 'Specific Users'), ('USER_ROLES', 'User Roles'), ('STORE_STAFF', 'Store Staff'), ('COMPANY_ADMINS', 'Company Admins'), ('CREATOR', 'Object Creator'), ('CUSTOM', 'Custom Logic')], max_length=30)),
                ('user_roles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('throttle_enabled', models.BooleanField(default=False)),
                ('throttle_minutes', models.PositiveIntegerField(default=60, help_text='Minimum minutes between notifications')),
                ('triggered_count', models.PositiveIntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('sale_completed', 'Sale Completed'), ('sale_voided', 'Sale Voided'), ('sale_refunded', 'Sale Refunded'), ('payment_received', 'Payment Received'), ('invoice_created', 'Invoice Created'), ('invoice_overdue', 'Invoice Overdue'), ('low_stock', 'Low Stock Alert'), ('out_of_stock', 'Out of Stock'), ('stock_received', 'Stock Received'), ('product_added', 'Product Added'), ('efris_fiscalized', 'EFRIS Fiscalized'), ('efris_failed', 'EFRIS Fiscalization Failed'), ('efris_sync_required', 'EFRIS Sync Required'), ('efris_certificate_expiring', 'EFRIS Certificate Expiring'), ('budget_exceeded', 'Budget Exceeded'), ('report_generated', 'Report Generated'), ('payment_due', 'Payment Due'), ('user_login', 'User Login'), ('suspicious_activity', 'Suspicious Activity'), ('device_authorized', 'Device Authorized'), ('backup_completed', 'Backup Completed'), ('subscription_expiring', 'Subscription Expiring'), ('trial_ending', 'Trial Ending'), ('company_suspended', 'Company Suspended'), ('new_message', 'New Message'), ('message_mention', 'Mentioned in Message'), ('custom', 'Custom Event')], max_length=50, unique=True)),
                ('title_template', models.CharField(help_text='Use {{variable}} for placeholders', max_length=255)),
                ('message_template', models.TextField(help_text='Use {{variable}} for placeholders')),
                ('send_in_app', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('action_url_template', models.CharField(blank=True, help_text='URL template with {{variable}} placeholders', max_length=500)),
                ('email_subject_template', models.CharField(blank=True, max_length=255)),
                ('email_body_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationbatch',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Notification Batches'},
        ),
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'verbose_name_plural': 'Notification Preferences'},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_a972ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_684eac_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_d8746a_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='emailed_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_emailed',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notificationbatch',
            name='batch_type',
        ),
        migrations.RemoveField(
            model_name='notificationbatch',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='notificationbatch',
            name='failure_count',
        ),
        migrations.RemoveField(
            model_name='notificationbatch',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='notificationbatch',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='notificationbatch',
            name='success_count',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_on_budget_alert',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_on_comment',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_on_expense_approved',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_on_expense_paid',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_on_expense_rejected',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='push_on_expense_approved',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='push_on_expense_rejected',
        ),
        migrations.AddField(
            model_name='notification',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_via_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_via_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_via_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, help_text='Context data for template rendering', null=True),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='recipients',
            field=models.ManyToManyField(related_name='notification_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Schedule for future delivery', null=True),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='category_preferences',
            field=models.JSONField(default=dict, help_text='Per-category notification settings'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='digest_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='dnd_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='dnd_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='event_preferences',
            field=models.JSONField(default=dict, help_text='Per-event notification settings'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='in_app_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('ALERT', 'Alert')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationbatch',
            name='recipient_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notificationbatch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENDING', 'Sending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='digest_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='push_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationcategory'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='specific_users',
            field=models.ManyToManyField(blank=True, related_name='notification_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='notifications.notificationcategory'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='notifications.notificationtemplate'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'category', 'is_read'], name='notificatio_recipie_28e0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'is_read'], name='notificatio_priorit_60753b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant_id', 'created_at'], name='notificatio_tenant__b302ab_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification', 'channel'], name='notificatio_notific_9169c3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_68c9bc_idx'),
        ),
    ]
