# Generated by Django 5.0.6 on 2025-11-22 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_notificationcategory_notificationlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationbatch',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, help_text='Context data for template rendering'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant_id', 'is_sent'], name='notificatio_tenant__af7bde_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'retry_count'], name='notificatio_status_25b332_idx'),
        ),
    ]
