# Generated by Django 5.0.6 on 2025-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationbatch_context_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
