# Generated by Django 5.0.6 on 2025-11-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='non_negative_unit_price'),
        ),
    ]
