# Generated by Django 5.0.6 on 2025-11-18 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saleitem',
            name='positive_quantity',
        ),
        migrations.RemoveConstraint(
            model_name='saleitem',
            name='non_negative_unit_price',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], default='PRODUCT', help_text='Type of item being sold', max_length=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.service'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='positive_quantity_saleitem'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='non_negative_unit_price_saleitem'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('product__isnull', False), ('service__isnull', True)), models.Q(('product__isnull', True), ('service__isnull', False)), _connector='OR'), name='product_or_service_required'),
        ),
    ]
