# Generated by Django 5.0.6 on 2025-12-04 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0003_alter_saleitem_product'),
        ('stores', '0002_store_store_auto_fiscalize_sales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_store_i_1a7184_idx',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='cart',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt (Immediate Payment)'), ('INVOICE', 'Invoice (Credit Sale)'), ('PROFORMA', 'Proforma/Quotation'), ('ESTIMATE', 'Estimate')], default='RECEIPT', max_length=20, verbose_name='Document Type'),
        ),
        migrations.AddField(
            model_name='cart',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='cart',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='terms',
            field=models.TextField(blank=True, null=True, verbose_name='Terms'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('PARTIAL', 'Partial Payment'), ('ADVANCE', 'Advance Payment'), ('FINAL', 'Final Payment')], default='FULL', max_length=20, verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cashier_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cashier Name'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer_copy',
            field=models.BooleanField(default=True, verbose_name='Customer Copy'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_summary',
            field=models.JSONField(default=dict, verbose_name='Payment Summary'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='terminal_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Terminal ID'),
        ),
        migrations.AddField(
            model_name='sale',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Document Number'),
        ),
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('NOT_APPLICABLE', 'Not Applicable')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='is_duplicate',
            field=models.BooleanField(default=False, verbose_name='Is Duplicate'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='print_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Print Count'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='printed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Printed At'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='printed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Printed By'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_data',
            field=models.JSONField(default=dict, verbose_name='Receipt Data'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Receipt Number'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_detail', to='sales.sale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt (Immediate Payment)'), ('INVOICE', 'Invoice (Credit Sale)'), ('PROFORMA', 'Proforma/Quotation'), ('ESTIMATE', 'Estimate')], db_index=True, default='RECEIPT', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('VOIDED', 'Voided'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='sales_recei_receipt_0e369b_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['sale'], name='sales_recei_sale_id_1567f1_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['printed_at'], name='sales_recei_printed_28fe00_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'status', 'created_at'], name='sales_sale_store_i_16fc74_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['document_type'], name='sales_sale_documen_a13e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['document_number'], name='sales_sale_documen_9cfbcd_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_status'], name='sales_sale_payment_f41ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['due_date'], name='sales_sale_due_dat_626ea7_idx'),
        ),
    ]
