# Generated by Django 5.0.6 on 2025-12-12 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_sales_sale_store_i_1a7184_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('BEFORE_DUE', 'Before Due Date'), ('ON_DUE', 'On Due Date'), ('OVERDUE_3', '3 Days Overdue'), ('OVERDUE_7', '7 Days Overdue'), ('OVERDUE_14', '14 Days Overdue'), ('OVERDUE_30', '30 Days Overdue'), ('MANUAL', 'Manual Reminder')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('scheduled_for', models.DateTimeField(help_text='When this reminder should be sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='sales.sale')),
            ],
            options={
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['sale', 'status'], name='sales_payme_sale_id_0caa99_idx'), models.Index(fields=['scheduled_for', 'status'], name='sales_payme_schedul_849299_idx'), models.Index(fields=['reminder_type'], name='sales_payme_reminde_619b32_idx')],
            },
        ),
    ]
