# Generated by Django 5.0.6 on 2025-12-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_paymentreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='stock_deducted',
            field=models.BooleanField(default=False, verbose_name='Stock Deducted'),
        ),
    ]
