# Generated by Django 5.0.6 on 2025-12-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_saleitem_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original product/service price before any override', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price_override_reason',
            field=models.CharField(blank=True, help_text='Reason for price override', max_length=200, null=True),
        ),
    ]
