# Generated by Django 5.0.6 on 2025-12-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_saleitem_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('INVOICE', 'Invoice'), ('PROFORMA', 'Proforma/Quotation'), ('ESTIMATE', 'Estimate')], default='RECEIPT', max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('INVOICE', 'Invoice'), ('PROFORMA', 'Proforma/Quotation'), ('ESTIMATE', 'Estimate')], db_index=True, default='RECEIPT', max_length=20),
        ),
    ]
