# Generated by Django 5.0.6 on 2026-01-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_cart_document_type_alter_sale_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='fiscalization_error',
            field=models.TextField(blank=True, help_text='Error message if fiscalization failed', null=True, verbose_name='Fiscalization Error'),
        ),
    ]
