# Generated by Django 5.0.6 on 2026-01-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_fiscalization_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='fiscalization_error',
        ),
    ]
