# Generated by Django 5.0.6 on 2026-01-10 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_sale_fiscalization_error'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saleitem',
            name='positive_quantity_saleitem',
        ),
        migrations.RemoveConstraint(
            model_name='saleitem',
            name='non_negative_unit_price_saleitem',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
