# Generated by Django 5.0.6 on 2026-01-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_sale_export_cleared_at_sale_export_delivery_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='export_buyer_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='export_buyer_passport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='export_currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
        migrations.AddField(
            model_name='sale',
            name='export_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
