# Generated by Django 5.0.6 on 2026-01-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_sale_export_buyer_country_sale_export_buyer_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('INVOICE', 'Invoice'), ('EXPORT_INVOICE', 'Export_Invoice'), ('PROFORMA', 'Proforma/Quotation'), ('ESTIMATE', 'Estimate')], default='RECEIPT', max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('INVOICE', 'Invoice'), ('EXPORT_INVOICE', 'Export_Invoice'), ('PROFORMA', 'Proforma/Quotation'), ('ESTIMATE', 'Estimate')], db_index=True, default='RECEIPT', max_length=20),
        ),
    ]
