# Generated by Django 5.0.6 on 2026-02-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_cart_document_type_alter_sale_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='export_piece_measure_unit',
            field=models.CharField(blank=True, help_text='3-char code from T115 exportRateUnit (e.g. "101"=per stick)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='export_piece_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of pieces — mandatory in T109 goodsDetails when invoiceIndustryCode=102', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='export_total_weight',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Net weight in KGM — mandatory in T109 goodsDetails when invoiceIndustryCode=102', max_digits=12, null=True),
        ),
    ]
