# Generated by Django 5.0.6 on 2026-02-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_saleitem_export_piece_measure_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_terms_code',
            field=models.CharField(blank=True, help_text='MANDATORY for exports: FOB, CIF, CFR, CPT, DAP, DDP, etc.', max_length=3, verbose_name='Delivery Terms (Incoterms)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_industry_code',
            field=models.CharField(default='101', help_text='101=Domestic, 102=Export', max_length=3, verbose_name='Invoice Industry Code'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_export_sale',
            field=models.BooleanField(db_index=True, default=False, help_text='Sale is an export invoice (invoiceIndustryCode=102)', verbose_name='Export Sale'),
        ),
    ]
