# Generated by Django 5.0.6 on 2026-02-20 06:47

import uuid
from django.db import migrations, models


def populate_sync_ids(apps, schema_editor):
    models_to_update = [
        ('sales', 'Cart'),
        ('sales', 'CartItem'),
        ('sales', 'Payment'),
        ('sales', 'Receipt'),
        ('sales', 'Sale'),
        ('sales', 'SaleItem'),
    ]
    for app_label, model_name in models_to_update:
        try:
            Model = apps.get_model(app_label, model_name)
            for obj in Model.objects.filter(sync_id__isnull=True):
                obj.sync_id = uuid.uuid4()
                obj.save(update_fields=['sync_id'])
        except Exception as e:
            print(f"Skipping {app_label}.{model_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_cart_document_type_alter_sale_document_type'),
    ]

    operations = [
        # STEP 1: Add columns WITHOUT unique constraint
        migrations.AddField(
            model_name='cart',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),

        # STEP 2: Populate unique UUIDs for all existing rows
        migrations.RunPython(
            populate_sync_ids,
            migrations.RunPython.noop,
        ),

        # STEP 3: Now add unique + index — safe because all rows have values
        migrations.AlterField(
            model_name='cart',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sync_id',
            field=models.UUIDField(blank=True, null=True, unique=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]