# Generated by Django 5.0.6 on 2026-03-08 07:44

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_sync_id_customercreditstatement_sync_id_and_more'),
        ('inventory', '0012_stocktransfer_transfer_date'),
        ('sales', '0020_alter_payment_sync_id_alter_receipt_sync_id_and_more'),
        ('stores', '0008_userdevicesession_timezone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_store_i_e6f7be_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_documen_a13e7d_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sale_store_status_date_idx',
            old_name='sales_sale_store_i_16fc74_idx',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.service'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='related_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='sales.sale'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'document_type', 'created_at'], name='sale_store_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'payment_status', 'due_date'], name='sale_store_payment_due_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'is_fiscalized', 'document_type'], name='sale_store_fiscal_type_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', 'document_type', 'payment_status'], name='sale_customer_credit_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['transaction_type', 'status', 'store'], name='sale_txtype_status_store_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(condition=models.Q(('document_type__in', ['RECEIPT', 'INVOICE']), ('is_fiscalized', False)), fields=['store', 'created_at'], name='sale_pending_fiscal_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=django.contrib.postgres.indexes.GinIndex(fields=['document_number'], name='sale_docnum_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=django.contrib.postgres.indexes.GinIndex(fields=['efris_invoice_number'], name='sale_efris_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('cart', 'product'), name='unique_cart_product'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('cart', 'service'), name='unique_cart_service'),
        ),
    ]
