# Generated by Django 5.0.6 on 2026-03-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_remove_cartitem_unique_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Receipt Number'),
        ),
    ]
