# Generated by Django 5.0.6 on 2026-04-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_payment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='efris_exempt',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this sale was created during a pause window and will never be sent for fiscalization.', verbose_name='EFRIS Exempt'),
        ),
        migrations.AddField(
            model_name='sale',
            name='efris_exemption_reason',
            field=models.CharField(blank=True, default='', help_text='Describes why this sale is exempt from fiscalization.', max_length=255, verbose_name='EFRIS Exemption Reason'),
        ),
    ]
