# Generated by Django 5.0.6 on 2026-04-19 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_sale_efris_exempt_sale_efris_exemption_reason'),
        ('stores', '0009_alter_store_physical_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceReductionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_item_key', models.CharField(help_text='Frontend key e.g. "product_42". Used to match the cart row.', max_length=100, verbose_name='Cart item key')),
                ('item_name', models.CharField(help_text='Snapshot of the item name at request time.', max_length=255, verbose_name='Item name')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Original price')),
                ('requested_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Requested price')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity in cart')),
                ('employee_note', models.TextField(blank=True, help_text='Optional reason the employee provided.', verbose_name='Employee note')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=10)),
                ('admin_note', models.TextField(blank=True, help_text='Optional note from admin on approval or rejection.', verbose_name='Admin note')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_reduction_requests', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_price_requests', to=settings.AUTH_USER_MODEL, verbose_name='Resolved by')),
                ('sale_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_reduction_request', to='sales.saleitem', verbose_name='Sale item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_reduction_requests', to='stores.store')),
            ],
            options={
                'verbose_name': 'Price Reduction Request',
                'verbose_name_plural': 'Price Reduction Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='sales_price_employe_ad82fb_idx'), models.Index(fields=['store', 'status', '-created_at'], name='sales_price_store_i_d3dbc9_idx'), models.Index(fields=['status', '-created_at'], name='sales_price_status_32d1a9_idx')],
            },
        ),
    ]
