# Generated by Django 5.0.6 on 2025-11-14 13:01

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicNewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'public_newsletter_subscribers',
            },
        ),
        migrations.CreateModel(
            name='SubdomainReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.SlugField(max_length=63, unique=True)),
                ('reason', models.CharField(choices=[('SYSTEM', 'System Reserved'), ('BRAND', 'Brand Protection'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'public_subdomain_reservations',
            },
        ),
        migrations.CreateModel(
            name='TenantSignupRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('subdomain', models.SlugField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9-]+$', 'Only lowercase letters, numbers, and hyphens allowed')])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(default='Uganda', max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_phone', models.CharField(max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(blank=True, max_length=50)),
                ('estimated_users', models.PositiveIntegerField(default=1)),
                ('selected_plan', models.CharField(choices=[('FREE', 'Free Trial'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('tenant_created', models.BooleanField(default=False)),
                ('created_company_id', models.CharField(blank=True, max_length=10, null=True)),
                ('created_schema_name', models.CharField(blank=True, max_length=63, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referral_source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'public_tenant_signup_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subdomain'], name='public_tena_subdoma_cc0cf0_idx'), models.Index(fields=['email'], name='public_tena_email_de7076_idx'), models.Index(fields=['status'], name='public_tena_status_dcb7f8_idx'), models.Index(fields=['created_at'], name='public_tena_created_200a5e_idx')],
            },
        ),
    ]
