# Generated by Django 5.0.6 on 2025-11-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_accounts', '0001_initial'),
        ('public_router', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('signup_notification_sent', models.BooleanField(default=False)),
                ('signup_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notification_sent', models.BooleanField(default=False)),
                ('approval_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('generated_password', models.CharField(blank=True, max_length=255, null=True)),
                ('login_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_signups', to='public_accounts.publicuser')),
                ('signup_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='public_router.tenantsignuprequest')),
            ],
            options={
                'db_table': 'public_tenant_approval_workflow',
            },
        ),
        migrations.CreateModel(
            name='TenantNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SIGNUP_TO_ADMIN', 'Signup Notification to Admin'), ('APPROVAL_TO_CLIENT', 'Approval Notification to Client'), ('REJECTION_TO_CLIENT', 'Rejection Notification to Client'), ('REMINDER_TO_ADMIN', 'Reminder to Admin')], max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('sent_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('signup_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='public_router.tenantsignuprequest')),
            ],
            options={
                'db_table': 'public_tenant_notification_log',
                'ordering': ['-sent_at'],
            },
        ),
    ]
