# Generated by Django 5.0.6 on 2026-03-10 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_router', '0002_tenantapprovalworkflow_tenantnotificationlog'),
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantapprovalworkflow',
            name='referral_signup',
            field=models.ForeignKey(blank=True, help_text='The referral record that brought this signup, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_workflows', to='referral.referralsignup'),
        ),
    ]
