# Generated by Django 5.0.6 on 2026-03-25 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_companymodule_paid_through'),
        ('public_router', '0003_tenantapprovalworkflow_referral_signup'),
        ('referral', '0002_partner_ad_promo_text_partner_ad_tagline_and_more'),
    ]

    operations = [
        # ── 1. Harmless help_text update on referral_signup ───────────────────
        migrations.AlterField(
            model_name='tenantapprovalworkflow',
            name='referral_signup',
            field=models.ForeignKey(
                blank=True,
                help_text='The referral record that brought this signup, if any.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='approval_workflows',
                to='referral.referralsignup',
            ),
        ),

        # ── 2. Clear old VARCHAR plan strings BEFORE altering the column ──────
        #
        # The previous migration stored plan choices as plain strings in a
        # VARCHAR column (e.g. "FREE", "BASIC", "PRO", "ENTERPRISE").
        # The AlterField below converts that column to a BigIntegerField FK.
        # PostgreSQL cannot cast the string "FREE" to bigint, so we NULL out
        # every row first.  selected_plan is SET_NULL on the FK, so NULL is
        # a perfectly valid post-migration value.
        #
        # After running migrate, re-link existing rows with:
        #   from public_router.models import TenantSignupRequest
        #   from company.models import SubscriptionPlan
        #   free = SubscriptionPlan.objects.get(name='FREE', is_active=True)
        #   TenantSignupRequest.objects.filter(selected_plan__isnull=True).update(selected_plan=free)
        migrations.RunSQL(
            sql="""
                ALTER TABLE public_tenant_signup_requests
                    ALTER COLUMN selected_plan DROP NOT NULL;
                UPDATE public_tenant_signup_requests
                    SET selected_plan = NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ── 3. Now safe to alter: VARCHAR → BigIntegerField FK ────────────────
        migrations.AlterField(
            model_name='tenantsignuprequest',
            name='selected_plan',
            field=models.ForeignKey(
                blank=True,
                help_text='The plan the tenant chose at signup.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='signup_requests',
                to='company.subscriptionplan',
            ),
        ),
    ]