# Generated by Django 5.0.6 on 2026-03-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_router', '0004_alter_tenantapprovalworkflow_referral_signup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsignuprequest',
            name='selected_modules',
            field=models.TextField(blank=True, default='', help_text="Comma-separated module keys chosen at signup, e.g. 'inventory,sales,purchases'"),
        ),
    ]
