# Generated by Django 5.0.6 on 2026-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_router', '0005_tenantsignuprequest_selected_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsignuprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_FAILED', 'Payment Failed'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
