# Generated by Django 5.2.4 on 2025-11-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('total_pageviews', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0)),
                ('avg_pages_per_session', models.FloatField(default=0)),
                ('bounce_rate', models.FloatField(default=0)),
                ('signups_started', models.PositiveIntegerField(default=0)),
                ('signups_completed', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('top_pages', models.JSONField(blank=True, default=list)),
                ('top_sources', models.JSONField(blank=True, default=list)),
                ('top_campaigns', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Statistics',
                'verbose_name_plural': 'Daily Statistics',
                'db_table': 'public_analytics_daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('SIGNUP_STARTED', 'Signup Started'), ('SIGNUP_COMPLETED', 'Signup Completed'), ('TRIAL_STARTED', 'Trial Started'), ('DEMO_REQUESTED', 'Demo Requested'), ('CONTACT_FORM', 'Contact Form Submitted'), ('NEWSLETTER_SIGNUP', 'Newsletter Signup')], max_length=50)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, help_text='Monetary value of conversion', max_digits=10, null=True)),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.CharField(max_length=64)),
                ('first_touch_source', models.CharField(blank=True, max_length=100)),
                ('last_touch_source', models.CharField(blank=True, max_length=100)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('signup_request_id', models.UUIDField(blank=True, null=True)),
                ('company_id', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('converted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Conversion',
                'verbose_name_plural': 'Conversions',
                'db_table': 'public_analytics_conversions',
                'ordering': ['-converted_at'],
                'indexes': [models.Index(fields=['conversion_type', 'converted_at'], name='public_anal_convers_25c958_idx'), models.Index(fields=['visitor_id', 'converted_at'], name='public_anal_visitor_b9a160_idx'), models.Index(fields=['utm_campaign', 'converted_at'], name='public_anal_utm_cam_94c67c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SIGNUP', 'Signup'), ('CLICK', 'Click'), ('FORM', 'Form'), ('DOWNLOAD', 'Download'), ('VIDEO', 'Video'), ('SCROLL', 'Scroll'), ('ENGAGEMENT', 'Engagement')], max_length=50)),
                ('action', models.CharField(help_text="e.g., 'clicked_pricing_cta'", max_length=100)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('url_path', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'public_analytics_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['category', 'occurred_at'], name='public_anal_categor_1e5f66_idx'), models.Index(fields=['action', 'occurred_at'], name='public_anal_action_e78260_idx'), models.Index(fields=['session_id', 'occurred_at'], name='public_anal_session_9a8914_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('visitor_id', models.CharField(db_index=True, help_text='Anonymous visitor ID', max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot')], default='desktop', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('time_on_page_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'db_table': 'public_analytics_pageviews',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['url_path', 'viewed_at'], name='public_anal_url_pat_253726_idx'), models.Index(fields=['session_id', 'viewed_at'], name='public_anal_session_782218_idx'), models.Index(fields=['visitor_id', 'viewed_at'], name='public_anal_visitor_6266ef_idx'), models.Index(fields=['utm_campaign', 'viewed_at'], name='public_anal_utm_cam_0f7363_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_page', models.CharField(max_length=500)),
                ('exit_page', models.CharField(blank=True, max_length=500)),
                ('pages_viewed', models.PositiveIntegerField(default=0)),
                ('events_count', models.PositiveIntegerField(default=0)),
                ('converted', models.BooleanField(default=False)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Visitor Session',
                'verbose_name_plural': 'Visitor Sessions',
                'db_table': 'public_analytics_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['visitor_id', 'started_at'], name='public_anal_visitor_555612_idx'), models.Index(fields=['converted', 'started_at'], name='public_anal_convert_95ff02_idx')],
            },
        ),
    ]
