# Generated by Django 5.0.6 on 2025-11-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsession',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
